### ISSUE TITLE
same comments on all pages of one-page app

### ISSUE THREAD

**Issue by n8m** [michaelbromley/angularUtils#1]
I suspect that this is not issue of your directive, but anyway each comment on my app rendering on each page with comment section.
I'm passing the unique identifier as an attribute and use ng-bind-ready, cause I'm using async data loading. Also I've checked that directive see my identifier. 
I'm using angular routes without HTML5 mode and without any hash prefix (only # sign).
Do you have any ideas how to solve it?

**Comment by nguyenvandan** [comment]
test
