### ISSUE TITLE
disqus: Add to bower?

### ISSUE THREAD

**Issue by epelc** [michaelbromley/angularUtils#100]
Could you add the disqus directive to bower it doesn't seem to be on there. Also adding some install info to the docs would be nice besides just copy/paste the files. That doesn't work to well with ci unless you are vendoring.

**Comment by michaelbromley** [comment]
Yeah I can do this. This is the first request to do so, which is why I haven't done it yet (I have little idea how much some of these utils get used in production). Note that I'm on holiday right now so it may not be done for another couple of weeks.

**Comment by epelc** [comment]
@michaelbromley Thanks. Also your pagination directive is awesome! Can't wait to use the disqus one.
