### ISSUE TITLE
dirPaginate: unexpected token when assigning __currentPage

### ISSUE THREAD

**Issue by nursejason** [michaelbromley/angularUtils#101]
I'm using dirPaginate for an asynchronous, multi-tabbed series of grids. There are multiple boxes, each of which contain 2 tabs, and each tab can contain thousands of results -- These results are paginated. Since I have numerous different paginationators on the same page, I assign the pagination-id and allow the current-page variable to be set dynamically (this way when I change tabs, the page number will be saved).      

              <tr dir-paginate="row in r.sites | itemsPerPage: defaultLimit"
                    total-items="r.filtered_site_count"
                    pagination-id="r.name + r.customer_class + r.type">

Later on: 

            <dir-pagination-controls
                  on-page-change="pageChanged(newPageNumber, r)"
                  pagination-id="r.name + r.customer_class + r.type">
            </dir-pagination-controls>

When I load my page, I get an error akin to the following. 

Error: [$parse:syntax] Syntax Error: Token 'PLTCommercialcustomers__currentPage' is an unexpected token at column 5 of the expression [DEM PLTCommercialcustomers__currentPage] starting at [PLTCommercialcustomers__currentPage].

Any ideas as to what I'm doing wrong? I've tried doing a console.log on defaultCurrentPage in the directive, but I wasn't able to get a log to appear from your code. 

Edit: Figured out why my console.logs weren't showing up. Just needed to re-run grunt since we were in the vendor directory. Silly me!

**Comment by michaelbromley** [comment]
Just from looking at it, I suspect the problem may be to do with the space after "DEM" - does DEM correspond to `r.name`? Try stripping out white space from your ID token and see if that fixes it.

**Comment by nursejason** [comment]
Attempted that late Friday with some success. For some reason I wasn't able to put scoped functions into the `pagination-id` field originally, but was able to do so now. Unsure what my problem was there, but was having lots of issues still, as dirPagination was issuing a new paginator each time I switched tabs on my app.     
    
Switched tab viewing to be ng-show instead of ng-if, which caused the paginator and its current page state to stop being destroyed. All is well in my world of pagination. Thanks Michael and other contributors!
