### ISSUE TITLE
dirPaginate: Error message for No Results

### ISSUE THREAD

**Issue by merlihan** [michaelbromley/angularUtils#102]
Hi there,

Just wondering if there is a way to display some text like, "No results found" if the filter returns no results.

**Comment by michaelbromley** [comment]
Hi, which one of the utilities in this repo is this issue about?

**Comment by merlihan** [comment]
Ah, sorry!  DirPaginate. I am using it with a filter and am trying to achieve some kind of error message if there are no results. For example, in your demos, if you run a search for an item which does not exist in the list, the result is blank. Here I would like to give some kind of prompt to try again. 

Cheers
Kathryn

**Comment by michaelbromley** [comment]
Ah okay. You should be able to get the result you want with something like this:

```HTML
<ul>
    <li dir-paginate="item in filteredItems = (items | filter: myFilter) | itemsPerPage: 10">...</li>
</ul>
<div ng-show="filteredItems.length == 0">No results found</div>
```

To explain, this is just setting up a new value on the $scope, named `filteredItems`, which contains the result of the collection after it has been filtered. By testing the length of that collection in the `ng-show` below that, we know whether the filter has resulted in an empty collection, ie no results found.

The nice thing about this is that you don't need to do anything in your controller code, nor modify the directive itself.

**Comment by merlihan** [comment]
Thanks! Worked perfectly.

**Comment by michaelbromley** [comment]
Great!

**Comment by VampireNaeem** [comment]
Seems does not work for me, it show only when you don`t have data from backend server
