### ISSUE TITLE
How to reset to page 1 when new list is assigned to pagination?

### ISSUE THREAD

**Issue by aniketkwebonise** [michaelbromley/angularUtils#103]
I have the data of all products, at first time pagination works fine. On certain condition I am loading new list. Here it updates the number of pages and all the data as well but problem is before updating suppose I was on 3rd page then after list updates still I am on 3rd page. I should be on the first page rather than the previously selected page.

When list updates then user should be on 1st page.
Please ask if you have any doubt in understanding problem.

**Comment by michaelbromley** [comment]
Hi. You can bind to a `$scope` property to set the current page back to 1 whenever you load a new collection of data. Example:

```HTML
<div dir-paginate="item in items | itemsPerPage:10" current-page="currentPage">...</div>
```

```JavaScript
// in your controller
function loadNewList() {
    dataService.getData().then(function(result) {
        $scope.items = result;
        $scope.currentPage = 1;
    }
}
```

**Comment by aniketkwebonise** [comment]
Thanks for the quick reply. Problem is solved. Now, I am facing new issue first page is not getting selected when I assign new list. Old page selection remains as it is. Footer template updates everything number of records, from, to etc except page selection.

**Comment by michaelbromley** [comment]
Hi,

Could you provide some code so I can see what is going on?

**Comment by aniketkwebonise** [comment]
Hi,
I figured out. Problem was when I assign new list only <code>generatePagesArray</code> and <code>calculatePageNumber</code> functions are executed, <code>setCurrent</code> was not executing. So, added watch and called the <code>setCurrent</code> function

Once again thanks Michael.
