### ISSUE TITLE
dirPagination: Problems in AngularJS 1.2.0 (underscore issue)

### ISSUE THREAD

**Issue by postal2600** [michaelbromley/angularUtils#104]
When I try the example for the pagination directive I get the following error:

    Error: [$parse:isecprv] Referencing private fields in Angular expressions is disallowed! Expression: __default__currentPage

This is a "feature" in AngularJS 1.2.0, but maybe you might want to address it:
http://stackoverflow.com/questions/19917515/fixing-angularjs-1-2-0-parseisecprv-errors

**Comment by postal2600** [comment]
And of course that immediately after I post the issue, I found the answer: changed `var DEFAULT_ID = '__default';` to `var DEFAULT_ID = 'default';` and now it works

**Comment by michaelbromley** [comment]
Thanks for the heads up. I must have missed this dramatic episode in the development of Angular! I'll look into it further and decide whether it is worth making any changes next week.

**Comment by michaelbromley** [comment]
I decided against "fixing" this issue, since the underscore issue in Angular 1.2 was widely considered to be a bug and was reverted within a week with the release of 1.2.1. More info: http://angularjs.blogspot.co.uk/2013/11/on-launching-angular-12-what-we-learned.html

**Comment by postal2600** [comment]
Fair enough.
