### ISSUE TITLE
dirPaginate: track by $index breaks the directive

### ISSUE THREAD

**Issue by RahulKatariya** [michaelbromley/angularUtils#105]
If we want to allow duplicates we need to use track by $index but it doesn't work with dir-paginate. Here is the error it throws - Pagination directive: the 'itemsPerPage' filter must be set.

This is the code i am using 
tr dir-paginate="location in locations track by $index | itemsPerPage: 5">

**Comment by michaelbromley** [comment]
Try putting the "track by" part of the expression at the end:

```JavaScript
<tr dir-paginate="location in locations | itemsPerPage: 5 track by $index">
```

Let me know if that works for you.

**Comment by RahulKatariya** [comment]
Yes, It seems to work with this. Thanks a lot. Great Utility

**Comment by michaelbromley** [comment]
Cool, glad it got sorted.

**Comment by cash1981** [comment]
It seems like track by $index restarts when pagingating to another page. Is this correct behavior?
I would like the $index to continue correctly even if I am on page 2 for instance

**Comment by michaelbromley** [comment]
@cash1981 Yes, this is correct behaviour. `$index` is exposed by the ngRepeat directive and is only aware of what is displayed on the current page. To figure out the index, use this formula:

```JavaScript
absolute_index = $index + ($scope.currentPage - 1) * $scope.pageSize;
```

**Comment by cash1981** [comment]
Thanks
Will try.
Thanks for the great and easy tool
