### ISSUE TITLE
dir-paginate / dir-pagination-controls not working (node-webkit)

### ISSUE THREAD

**Issue by pirumpi** [michaelbromley/angularUtils#106]
I added the library and the template to my application. The directive dir-paginate does the iteration of the array just like ng-repeat but it does care what itemsPerPage is set to, it just display the entire array. Also dir-pagination-controls is not showing at all; it appears that the page array is empty.

Any ideas or suggestions?

**Comment by michaelbromley** [comment]
Hi,

Could you provide the relevant code so I can see what is going wrong? Also are there any errors in the console?

**Comment by pirumpi** [comment]
I'm using your basic example, I don't get any errors in the console and that is the weird part. I'm using it in node-webkit that could be doing something to the code but I didn't have the time to look into it. 
I was able to implement ui.bootstrap iu.pagination without any issues, but I just wanted to let you know in case you wanted to test your code in node-webkit.

**Comment by michaelbromley** [comment]
Okay, thanks. I've never used node-webkit but if I get time I'll check it out to see if there is a particular problem with that.

**Comment by mozami** [comment]
Just to chime in - Im also experiencing the exact same issue, and am also on Node Webkit (nw.js). The entire array gets printed irregardless of what itemsPerPage is set to. The pagination controls are not shown at all since the entire array is printed.

**Comment by michaelbromley** [comment]
Thanks. Since I'm totally clueless about node webkit, can you tell me what it is like to debug on it? And if I wanted to look into this issue, what do I need to set up to reproduce the issue in the most simple possible way?

Or, if you have already looked into it, are there any kind of error messages which may be of use?

**Comment by mozami** [comment]
Node webkit is quite easy to use and debug with. Its based on chromium and has most of the dev tools that come with chrome. 

I tried to debug the issue but didnt get very far im afraid. I do have my own homegrown pagination working on my app and was just curious to see what other/better alternatives may have to offer. I can try and set up a vanilla node webkit app and replicate the issue if you want.

**Comment by michaelbromley** [comment]
That would be really helpful if it's not too much trouble. I've just started a new job and consequently have a little less time to work on my open source stuff, so that would certainly save me some time.

**Comment by krinkere** [comment]
Same here. dir-pagination-controls is not showing at all. Using your basic example to iterate static array. 

I see ng-repeat providing me with the right data, but I don't see dir-pagination-controls.

**Comment by krinkere** [comment]
I figured it out... I had only 5 records, so when this was evaluated
<ul class="pagination" ng-if="1 < pages.length">

inside of dirPagination.tpl.html page, the control was not shown.

I removed ng-if="1 < pages.length"

and now have the control with only one page showing. That's actually what I want anyway. I dont want for control to disappear if I have only few results.

**Comment by krinkere** [comment]
Looks like my comment was edited when i posted... You need to look at the first line

ul class="pagination" ng-if="1 < pages.length"

**Comment by michaelbromley** [comment]
@krinkere thanks for the report. Does that mean that it works fine for you now, or do you also have the problem that the entire collection is being displayed rather than paginated?

**Comment by krinkere** [comment]
It works now. Basically, pagination tools appear once you have number of results more than number per page... so if you have only 3 results and results per page is 10, you wont see it. 

that's what was my issue
