### ISSUE TITLE
Search filter Server Side

### ISSUE THREAD

**Issue by mullermx** [michaelbromley/angularUtils#107]
Right now the filter searchs within  what is already being displayed, but I  need it to make a new call to the API with the query string.

Any simple way of attaching the input value to the call?

**Comment by michaelbromley** [comment]
Hi, are you referring to the pagination directive? Can you show any code for what you have tried already, or explain in a little more detail what exactly you are trying to achieve?

**Comment by mullermx** [comment]
Thanks for the quick reply.

Yes, it's about the pagination directive, since it includes the filter:q expresion, I thought it would filter  through my API call the search term.

Since it didn't, I'm going with an alternate solution:
1. remove the filter expresion  from the directive
2. in the filter input, just adding this  ng-change="pageChanged(1)"
3. $http.get('http://api.loc/catalog/page/'+pageNumber+'&q='+document.getElementById('search').value

**Comment by michaelbromley** [comment]
Yeah, you are right in that the Angular `filter` will only filter whatever is loaded into the scope - so if you are doing server-side paging then it's no good.

Your alternate solution looks fine. Have you implemented it and got it working, or do you still need help?

By the way, the line `$http.$get(http://api.loc/catalog/page/'+pageNumber+'&q='+document.getElementById('search').value)` is a bit of a non-Angular way of doing it. To get the value of the "search" input, you would more usually bind it to a $scope value and reference that value in your controller, e.g.:

```HTML
<input type="text" ng-model="search" />
```

```JavaScript
$http.$get('http://api.loc/catalog/page/'+pageNumber+'&q='+$scope.search);
```

Also, in case you don't already know about it, the debounce feature of [ng-model-options](https://docs.angularjs.org/api/ng/directive/ngModelOptions) (`ng-model-options="{ debounce: 200 }"`) is very useful in this scenario to prevent excessive API calls each time a letter is typed.

**Comment by mullermx** [comment]
Thanks!

​I did got it working that way​, and thanks for your comments; I did
implement it that way and everything looks cleaner, thanks again.

I do have one observation, for some reason, when  paginating, it scrolls
only to the half of the page, not to the very top, but I'm still figuring
if it is my code interfering or not, in case not I'll open another ticket.

**Comment by michaelbromley** [comment]
Ok. I'll close this issue then, and if the scrolling issue seems to be coming from this module, open a new issue for that. By the way, on my blog (http://www.michaelbromley.co.uk/blog) I use this pagination and it scrolls to the top fr me okay when changing pages.
