### ISSUE TITLE
DirPagination: ng-repeat not working between dir-paginate-start and dir-paginate-end

### ISSUE THREAD

**Issue by alex-dolbik** [michaelbromley/angularUtils#108]
Hello!
*ng-repeat* directive not working between **dir-paginate-start** and **dir-paginate-end**. For example:

```
<tr pagination-id="main" dir-paginate-start="item in creative.list | itemsPerPage: creative.pageSize : 'main'" total-items="creative.totalCount" ng-if="false"></tr>

<tr>
    <td>{{ item.name }}</td>
    <td>
        <span ng-repeat="size in item.sizes">{{ size }}</span>
    </td>
</tr>

<tr dir-paginate-end ng-show="false"></tr>
```

After compiling *ng-repeat* replaced by comments:
```
<!-- ngRepeat: size in item.sizes -->
```

How can I solve this problem? Thanks!

**Comment by michaelbromley** [comment]
Hi. Thanks for the report. This is a known issue - see https://github.com/michaelbromley/angularUtils/issues/92 for more information and a hacky work-around I came up with. I've not yet been able to implement a more permanent solution.
