### ISSUE TITLE
Using ng-resource with Asynchronous Data

### ISSUE THREAD

**Issue by krusk** [michaelbromley/angularUtils#109]
Hi all,

For server side paging using ng-resource, how could I incorporate my service as follows:

services.js
        
    // All of my Articles
    pfcServices.factory('pfcArticles', ['$resource', function ($resource) {
        return $resource('https://myrestcall.net/tables/articles/:articleID', { articleID: '@id' },
        {
            'update': { method: 'PATCH' }
        }
        );
    }]);

Into the "Working With Asynchronous Data" example shown instead of the http? Would I need to adjust my factory, the function in the controller, or both? 

controller.js

    .controller('UsersController', function($scope, $http) {
    $scope.users = [];
    $scope.totalUsers = 0;
    $scope.usersPerPage = 25; // this should match however many results your API puts on one page
    getResultsPage(1);

    $scope.pagination = {
        current: 1
    };

    $scope.pageChanged = function(newPage) {
        getResultsPage(newPage);
    };

    function getResultsPage(pageNumber) {
        // this is just an example, in reality this stuff should be in a service
        $http.get('path/to/api/users?page=' + pageNumber)
            .then(function(result) {
                $scope.users = result.data.Items;
                $scope.totalUsers = result.data.Count
            });
    }
    })

Thank you!
K.

**Comment by michaelbromley** [comment]
Hi,

You just need to ensure that your back-end service returns the total items, which is required to figure out the pagination. Does it do this? 

I've not used $resource much myself, but I think you'd use the `query` method to get the list of articles.

It'd be good if you take your best shot at getting it working yourself, and then get back to me with what you've tried, and what doesn't work (and any error messages etc.).

For general Angular questions not directly related to my module, try StackOverflow as you'll probably get a faster answer. 

Good luck.

**Comment by krusk** [comment]
Thanks Michael, will do. I can query for full results, but am trying to track down what Azure Mobile Web Services API defaults to for results per page, and if there is a paging call similar to GITs:

>Requests that return multiple items will be paginated to 30 items by default. You can specify further pages with the ?page parameter. For some resources, you can also set a custom page size up to 100 with the ?per_page parameter.

Regards,

Kelly

**Comment by krusk** [comment]
Update, I have found that Azure's Web Services API uses $top, $skip, and $inlinecount to handle pagination up to 50 items per page, so to get a 2nd page, the URL would look like: https://myrestcall.net/tables/articles?$top=100&$skip=50&$inlinecount=allpages

I tried to leverage this by my service as follows:

     // All Articles
    pfcServices.factory('pfcArticles', ['$resource', function ($resource) {
        return $resource('https://myrestcall.net/tables/articles/:articleID?$top=100&$skip=' + pageNumber + '&$inlinecount=allpages', { articleID: '@id' },
        {
            'query': { method: "GET", isArray: false },
            'update': { method: 'PATCH' }
        }
        );
    }]);

My controller is (note that I removed the functionality for voting to keep this post concise):

     // Articles for Home Paging Test
    pfcControllers.controller('pfcHomeArticlesCtrlTest', ['$scope', 'auth', 'pfcArticles', function ($scope, auth, pfcArticles) {

    $scope.articles = [];
    $scope.totalUsers = 0;
    $scope.usersPerPage = 50; // this should match however many results your API puts on one page
    getResultsPage(1);

    $scope.pagination = {
        current: 1
    };

    $scope.pageChanged = function (newPage) {
        getResultsPage(newPage);
    };

    function getResultsPage(pageNumber) {
        // this is just an example, in reality this stuff should be in a service
       pfcArticles.query(function(data) {
           $scope.articles = data.results;
           $scope.totalUsers = data.count;
        });
    }
    }]);

My html is as follows (note that I removed the voting functionality from the controller in this post to keep it more concise):

            <div ng-controller="pfcHomeArticlesCtrlTest">
                <table class="table table-striped">
                    <tr>
                        <th>Votes</th>
                        <th>Title</th>
                        <th>Category ID</th>
                        <th>Link</th>
                    </tr>

                    <tr dir-paginate="article in articles | itemsPerPage:10 | total-items=" totalusers">

                        <td>
                            <div class="col-md-1 voting well">
                                <div class="votingButton" ng-click="upVote(articlevote);">
                                    <i class="glyphicon glyphicon-chevron-up"></i>
                                </div>
                                <div class="badge badge-inverse">
                                    <div>{{article.articlevotes}}</div>
                                </div>
                                <div class="votingButton" ng-click="downVote(articlevote);">
                                    <i class="glyphicon glyphicon-chevron-down"></i>
                                </div>
                            </div>
                        </td>
                        <td>{{article.articletitle}}</td>
                        <td>{{article.articlecategoryid}}</td>
                        <td><a ng-href="#article/{{article.id}}/{{article.articlelink}}">{{article.articletitle}}</a></td>
                    </tr>
                </table>
                <dir-pagination-controls on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls>
            </div>

The errors I am receiving are as follows:

angular.min.js:101 Error: [$injector:unpr] http://errors.angularjs.org/1.3.4/$injector/unpr?p0=totalFilterProvider%20%3C-%20totalFilter
    at Error (native)

and 

ReferenceError: pageNumber is not defined

**Comment by michaelbromley** [comment]
Hi,

So it sounds like your API uses the [OData protocol](http://www.odata.org/documentation/odata-version-2-0/uri-conventions)

A few things I notice that would need fixing:

1. In your controller your define `articlesPerPage = 50`, but in your service example you have hard-coded the `$top=100` option, which will cause it to return 100 items per page, not 50. These two figures should match.

2. In your `getResultsPage` controller method, you need some way of telling the resource which page of results you want. In the case of OData, this would be done with the [`$skip` option](http://www.odata.org/documentation/odata-version-2-0/uri-conventions#SkipSystemQueryOption). So, if you have 50 articles per page, the first page is `$skip=0`, the second page is `$skip=50`, third page is `$skip=100` etc., or in general, `$skip = (currentPage - 1) * articlesPerPage`.

3, Although you define `totalArticles` in your controller, in your view you still have:

```HTML
<tr dir-paginate="article in articles | itemsPerPage:10 total-items=" totalusers">
```

You need to change it to `total-items="totalArticles"`.

Check out those things and then see where it stands. You might need to do a bit of research about how to set the `$top` & `$skip` values dynamically in your service, but I think it might be something like: 

```JavaScript
// in your service
return $resource('https://myrestcall.net/tables/articles/:articleID', { articleID: '@id' },
    {
        'query': { method: "GET", isArray: false },
        'update': { method: 'PATCH' }
    });

// then in your controller
pfcArticles.query({
    $skip :  ($scope.pagination.current - 1) * $scope.articlesPerPage,
    $top : $scope.articlesPerPage,
    $inlinecount: 'allpages'
}, function(data) {
   $scope.articles = data.results;
   $scope.totalArticles = data.count;
});
```

That code is totally untested so there's a strong chance you will have to get in there and fix it up to get it working.

**Comment by krusk** [comment]
Thank you. Digging in now and I will keep you posted.

**Comment by krusk** [comment]
I believe we are getting close. Using the OData I can pass dynamically. My current error is:

>TypeError: Cannot read property 'current' of undefined

My controller is as follows:

    $scope.articles = [];
    $scope.totalArticles = 0;
    $scope.articlesPerPage = 100; // this should match however many results your API puts on one page
    getResultsPage(1);

    $scope.pagination = {
        current: 1
    };

    $scope.pageChanged = function (newPage) {
        getResultsPage(newPage);
    };

    function getResultsPage(pageNumber) {
        // this is just an example, in reality this stuff should be in a service
        pfcArticles.query({ $skip: ($scope.pagination.current - 1) * $scope.articlesPerPage, $top: $scope.articlesPerPage, $inlinecount: 'allpages' }, function (data) {
           $scope.articles = data.results;
           $scope.totalArticles = data.count;
        });
    }

My service is:

    pfcServices.factory('pfcArticles', ['$resource', function ($resource) {
        return $resource('https://myrestcall.net/tables/articles/:articleID', { articleID: '@id' },
        {
            'query': { method: "GET", isArray: false },
            'update': { method: 'PATCH' }
        }
        );
    }]);

And HTML:

               <table class="table table-striped">
                    <tr>
                        <th>Votes</th>
                        <th>Title</th>
                        <th>Category ID</th>
                        <th>Link</th>
                    </tr>

                    <tr dir-paginate="article in articles | itemsPerPage:10 total-items=totalArticles">

                        <td>
                            <div class="col-md-1 voting well">
                                <div class="votingButton" ng-click="upVote(articlevote);">
                                    <i class="glyphicon glyphicon-chevron-up"></i>
                                </div>
                                <div class="badge badge-inverse">
                                    <div>{{article.articlevotes}}</div>
                                </div>
                                <div class="votingButton" ng-click="downVote(articlevote);">
                                    <i class="glyphicon glyphicon-chevron-down"></i>
                                </div>
                            </div>
                        </td>
                        <td>{{article.articletitle}}</td>
                        <td>{{article.articlecategoryid}}</td>
                        <td><a ng-href="#article/{{article.id}}/{{article.articlelink}}">{{article.articletitle}}</a></td>
                    </tr>
                </table>
                <dir-pagination-controls on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls>

**Comment by michaelbromley** [comment]
Hi,

I believe the `TypeError: Cannot read property 'current' of undefined` is occurring because you are calling `getResultsPage(1);` before defining the `$scope.pagination` object in the next line. Swap those two lines and see it goes away.

I don't quite understand the problem with the 1000 items limit. The calculation `($scope.pagination.current - 1) * $scope.articlesPerPage` should only affect the `$skip` option - which determines which item to *start from*, rather than the number of items to *return*. The `$top` option determines how many to return. So `$top` should always stay the same (100).

To explain, if you ask for `$skip=1000&$top=100`, your asking the API to give you 100 items, starting from the 1001st item in the result set.

**Comment by krusk** [comment]
Ah! I was using $top in the client side sense where at times I needed to return a larger set (ex. show more than 50 results total). What you stated makes perfect sense for server-side returns. I cannot thank you enough for your help. I ended up passing the pageNumber variable in for the $skip portion, eliminating the need for $scope.pagination.current. Here is my working code. I hope this can help others with ng-resource/oData, as you have an awesome directive!

Controller.js

    $scope.articles = [];
    $scope.totalArticles = 0;
    $scope.articlesPerPage = 10; // this should match however many results your API puts on one page
  
    getResultsPage(1);

    $scope.pageChanged = function (newPage) {
        getResultsPage(newPage);
    };

    function getResultsPage(pageNumber) {

        // currently skipping by page number * articles per page
        pfcArticles.query({ $skip: (pageNumber - 1) * $scope.articlesPerPage, $top: $scope.articlesPerPage, $inlinecount: 'allpages' }, function (data) {
           $scope.articles = data.results;
           $scope.totalArticles = data.count; // Can change to hard number to reduce total items instead of LimitTo
        });
    }

Services.js

    pfcServices.factory('pfcArticles', ['$resource', function ($resource) {
    return $resource('https://myrestcall.net/tables/articles/:articleID', { articleID: '@id' },
    {
        'query': { method: "GET", isArray: false },
        'update': { method: 'PATCH' }
    }
    );
    }]);

HTML (note that I pass the articlesPerPage via the controller)

            Sort By: <select ng-model="articleSortOrder">
                <option value="+id">ID</option>
                <option value="+articletitle">Article Title</option>
                <option value="-articlevotes">Article Votes</option>
            </select>
          
                <table class="table table-striped">
                    <tr>
                        <th>Votes</th>
                        <th>Title</th>
                        <th>Category ID</th>
                        <th>Link</th>
                    </tr>

                    <tr dir-paginate="article in articles | orderBy:articleSortOrder | itemsPerPage:articlesPerPage" total-items="totalArticles">

                        <td>
                            <div class="col-md-1 voting well">
                                <div class="votingButton" ng-click="upVote(articlevote);">
                                    <i class="glyphicon glyphicon-chevron-up"></i>
                                </div>
                                <div class="badge badge-inverse">
                                    <div>{{article.articlevotes}}</div>
                                </div>
                                <div class="votingButton" ng-click="downVote(articlevote);">
                                    <i class="glyphicon glyphicon-chevron-down"></i>
                                </div>
                            </div>
                        </td>
                        <td>{{article.articletitle}}</td>
                        <td>{{article.articlecategoryid}}</td>
                        <td><a ng-href="#article/{{article.id}}/{{article.articlelink}}">{{article.articletitle}}</a></td>
                    </tr>
                </table>
                <dir-pagination-controls on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls>

**Comment by michaelbromley** [comment]
Great! Happy to help. Good persistence ;)
