### ISSUE TITLE
How to save a state of the pagination

### ISSUE THREAD

**Issue by trinzal** [michaelbromley/angularUtils#110]
In my situation I have an array of links with details. When I go by a link and than return back, my previous pagination state is reset. Any idea how I could fix it?

**Comment by ffsantos92** [comment]
Check [ngCookies](https://docs.angularjs.org/api/ngCookies).

**Comment by michaelbromley** [comment]
Basically you need some method of saving state in your app. As mentioned above, cookies could be one option. Other options would be to store the state in a parent controller (e.g. and app-wide controller), or use a service to save and restore the pagination state.
