### ISSUE TITLE
Pagination - Can't get id's working

### ISSUE THREAD

**Issue by mckinleymedia** [michaelbromley/angularUtils#111]
First off, love this util.  Thanks for making it.
I'm hoping you can help with this issue.  I can't get the ids to function.  I put in simple text versions to test it and they break it, too.  I tried copying the text directly off the tutorial - pagination-id="branch".  I don't get any error message.  The data shows up, but the pagination disappears.  If I remove the pagination ids, the pagination works again.  
I'm using AngularJS v1.2.22 and Bootstrap v2.3.1 .  I do have a number of other modules in there as well: angular-route, underscore, jquery, jquery ui, sticky, angular-busy, zeroClipboard, ng-clip
Here's my pagination repeat code:
<tr dir-paginate="result in data | itemsPerPage: view.itemsPerPage" 
			total-items="view.filters.resultsCount"
			ng-class="{selected: view.currentItem == result}" 
			class="{{ result.classes }}" >
And here's my pagination controls code:
<dir-pagination-controls on-page-change="getData('',newPageNumber)" ></dir-pagination-controls>
Any ideas?
Thanks.

--Will

**Comment by michaelbromley** [comment]
Hi,

First thing to check is that you have the latest version of the dirPagination.js file, since the way of declaring ids changed recently in a way that would break on earlier versions.

Assuming you have the latest version and it still doesn't work, try posting your code again - something seems to have gone wrong above.

**Comment by mckinleymedia** [comment]
Excellent!  Thanks.  I think that did the trick - I don't have multiple instances yet, but it works with one for sure.  
FYI - when I upgraded, I needed to update the template url on line 399.
Cheers.

**Comment by michaelbromley** [comment]
Good stuff. Re the template URL, you might want to look at dirrerent ways to specify the template: https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#specifying-the-template

**Comment by mckinleymedia** [comment]
Oh, right.  Thanks.  Duh.  I saw that earlier, but forgot.


--Will

---
                             Will McKinley
                        McKinley Media Inc
               Adding vision to corporate design
www.mckinleymedia.com <http://www.mckinleymedia.com/>     will@mckinleymedia.com <mailto:will@mckinleymedia.com>     (415) 924-1975
---
