### ISSUE TITLE
ngRepeat variables

### ISSUE THREAD

**Issue by williamsousa** [michaelbromley/angularUtils#115]
Hi everybody.

I've a issue about ngRepeat variables (https://docs.angularjs.org/api/ng/directive/ngRepeat).

I've tried to use <code>$index</code> but doesn't work.

There's another way to use this?

Thanks, hugs!

**Comment by michaelbromley** [comment]
Hi,

This issue is too vague - it would be helpful if you could state:

* exactly what you are trying to achieve
* what you have tried so far (with code)
* what the error or unwanted result was

If it is not specific to this angularUtils repo (ie it is just a general question about how touse AngularJS), then a more appropriate place to get help is [StackOverflow](http://www.stackoverflow.com)

**Comment by williamsousa** [comment]
Hi Michael,

I'm sorry, maybe I did not express myself in the best way.

I want to know if dir-paginate is compatible with ngRepeat variables like <code>$index, $first, $last</code>

**Comment by michaelbromley** [comment]
Hi,

Okay, I see what you mean. The answer is **yes**, dir-paginate *is* compatible with `$index, $first, $middle, $last` etc. but with one caveat:

`$index` will only tell you the index on the *current* page. So if you have 10 items per page, `$index` will always be between 0 and 9, no matter which page you are on. 

There are a couple of solutions to this. One is to use the following type of expression to get the corrected index value:

```HTML
<li dir-paginate="meal in meals | filter:q | itemsPerPage: pageSize" current-page="currentPage">
    <strong>{{ meal }}</strong>
        <ul>
            <li>$index:  {{ $index }}</li>
            <li>corrected index: {{ ($index + 1) + (currentPage - 1) * pageSize}}</li>
        </ul>
</li>
```

Here is a [plunker demo of this](http://plnkr.co/edit/4rNlz7hx36noSmLDWVx7?p=preview), as well as the use of some other ngRepeat variables.

Another way to do it, if you want to avoid all that logic in your template, is given here in this similar issue: https://github.com/michaelbromley/angularUtils/issues/76#issuecomment-61810215
