### ISSUE TITLE
Get current page number

### ISSUE THREAD

**Issue by krusk** [michaelbromley/angularUtils#116]
I need to get the current page number (ex. I am on page 3 of 10, get page 3) and use it as a variable in a controller. The reason I need this is that I am implementing server side sorting and if a user is on a page, such as 3, and sorts... I need to ensure that they remain on page 3 but the results change as appropriate. How do I get the current page and pass it to the controller?

**Comment by michaelbromley** [comment]
You need to use the [`current-page` attribute](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#dir-paginate) on the `dir-pagination` directive. This allows you to specify a property on your controller's $scope that will can get used to get/set the current page of pagination.

**Comment by krusk** [comment]
Thanks, I tried adding it as follows:

dir-pagination 
    
    current-page="currentPage"

Controller

    var currPage = $scope.currentPage

But it returns as NaN. Do you have an example of how to do this properly?

**Comment by krusk** [comment]
It looks like Angular is not detecting the current page. When I log $scope.currentPage, it only returns the first page value of 1. Here is the reference on StackOverflow: http://stackoverflow.com/questions/28329602/angularjs-pagination-get-current-page-and-pass-to-controller

**Comment by krusk** [comment]
Just found the issue. I have a controller overlap because a div got deleted that closed that div. Count this as coding while tired! Thanks

**Comment by michaelbromley** [comment]
Ok, glad you got it sorted.

**Comment by scape14** [comment]
Good evening, I also have doubts about how to get the value of the page I'm in, I do not quite understand how you solved this problem.
