### ISSUE TITLE
Reset current-page

### ISSUE THREAD

**Issue by ghost** [michaelbromley/angularUtils#120]
Want to reset current-page value to default (1) on ng-change event bound to a select input field.
Tried to call a function attached to the controller, which actually sets the current-page value to 1, does not appear to work.

**Comment by michaelbromley** [comment]
Hi,

please show me your controller and view code (the pertinent parts at least).

**Comment by hanssulo** [comment]
Thought the following would reset the current page, whenever the filter's value from input field gets updated.
Does not, stays on the current-page the user clicked on before.
Same behaviour in your plunker's example.
Click on any page, change the input value and the results will be displayed from page two, but I want the to be displayed from Page one as start point.

Controller:

    $scope.resetPage = function(){
        $scope.currentPage = 1;
    }


Template : 

<input type="text" data-ng-model="q" data-ng-change="resetPage()">
....
<dir pagination ..... filter:q ......>

**Comment by michaelbromley** [comment]
Are you including the attribute `current-page="currentPage"` in the `dir-pagination` directive?

**Comment by hanssulo** [comment]
Yes, when I set $scope.currentPage to whatever on startup, pagniation is correctly set. How ever, the resetPage function has no effect on $scope.currentPage later

**Comment by michaelbromley** [comment]
Okay. From your little bit of code you provided, I cannot see why it would not work. I've set up a demo that does exactly what you describe (select an option from the "filter" select input and note that the page will reset to 1) - please take a look at it and compare it to your code, and see if that helps you to debug your issue. 

In the demo, all the code is in the template - index.html - line 31 - 36.

http://plnkr.co/edit/0z8nWJEi9IU1WdMOUTZG?p=preview

**Comment by NetanelBasal** [comment]
I have the same problem too, did you manage to solve this?

**Comment by michaelbromley** [comment]
Closing since I have had no feedback from the original reporter.
