### ISSUE TITLE
dirPaginate displaying 3 items and going on next items one by one

### ISSUE THREAD

**Issue by casertap** [michaelbromley/angularUtils#124]
Hi, I'm wondering if it is possible to use dirPaginate to display 3 elements: A, B, C,
and on click on next I could have B, C ,D, etc... ?

**Comment by michaelbromley** [comment]
With an in-memory collection, there is no way I can think of to do this. However, here are a couple of suggestions that might work:

- Create your collection in a way that repeats the items, for example:

```JavaScript
$scope.myCollection = ['A', 'B', 'C', 'B', 'C', D', 'C', 'D' 'E'];
```

Then when you paginate it with `itemsPerPage: 3`, you should get the result you want. You'll need to figure out a smart way to convert the plain list A, B, C, D... into the format above.

- If you use server-side paging, you could write the server code to return the results you want, i.e. page 1 returns A, B, C; page 2 returns B, C, D; etc.
