### ISSUE TITLE
Disqus not working

### ISSUE THREAD

**Issue by jl2035** [michaelbromley/angularUtils#125]
I think I followed all the instructions in readme file. Can I get some help on this?

Where ever I put the "dir-disqus" tag it just stays like that and it's not being converted to Disqus comments.

**Comment by bletvaska** [comment]
i have similar problem. i am running angular 1.3.14. in my configuration i have:

$locationProvider.html5Mode('true');
$locationProvider.hashPrefix('!');

in the controller i initialized all of the required variables:
$scope.shortname = 'xxx';
$scope.identifier = 'yyy';
$scope.url = 'zzz';

in the html template i have:
<dir-disqus 
   disqus-shortname="{{shortname}}"
   disqus-identifier="{{identifier}}"
   disqus-url="{{url}}"
   >
</dir-disqus>

and when i check, what is in the resulted html document, there is:
<dir-disqus class="ng-isolate-scope" disqus-shortname="{shortname}" disqus-identifier="{identifier}" disqus-url="{url}">

so it looks like the scope variables are not working. but if i place them above the directive, their value is used. they are not working only inside of directive.

thanks for any advice.

**Comment by michaelbromley** [comment]
Hi guys, thanks for the report. First of all I thought it might be to do with some change with Angular 1.3.x, so as a test, I updated my own blog (which uses this directive) to 1.3.14, but the Disqus directive still works okay.

Does anything show up at all? Does it show the "comments powered by Disqus" text? That is the default template text  that should display even if the Disqus script itself does not load. If that is not showing up, it suggests that the directive is not properly registered (e.g. if you didn't include it as a dependency of your app).

If it does show, then the directive *is* being invoked but something else is wrong. In that case, are you able to set a break point in the directive code in the browser's dev tools (e.g. on [line 44](https://github.com/michaelbromley/angularUtils/blob/master/src/directives/disqus/dirDisqus.js#L44)) and inspect the content of the `scope` object? Does it contain the parameters you passed to it?

**Comment by bletvaska** [comment]
hello michael

thanks for reply.

in my case it looks, that disqus is loaded, but the params are not passed correctly. it is some angular problem from my point of view (and maybe it's really some easy stuff, but i am just angular beginner). 

my project is at: http://it4kt.cnl.sk/c/pvjc/#!/2015%252Flabs.02 and you can see the disquss at the bottom. 

yesterday i was reading and looking around, and it seems, that params passing to element attributes are not working at all in my case and ng-attr was also not helpful.

i try to debug the problem as you suggest.

**Comment by jl2035** [comment]
"Does anything show up at all?"

Not here. So how would I "properly register" this directive? Aren't these the steps described in the readme file?

**Comment by bletvaska** [comment]
finaly - in my case it looks, the problem is somewhere completely else. i am generating web pages with xslt transformation, and after transformation i am missing one of the curly braces :-D ok - so i hope this is the case.

thanks anyway

**Comment by bletvaska** [comment]
so finaly - as i mentioned - problem was not in the directive - it works well, but in the xslt transformation. i solved the problem and now it finally works. thanks for the directive - it is crucial part of our site ;)

**Comment by michaelbromley** [comment]
@jl2035 Yeah, it is described under [installation](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/disqus#installation), but just to make sure:

1. Is the dirDisqus.js file being included on your page? This would be done either by adding a `<script>` tag to your page pointing to the location of the file, or if you use a build system, making sure it is included in the files that get built.
2. Did you add the reference to the module? ie:

```JavaScript
angular.module('myApp', ['angularUtils.directives.dirDisqus']);
```

Those are the basic requirements to using the directive. The fact that nothing is showing up for you suggests that one or both of these might not be in place. Also, are there any error messages in the console?

**Comment by jl2035** [comment]
1. yes, i included it with a html "script" tag, right after angularjs-all.min.js file .. and I can view the file with firebug. it's there
2. i did

Thanks for helping me, man. I am really in the dark here  :(

**Comment by michaelbromley** [comment]
Okay. So, if the script is there, and the app has reference to the module, then we can assume that the directive is being made available to the app. Angular will be looking for an element named `dir-disqus` and if it finds it, it will compile the directive.

Could you post your template code (or the part that uses this module)? Also can you confirm that there are no errors in the console?

**Comment by jl2035** [comment]
In console I don't see any errors. I did earlier ("angular" not defined, or something), but after moving the javascript file after the angular one the error was gone.

In the template I added this code:

<dir-disqus disqus-shortname="mytestsitedisqus"
         disqus-identifier="{{ identifier }}"
         disqus-url="{{ theurl }}">
</dir-disqus>

html output of that looks something like this:

<dir-disqus disqus-url="http://example.com/testpost" disqus-identifier="testpost" disqus-shortname="mytestsitedisqus"></dir-disqus>

**Comment by michaelbromley** [comment]
Okay, your HTML looks fine. The output confirms that the directive is not being compiled at all, since it should contain the `<div id="disqus_thread"></div>` at least, even if the call to the Disqus API fails.

There is a deeper issue here which I cannot figure out without seeing more code. Can you post the JS code where you define your angular app and dependencies?

**Comment by jl2035** [comment]
In my app.js file

```
'use strict';

var defaultLanguage = localStorage.getItem('myapp-language') || 'en';

angular.module('myapp',[
  'ngAnimate',
  'ngResource',
  'ngRoute',
  'ngProgress',
  'ui.bootstrap',
  'ui.route',
  'angularMoment',
  'myapp.games',
  'myapp.entries',
  'angularUtils.directives.dirDisqus'
]);

angular.module('myapp.games', []);
angular.module('myapp.entries', ['angularUtils.directives.dirDisqus']);
```

**Comment by michaelbromley** [comment]
Okay, I can't see anything obvious there. I notice that you include it twice though - once as a dependency for `myapp.entries` and then once in your main app. As I understand it, the module will only be loaded once anyway (from the `myapp.entries` declaration, since that module will be bootstrapped before the main `myapp` module). 

Long shot - is there any difference if you remove one of the references to dirDisqus?

**Comment by jl2035** [comment]
yeah I was also assuming that. no difference if I remove one declaration..

**Comment by michaelbromley** [comment]
In that case I am a bit stumped. In your position I would now attempt to use the directive in the most simple environment possible - a fresh Angular app with nothing but this directive on a page, and see if it works. Then work my way through to isolate what part of your app might be causing the problem. 

Sorry that I can't offer more specific advice than that.

**Comment by jl2035** [comment]
Will definitely try that. I'll let you know.

**Comment by jl2035** [comment]
Sorry, but I didn't have time to try. Disqus works with any other setup, so I said goodbye to angular. I don't think I will play with this more.. closed

**Comment by michaelbromley** [comment]
Fair enough.
