### ISSUE TITLE
How to have two dir-pagination-controls for one dir-paginate: on top and bottom?

### ISSUE THREAD

**Issue by Bighamster** [michaelbromley/angularUtils#126]
If I have top and bottom dir-pagination-controls then pageChanged is activated twice. How to fix it?

... and how to get the updated current page within Controller?

**Comment by michaelbromley** [comment]
Hi, 

1. Just put the `on-page-change` attribute on one of the controls, not both. This should cause the pageChanged callback to fire only once, but it will still fire even if you click the set of controls that do not have that attribute.

2. Two ways to get this: First, if you are using an `on-page-change` callback, the function you specify will be provided with an argument named `newPageNumber` which contains the updated current page. Alternatively, you can specify the `current-page` attribute on the `dir-pagination` directive and pass it a scope value that will always get updated to the current page whenever the page changes. See the [docs on the API for more detail](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#directives-api)

**Comment by Bighamster** [comment]
Hi)
1. It works! Removing on-page-change attribute from the second control definitely helped!
2. Got it! Thanks a lot!
