### ISSUE TITLE
Next and Previous links

### ISSUE THREAD

**Issue by ashto5** [michaelbromley/angularUtils#132]
Michael,

Thanks for the control works like a dream.
I want to expand on it but I am new to Angular.
I want to have a next link, a current title and previous link, which reflects the selected row in the table / list paginated data.

e.g. 
1a      2b    3c    <-- next / prev control

1a        <-- previous
<2b>   <-- selected row
3c        <-- next
4d
5e
6f

<<  <  1 2 3 >  >>         <-- dir-pagination-controls

I would like it to step onto the next page when relevant.
I have done this but I have had to use jQuery which is not the Angular way, and the code is not elegant.

**Comment by michaelbromley** [comment]
Hi,

I don't quite understand what it is you are trying to achieve. What do the next/prev links do? Move the selected row forwards/backwards?

Maybe if you show me what you already have, I'd get a better idea (don't worry about elegance or lack of it - no judging here ;))

**Comment by ashto5** [comment]
![next and prev](https://cloud.githubusercontent.com/assets/11505538/6685616/6bd71ce6-cc93-11e4-9afc-e0f7f89a105d.png)

A picture is worth a thousand words.

**Comment by ashto5** [comment]
What I have been trying to achieve is the same technique you used where the Angular code file contains all the controls which I can then place anywhere on the screen.

**Comment by ashto5** [comment]
The tab grid / chart area is where the detail of the selection is shown.

**Comment by michaelbromley** [comment]
Ah ha. The picture explains it perfectly.

So, the Angular way would be to do something like keeping track of the index of the selected item of your list, and then using that to bind all the controls together.

I threw together a working demo doing this, the main parts are:

```HTML
<!-- the detail area with the next/prev controls -->
<div class="detail-area">
    {{ getSelectedName() }}

    <button ng-click="selectPrevious()" class="btn btn-xs">
        < {{ getSelectedName(-1) }} 
    </button>
       
    <button ng-click="selectNext()" class="btn btn-xs">
        {{ getSelectedName(+1) }} >
    </button>
</div>

<!-- the paginated table -->
<table class="table">
    <tr>
        <th>Desc</th>
        <th>Date</th>
    </tr>
    <tr dir-paginate="row in items | filter:q | itemsPerPage: pageSize" 
         current-page="currentPage" 
         ng-class="{ active : $index === selectedIndex }">
        <td>{{ row.desc }}</td>
        <td>{{ row.date }}</td>
    </tr>
</table>
```

```JavaScript
// in your controller
$scope.currentPage = 1;
$scope.pageSize = 10;
$scope.items = items; // this is your collection from wherever you get it.

$scope.selectedIndex = 0;

$scope.getSelectedName = function(shift) {
    shift = shift || 0;
    var realIndex = ($scope.currentPage - 1) * $scope.pageSize + $scope.selectedIndex + shift;
    return $scope.items [realIndex] ? $scope.items [realIndex].desc+ ' - ' + $scope.items [realIndex].date: '';
};

$scope.selectPrevious = function() {
    if ($scope.selectedIndex === 0) {
        if (1 < $scope.currentPage) {
            $scope.currentPage--;
            $scope.selectedIndex = $scope.pageSize - 1;
        }
    } else {
        $scope.selectedIndex--;
    }
};

$scope.selectNext = function() {
    if ($scope.selectedIndex + 1 === $scope.pageSize) {
        $scope.currentPage++;
        $scope.selectedIndex = 0;
    } else {
        $scope.selectedIndex++;
    }
};
```

Here's a working demo (based on tasty meals, but essentially the same): http://plnkr.co/edit/uChQNw8vmznoL4vmNCO4?p=preview

**Comment by ashto5** [comment]
But I believe I understand what you are doing.

Thank you for the prompt replies and attention very much appreciated.
