### ISSUE TITLE
dirPaginate: Pagination controls at the top and the bottom without a repeat

### ISSUE THREAD

**Issue by pasque** [michaelbromley/angularUtils#133]
I'm working with the pagination in a newsfeed type application. Because I am listing 5 news stories at a time, you can't see the bottom pagination controls when you're at the top of the page, and would therefore like to place a duplicate copy at the top. I've looked around, and while others have mentioned they are doing so, I don't see code examples of how to do so. My problem is, if I place the pagination controls directly below the ```dir-paginate``` call, then I get a repeat of the controls at the top of every news story. It works great when I remove the top page controls and just leave the one at the bottom. Thoughts on getting just one on the top, and one on the bottom?

Code with Controls at top and bottom (top controls repeat at each story)
```
<div data-ng-app="TileApp" id="top">
    <div data-ng-controller="newsCtrl">
    Search News
    <br />
    <input type="text" class="input-long search-query" data-ng-model="search.$">
        <div class="wptileblock">
    	<div dir-paginate="feed in news | filter:search | orderBy:'-date' | itemsPerPage: 5">
         <div class="text-center"><dir-pagination-controls template-url="/law/js/angular/dirPagination.tpl.html" on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls></div>
                <p id="clearleft">
	

			<h2 id="{{feed.post_meta.anchor}}">
				<div data-ng-bind-html="feed.title">{{feed.title}}</div>
				</h2>
				{{feed.date | date : longdate}}
				<br />
				<div id="wpthumbnail">
				<img src="{{feed.featured_image.source}}" width="200">
				</div>
                <div data-ng-bind-html="feed.content">{{feed.content}}</div></p>
				<br />
                <br />
                <div class="text-center data-ng-bind-html="Back to Top"><a href="#top">Back to Top</a></div>
			<h3 data-ng-show="(news | filter:search).length == 0">No Results</h3>
    		    
			</div>   
			</div>
            <p>
            <div class="text-center"><dir-pagination-controls template-url="/law/js/angular/dirPagination.tpl.html" on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls></div>
			</p>
    		    
			</div>
			</div>
```
Note repeat of page controls at each new "repeat"
![untitled-1](https://cloud.githubusercontent.com/assets/11381975/6700718/a734e19e-ccd7-11e4-9e13-4ca14bd9385d.jpg)

**Comment by michaelbromley** [comment]
Hi,

The reason is that if you put the controls *inside* the repeated element, it of course gets repeated for every item along with the rest of the contents of that div.

Just move the top controls out of the `dir-paginate` div and that should fix it.

**Comment by pasque** [comment]
Well of course that would work! I didn't even try that, I just assumed if you put it out of the controls it would no longer function, but I forgot that it gets called as a dependency of my entire app. Thanks for setting me straight, and I absolutely love your pagination component.

**Comment by hackel** [comment]
I have tried the suggested solution, but if I place dir-pagination-controls before dir-paginate, I get the error: "pagination directive: the pagination controls cannot be used without the corresponding pagination directive."  Any ideas?
