### ISSUE TITLE
dirPagination: multiple instances in a page

### ISSUE THREAD

**Issue by diegorusso** [michaelbromley/angularUtils#136]
Hello,
I've been experiencing issues with dir-paginate and multiple instances in the same page. Basically I have the same example of https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#multiple-instances-with-ngrepeat with the following changes:
```html
<div class='row' data-ng-repeat='section in results'>
    ...
    code
    ...
    <ul class='list-group'> 
        <li class='list-group-item' dir-paginate="test in section.tests | itemsPerPage: 10" pagination-id="section._id.fingerprint_id">
    ...
    code with tables and inner ng-repeat
    ...
        </li>                                                                 
    </ul>
    <dir-pagination-controls pagination-id="section._id.fingerprint_id"></dir-pagination-controls>
</div>
```

The error I have is: https://docs.angularjs.org/error/$parse/syntax?p0=c7f197caa6208e290515a5120005c199eeabaa__currentPage&p1=is%20an%20unexpected%20token&p2=3&p3=60c7f197caa6208e290515a5120005c199eeabaa__currentPage&p4=c7f197caa6208e290515a5120005c199eeabaa__currentPage%20at%20Error%20(native)

It is failing in this function when it parses defaultCurrentPage.
```javascript
function makeCurrentPageGetterFn(scope, attrs, paginationId) {
            var currentPageGetter;
            if (attrs.currentPage) {
                currentPageGetter = $parse(attrs.currentPage);
            } else {
                // if the current-page attribute was not set, we'll make our own
                var defaultCurrentPage = paginationId + '__currentPage';
                scope[defaultCurrentPage] = 1;
                currentPageGetter = $parse(defaultCurrentPage); <-------IT'S FAILING HERE
            }
            return currentPageGetter;
        }
```

The fingerprint is somehow *cut* at the beginning. Why?
That's odd because just the last pagination works. In other examples I have the first and the last pagination that work correctly.
What am I doing wrong?

**Comment by diegorusso** [comment]
All right, after some investigation, it seems the $parse function is bothered by strings that start with a number.
```javascript
parse('a123a')
function (s,l,a,i){var v5,v6=l&&('a123a' in l);if(!(v6)){if(s){v5=s.a123a;}}else{v5=l.a123a;}return v5;}
parse('123a')
angular.js:38 Uncaught Error: [$parse:syntax] http://errors.angularjs.org/1.4.0-beta.6/$parse/syntax?p0=a&p1=is%20an%20unexpected%20token&p2=4&p3=123a&p4=a
```
Maybe some stronger check would be better in that function.

**Comment by diegorusso** [comment]
I turns out I have found a solution (workaround). I generate the pagination id in the following way

```pagination-id = "'_' + section._id.fingerprint_id"```

So I force the id to start with a character rather than a number.
Please consider revisiting this part.

Cheers

**Comment by michaelbromley** [comment]
Hi, thanks for the detailed reports.

I just tested this out with `pagination-id="myId"` and `$scope.myId = "123a"`, and it worked okay. Can you confirm that you are using the latest version of the code (v0.6.0 if using Bower)?

If you still get the error on the latest version, are you able to recreate it in a plunk (you can form this one: http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview)?

Cheers.

**Comment by diegorusso** [comment]
Here the plunk: http://plnkr.co/edit/pS37d24Tn4NgvPuNBfc3?p=preview
Ok, what I'm trying to do is slightly different: my id's name is the value of some variable generated in an external ng-repeat while you're setting the value of a fixed variable in a scope.
Obviously in js we cannot have variable names which start with a number, hence the parse error.

**Comment by michaelbromley** [comment]
Ah I see. Yeah I ran into a similar issue recently with ids containing a hyphen. Comes down to the same problem - identifiers in Angular expressions must be valid JavaScript identifiers too. This isn't an issue specific to this module, so I'll close this now.

**Comment by diegorusso** [comment]
Yep, I read about that. I would suggest to implement some soft of sanitation of the variable name (start with a character, replace hyphen with underscore, etc) so users can use it without worrying about it as the pagination-id can be generated starting from user data which might contain numbers, hyphens and other not valid characters.
Anyway, great module! Congrats and thanks!
