### ISSUE TITLE
Pagination doesn't work with angular-rails-templates (not a bug - only wish)

### ISSUE THREAD

**Issue by Bighamster** [michaelbromley/angularUtils#141]
1. I want to use html5Mode: $locationProvider.html5Mode(true);
2. On server side (rails) I write a stub: get '*path' => 'application#index'
3. I set pagination path:
app.config(function(paginationTemplateProvider) {
    paginationTemplateProvider.setPath('dirPagination.tpl.html');
});
4. If I put dirPagination.tpl.html into app/templates then I expect browser not requesting the server for http://localhost:3000/dirPagination.tpl.html .... but browser does(

Q: How to prevent dirPagination.tpl.html request?

**Comment by michaelbromley** [comment]
Hi, I'm sorry but I'm not sure I understand the problem. I've never used Rails so much of that description is lost on me.

Why do you not want the template to be requested?

**Comment by pcnate** [comment]
I wonder if he means the file should be requested from http://localhost:3000/app/templates/dirPagination.tpl.html?

**Comment by Bighamster** [comment]
Sorry, I miss explained! I was trying to say that would be nice if the dirPagination.tpl.html could be taken from $templateCache. The gem angular-rails-templates provides shuch a nice service if we place html-files into app/templates folder. It removes the need for AJAX calls to retrieve the templates.

**Comment by michaelbromley** [comment]
Ah I see. Well, there is no special reason why the template cannot be served from the template cache. I do it that way myself on a couple of my own apps which use this module.

I guess it is a problem related to how the angular-rails-templates gem (or Rails itself) works. Does it not work if you set `paginationTemplateProvider.setPath('templates/dirPagination.tpl.html');`, or maybe `paginationTemplateProvider.setPath('app/templates/dirPagination.tpl.html');`?

**Comment by Bighamster** [comment]
You are right! The template dirPagination.tpl.html can be served from the template cache IF the name of template **doesn't contain .tpl** When I replaced dirPagination.tpl.html for dirPagination.html everything worked perfectly! 

I am really surprised that the template doesn't hit the cache because of suffix - .tpl ....
