### ISSUE TITLE
Scroll back to top after paging

### ISSUE THREAD

**Issue by krusk** [michaelbromley/angularUtils#142]
Is there a method with this directive to have it scroll back to the top after each pagination. Currently, if I go to page 2 with 10 items per page, the user is at the bottom of the page. I have tried achorscroll, but the issue is that if I use a location.hash it is messing with my routing.

**Comment by michaelbromley** [comment]
Have you tried setting the [`$anchorScroll.yOffset`](https://docs.angularjs.org/api/ng/service/$anchorScroll#yOffset) property? It says there you can pass it a number (ie `0`) and it should scroll there.

Or, just plain old DOM API should work, i.e. `window.scrollTo(0, 0)`.

**Comment by krusk** [comment]
Thanks Michael, I have been testing the AnchorScroll but it keeps requiring two clicks before executing (first for a route it believes it is hitting, and the second for the actual scroll). I will continue to investigate how to work around this.

**Comment by krusk** [comment]
I solved the double clicking (anchor and routing were interfering): http://stackoverflow.com/questions/29637614/anchorscroll-only-works-after-second-click/29660203#29660203

However, how would I perform a scroll when using client side paging? In server side paging I have a function I can put the scroll into, but not for client side when using this directive.

**Comment by michaelbromley** [comment]
You can still use the `on-page-change` attribute with client-side paging to specify a controller method to call when changing pages, so you could still put the scroll code there.

**Comment by krusk** [comment]
Works like a charm. Thank you!

**Comment by nlindroos** [comment]
A bit late to the party, I know. If anyone stumbling over this page is wondering how this is done with Ionic, the following works

    $ionicScrollDelegate.scrollTop();

Cheers
