### ISSUE TITLE
dirPagination on-page-change

### ISSUE THREAD

**Issue by jcsmesquita** [michaelbromley/angularUtils#148]
Lets say I have list of 10 items and itemsPerPage is set to 5.
My controller is setup to something similar to the async example in the [pagination docs] (https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#working-with-asynchronous-data). So whenever the page is changed with dir-pagination-controls I have a function that makes an API call with limit and skip.

The problem is when I am in the second page and perform a search which results in 1 item. What happens is dirPaginate sees the list items have updated and triggers on-page-change (because of course now we only have 1 page and it must go to it). 

But shouldn't the directive bypass the on-page-change when the object changes?
At the moment I end up with an unfiltered list and losing my search results, I can't come up with a workaround for this at the controller level. Any suggestions?

**Comment by michaelbromley** [comment]
Hi,

I *think* I understand what you are describing. With server-side paging, the use case I mainly had in mind was that search/filtering would be done server side, too. So when the use types into the search box, a brand new request is sent off and the server returns just the filtered result set, in which case the current behaviour is correct.

In your case, as I understand it you are getting 10 results, and then want to filter those 10 *only*, without making a new server call.

A possible work around:

In your `on-page-change` function, do a check to see if there is any input in the search box, and only make the request to the server if the search box is empty. Here's the general idea:

```JavaScript
$scope.onPageChange = function() {
  if (!$scope.searchInput) {
    // do server call for new items
  }
};
```

Does that help at all?

**Comment by jcsmesquita** [comment]
Hi Michael thanks a lot for the quick response.

My case is those 10 items are the total in the database, but the actual results i have are only ever maximum 5 at a time because I also limit and skip the API call accordingly.

I tried the solution you suggested, the only issue was if the user wrote somethinf

**Comment by jcsmesquita** [comment]
ops sorry about the close/re-open! that's what happens when I try to github on my phone with no coffee :)

**Comment by michaelbromley** [comment]
No worries. So.... should it be closed now?

**Comment by jcsmesquita** [comment]
Actually this solution doesn't work because if you do a search and end up with a result that spans more than 1 page, the pagination will not work. Is there a way I could change your code to bypass on-page-change when the object changes?

**Comment by jcsmesquita** [comment]
I ended up using ui bootstrap [pagination](http://angular-ui.github.io/bootstrap#pagination) instead
