### ISSUE TITLE
dirPagination: Change in total items ignored

### ISSUE THREAD

**Issue by AudriusButkevicius** [michaelbromley/angularUtils#150]
I have a list of files I am downloading, which means that every now and then, the list shrinks.
As a result, I update the list of items and the variable which is bound to `total-items`, but it seems that the page selection widget never shrinks, allowing me to go to pages which don't have any items anymore.

**Comment by AudriusButkevicius** [comment]
Nevermind, it's just me being an idiot.

**Comment by michaelbromley** [comment]
No worries. It happens to the best of us ;)

**Comment by JoomSavvy** [comment]
Please share how you were being an idiot, because apparently I'm being the same kind of idiot.

**Comment by AudriusButkevicius** [comment]
So I can't remember what the issue was, but the implementation is available here.

https://github.com/syncthing/syncthing/blob/master/gui/syncthing/transfer/neededFilesModalView.html
https://github.com/syncthing/syncthing/blob/master/gui/syncthing/core/syncthingController.js

**Comment by JoomSavvy** [comment]
Thanks for the response. I just hadn't bound the array properly.
