### ISSUE TITLE
pagination-id not get value from scope (Multiples Pagination on same controller to diferent Grids)

### ISSUE THREAD

**Issue by joaolori** [michaelbromley/angularUtils#151]
Hello Guys,
I guess i found a bug here on dir-pagination.

on dirPagination.js

     // Now that we have access to the `scope` we can interpolate any expression given in the paginationId attribute and
                // potentially register a new ID if it evaluates to a different value than the rawId.
                var paginationId = $parse(attrs.paginationId)(scope) || attrs.paginationId || DEFAULT_ID;

i put on markup this (datagrid.tpl.html) :
pagination-id="paginationIdSuper"

that was name of property will assign the pagination id, if i put this :

pagination-id="{{paginationIdSuper}}"

Get error... if i leave the 1st option, the value passed to dirPagination.js is string, so, when i got multiple grids with pagination when change one of them the pagination its changed to whole grids on controller.

Can u help me out?

**Comment by michaelbromley** [comment]
Hi,

Can you show me the controller code where the `paginationIdSuper` variable is being assigned, and your view code there you use the directives?
