### ISSUE TITLE
OrderBy only working per page basis

### ISSUE THREAD

**Issue by fraincs** [michaelbromley/angularUtils#154]
when I use the orderBy filter on a repeat, it works but on a per page basis

**Comment by michaelbromley** [comment]
Just a guess here, but make sure the itemsPerPage filter comes *after* the orderBy.

**Comment by jason-amador** [comment]
I just run the filter on the array itself in the controller instead of in the template.

**Comment by michaelbromley** [comment]
Closing as the originator did not respond.
