### ISSUE TITLE
dirPagination: total-items forcing asynchronous mode

### ISSUE THREAD

**Issue by jaythomas** [michaelbromley/angularUtils#157]
Whenever I'm working with local data and I specify the `total-items=` the pagination buttons don't work. I did a console.log and the current page properly changes, but it still shows page 1. No matter what I set `total-items` to, it does this. If I remove `total-items` attribute, however, the directive works as expected. The issue is I need the `total-items` attribute there, because my table module is used for api calls with and without server-side pagination.

Am I missing something? What can I do to let the API call decide whether or not there is server-side pagination?

sample template:
```html
<tr dir-paginate-start="row in model.rows | itemsPerPage: options.pageSize" current-page="options.currentPage" pagination-id="tableId" total-items="options.totalItems">
```

sample scope:
```javascript
$scope.tableId = 'd21abf76-e373-40fe-8d94-2647577325aa'
$scope.model = { rows: [...] }
$scope.options = {
  pageSize: 10,
  totalItems: $scope.model.rows.length
}
```

Thanks.

**Comment by michaelbromley** [comment]
Hi,

You're not missing anything - you just have a use-case which I didn't foresee (i.e. using local & server-side on the same collection).

The actual effect of using the `total-items` attribute can be see [here](https://github.com/michaelbromley/angularUtils/blob/80ef1819488a09c6c2b0cf0252237d4d18eedbf6/src/directives/pagination/dirPagination.js#L89-L90) and again [here](https://github.com/michaelbromley/angularUtils/blob/80ef1819488a09c6c2b0cf0252237d4d18eedbf6/src/directives/pagination/dirPagination.js#L426-L430)

To allow your use case to work with the existing code would probably take a fair bit of modification to the module and probably additions to the API to allow you to specify such a "mixed" mode.

I don't currently have time to do a lot of work on this - feel free to have a go if you like. Otherwise, I would suggest (if this is possible) to see if you can re-think things so that you do not have this particular requirement, and either use *only* server-side paging or client-side for that particular collection.

**Comment by jaythomas** [comment]
At first glance into the source code it looks like it should be able to set the total-items to `undefined`, but upon testing this is not the case.

To clarify better my use case, the controllers are making api calls then returning the paginated data. I can probably get away with telling the controllers to *always* pull paginated data, but sometimes the controllers themselves locally generate data for my table module and this is never segmented into pages.

Considering the size of the application, it would be more feasible to modify the directive than every controller that does so. I'll take a look at this later and see how much of an undertaking it would be.

**Comment by jaythomas** [comment]
This is a big mess and it probably fails the karma tests, but seems to do the trick for me. http://paste.debian.net/193437/

```javascript
if (typeof attrs.totalItems !== 'undefined') {
    scope.$watch(function() {
        return $parse(attrs.totalItems)(scope);
    }, function (result) {
        console.log(paginationService.getItemsPerPage(paginationId), result)
        if (0 < result && paginationService.getItemsPerPage(paginationId) < result) {
            paginationService.setCollectionLength(paginationId, result);
            paginationService.setAsyncModeTrue(paginationId);
        } else {
            scope.$watchCollection(function() {
                return collectionGetter(scope);
            }, function(collection) {
                if (collection) {
                    paginationService.setCollectionLength(paginationId, collection.length);
                }
            });
        }
    });
} else {
    scope.$watchCollection(function() {
        return collectionGetter(scope);
    }, function(collection) {
        if (collection) {
            paginationService.setCollectionLength(paginationId, collection.length);
        }
    });
}
```

(Excuse the lack of semicolons. I have religious convictions.)

**Comment by jaythomas** [comment]
I give up on this. Anyone else feeling like taking a crack at it, by all means.

**Comment by michaelbromley** [comment]
Ok. Thanks for sharing your attempt so far. Might come in useful for anyone else brave enough to attempt something similar ;)

**Comment by benoror** [comment]
I just happen to have the same use-case (using local & server-side on the same collection). 

I tried using [**ngAttr**](https://docs.angularjs.org/guide/directive#-ngattr-attribute-bindings) with: `ng-attr-total-items="vm.options.totalItems"` but that resulted in `total-items` being appended without an actual value.

**Comment by benoror** [comment]
I fix it with an dirty, hacky, ugly workaround, :cry:  I doesn't like it but it works for the time being.

I simply surround two `dir-paginate` directives inside an **ng-switch**, one with `total-items` attribute, (for server side pagination), and another without it (for client-side pagination):

```
<div ng-switch on="vm.asyncPaginationFlag">
  <!-- Server side pagination -->
  <div ng-switch-when="true">
    <div dir-paginate="..." total-items="vm.options.totalItems">
      ...
    </div>
  </div>
  <!-- Client side pagination -->
  <div ng-switch-default>
    <div dir-paginate="...">
      ...
    </div>
  </div>
</div>
```

Anyway, my proposal is to **re-open** :green_heart: this issue in case myself, or someone else, allocate some time in the future to improve the robustness of this **awesome directive** :smile: 

Cheers!

**Comment by jaythomas** [comment]
Thanks for the reply, @benoror. My workaround is similar. I'm using two different template files for storing the `dir-paginate` div and then conditionally loading the appropriate template depending if I am working with a local or server-side collection.

**Comment by benoror** [comment]
Great!, just curious, are you using **ng-include** or a similar approach?

**Comment by jaythomas** [comment]
I'm touching the element from within the directive's link:
```javascript
if (partial === true) {
  element.html($templateCache.get('jaytable/jaytable-partials.html'))
} else {
  element.html($templateCache.get('jaytable/jaytable-full.html'))
}
```

**Comment by seadaily** [comment]
I'm running into a similar situation and I'm hoping I might be able to get a little help on it.

For the two hacks mentioned here, do they involve a single table that for some pages will be using client-side data and then when it runs out that it goes and grabs some more data from the server?

So far I've tried using the ng-switch suggestion above and even ng-if, but neither have worked correctly. When hitting a page that would use client-side pagination, nothing happens and when I hit a page that would require going back to the server, it reloads and displays as if the total-items attribute isn't present.

Any help or suggestions would be greatly appreciated.

**Comment by ram535ii** [comment]
+1
 I am in the same boat as @seadaily. 

I have a local data store that has a bunch of data that should paginate. Only when those objects run out I want to go into async mode to fetch more (and then proceed to paginate locally until the same thing happens again). To do that I need to always have `total-items` present to show the correct number of pagination tabs. As such, unless I've missed something, none of the proposed hacks work. 

Spent some time tring to cater for the hybrid mode, but with no success. For now I'm sticking to doing it all in Async mode, but would love the hybrid mode.
