### ISSUE TITLE
dirPagination: how to set a custom inline template

### ISSUE THREAD

**Issue by simonewebdesign** [michaelbromley/angularUtils#159]
I am currently struggling on how to set a custom template for the dirPagination. I stumbled across https://github.com/michaelbromley/angularUtils/issues/143 while googling (I'm using Rails too) and I've already tried this code:

``` javascript
angular.module("mymodule").run(["$templateCache", function($templateCache) {
  $templateCache.put(
    "directives/pagination/dirPagination.tpl.html", 
    '<div class="pagination">this is the new template</div>')
}]);
```

Unfortunately this is not working for me, the template remains the default one.

So what's the way of doing this? I read the documentation but it's only specified how to set the path. I couldn't find anything about the inline template. Any thoughts?

**Comment by michaelbromley** [comment]
Hi,

In your above example, did you also specify this custom template in your config block?  i.e.:

```JavaScript
angular.module("mymodule").config(function(paginationTemplateProvider) {
    paginationTemplateProvider.setPath('directives/pagination/dirPagination.tpl.html');
});
```

That would tell the pagination module to use the template you had put into the templateCache yourself.

Here is a working example: http://plnkr.co/edit/L7ROfebFE7HPWNCOHkwc?p=preview

**Comment by simonewebdesign** [comment]
Yeah that works :)

I didn't realize I had to set the path anyway, so I skipped the first step, but that did the trick.

Thanks!
