### ISSUE TITLE
IE 11 no data-binding on page numbers

### ISSUE THREAD

**Issue by koraysels** [michaelbromley/angularUtils#160]
you can check here : http://www.atrecruitment.be/kandidaat/zoek-een-job/#

this is what I get

![image](https://cloud.githubusercontent.com/assets/2418853/7660487/bf397150-fb4a-11e4-9ab2-7b5b113f8534.png)

**Comment by koraysels** [comment]
well i solved it using ng-bind but still it's a strange issue

**Comment by michaelbromley** [comment]
Hi,

I just tested the demo plunker in IE11 and it works fine for me (using regular {{ }} interpolation). Was there any error in the console when you came across the error above?
