### ISSUE TITLE
pagination-id may not contain certain characters

### ISSUE THREAD

**Issue by raztus** [michaelbromley/angularUtils#161]
The README.md currently states, "The pagination-ids can be anything you like". However, because of the `$parse` at https://github.com/michaelbromley/angularUtils/blob/master/src/directives/pagination/dirPagination.js#L77 and 
https://github.com/michaelbromley/angularUtils/blob/master/src/directives/pagination/dirPagination.js#L194, this is not true. Here are two examples that cause `$parse` to fail at each of those places, respectively:

```
<dir-pagination-controls template-url="/Content/templates/dirPagination.tpl.html" pagination-id="a1f209549-11bb"></dir-pagination-controls>
<div dir-paginate="match in job.Matches | itemsPerPage: 50" pagination-id="a1f209549-11bb">
```
> Error: [$parse:syntax] Syntax Error: Token 'bb' is an unexpected token at column 13 of the expression [a1f209549-11bb] starting at [bb].

```
<dir-pagination-controls template-url="/Content/templates/dirPagination.tpl.html" pagination-id="1"></dir-pagination-controls>
<div dir-paginate="match in job.Matches | itemsPerPage: 50" pagination-id="1">
```
> Error: [$parse:syntax] Syntax Error: Token '__currentPage' is an unexpected token at column 2 of the expression [1__currentPage] starting at [__currentPage].
>     ...
>     at $parse (angular.js:12737:39)
>     at makeCurrentPageGetterFn (dirPagination.js:194:37)

This may simply be a question of updating the docs to clarify invalid expressions in `pagination-id`, or evaluating the use of `$parse`.

I'm using Angular 1.3.15 with commit 090548de38b of dirPagination.js.

**Comment by michaelbromley** [comment]
Good spot. I'd actually run into this before as it came up in another issue, but I didn't think to check the docs.

Now updated to this: https://github.com/michaelbromley/angularUtils/commit/72ee6973c49d3f4176b830e9ea4d5a3d1bc62f23

**Comment by raztus** [comment]
Thank you! And thanks for the educating blog post.
