### ISSUE TITLE
Pagination with filter works fine only for itemsPerPage >= 7

### ISSUE THREAD

**Issue by pawlowskim** [michaelbromley/angularUtils#162]
Hello, I "started" using angular and I faced strange issue. I have collection of objects I want to filter. I display them as a table and I append filters. After filtering if itemsPerPage >= 7 data is displaying correctly, but if I have itemsPerPage < 7 some data is missing (but should be visible). This is basically what I have:

	<label>Location: <input ng-model="cityOrCountry"></label>
	 <table class="table table-striped b-t b-light">
	<thead>
	<th>Location</th>
	</thead>
	<tr dir-paginate ="x in gsc | itemsPerPage:entryLimit | filter:filterOnLocation"
            current-page="currentPage">
	<td>{{ x.location.city }}, {{ x.location.country }}</td>
	</tr>
	</table>
	<dir-pagination-controls></dir-pagination-controls>

And controller:

	$scope.cityOrCountry = '';
	$scope.minimumRecommendation = null;
	$scope.responseTime = null;

	$scope.entryLimit = 7; //max rows for data table
	$scope.currentPage = 1;

	$scope.filterOnLocation = function(obj) {
		return (obj.location.city.toLowerCase() +   obj.location.country.toLowerCase()).indexOf($scope.cityOrCountry.toLowerCase()) >= 0;
	};

"gsc" is my collection I get from rest API. When itemsPerPage < 7 it looks like filter isn't working correctly, but I debug it, and it return true for elements that should be visible. Any ideas?

**Comment by michaelbromley** [comment]
Try this: `dir-paginate ="x in gsc | filter:filterOnLocation | itemsPerPage:entryLimit"`.

The `itemsPerPage` filter should always be at the end, as it truncates the collection.

**Comment by pawlowskim** [comment]
It works, good point and tip for future too :) thx. 

[RESOLVED]
