### ISSUE TITLE
Show pagination even if there's not enough items

### ISSUE THREAD

**Issue by cezarykluczynski** [michaelbromley/angularUtils#165]
I would like to show pagination even when there's not enough items to paginate over. For example, there are 2 items, but itemsPerPage is set to 10. Is there a way to do this now? Would pull request for this kind of functionality be considered?

**Comment by michaelbromley** [comment]
Either:

* use a custom template based on the [default](https://github.com/michaelbromley/angularUtils/blob/master/src/directives/pagination/dirPagination.tpl.html#L1) (removing the ng-if on the first line)

* yes a pull request would be welcome but only if the displaying of the pagination when not needed was made optional - i.e. the current behaviour continues to work as is (so as not to break backward compatibility), but there could, for example, be an optional attribute (e.g. `auto-hide="false"`, default being `true`) added to the `dir-pagination-controls` API which allows the user to specify this behaviour if required.

**Comment by cezarykluczynski** [comment]
I've created pull request #166.
