### ISSUE TITLE
DirPagination error when I use grunt wiredep

### ISSUE THREAD

**Issue by alsfurlan** [michaelbromley/angularUtils#167]
Hi,
I am installing dirPagination from bower and when I am used grunt wiredep, the dirPagination's script was imported before angularjs.

Like the images
![sem titulo](https://cloud.githubusercontent.com/assets/4544070/7900686/9340886a-073c-11e5-975e-ccbc376a5bb8.png)
![error](https://cloud.githubusercontent.com/assets/4544070/7900688/994a1834-073c-11e5-89ee-cd3732081937.png)

I found a solution, just add dependencies on bower.json, but I don't know how do a pull request about this, you do that for me?
![sem titulo 2](https://cloud.githubusercontent.com/assets/4544070/7900692/be1d7fde-073c-11e5-96c1-80368b342eb9.png)

For give me about the English errors, 

Best regards

**Comment by michaelbromley** [comment]
Hi,
Thanks for the report and solution. Yes, I'll add this to the next release I push out - should be in the next few days.

**Comment by michaelbromley** [comment]
This went out with v0.8.0 of the package.

**Comment by alsfurlan** [comment]
@michaelbromley Thanks a lot :+1:
