### ISSUE TITLE
dirPagination: pagination controls directive intermittently shows "cannot be used without corresponding pagination" error

### ISSUE THREAD

**Issue by benelliott** [michaelbromley/angularUtils#169]
I have spent a few hours searching for a fix to this issue and have resorted to filing a report after no luck.

My problem is that the pagination controls directive will intermittently throw the "the pagination controls cannot be used without the corresponding pagination directive" error every so often if I repeatedly refresh my web app. If the error is thrown then the list items will repeat as usual but not pagination controls will be shown. If it is not thrown then the controls will function as expected.

This is the relevant part of my (somewhat abstracted) HTML:
```
    <div>
        <div>
            <some-custom-directive dir-paginate="item in items | itemsPerPage:pagination.perPage" total-items="pagination.total" item="item" current-page="pagination.currentPage"></some-custom-directive>
        </div>
        <div>
            <dir-pagination-controls on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls>
        </div>
    </div>
```

This is the relevant part of my controller:
```
$scope.pagination = {
	perPage: 10,
	perPageOptions: [10, 20, 50],
	currentPage: 1,
	total: 0
};

$scope.loadItems = function(){
	var response = Items.allPaged($scope.pagination.perPage, $scope.pagination.currentPage - 1); // backend starts counting from 0
	response.$promise.then(function(){
		$scope.items = response.data;
		$scope.pagination.total = response.details.total;
	});
};

$scope.pageChanged = function(newPage){
	$scope.pagination.currentPage = newPage;
	$scope.loadItems();
};

```

This is the full error message:
```
pagination directive: the pagination controls cannot be used without the corresponding pagination directive.
<dir-pagination-controls on-page-change="pageChanged(newPageNumber)" class="ng-isolate-scope">
(anonymous function) @ angular.js?v=0:11655
$get @ angular.js?v=0:8596
invokeLinkFn @ angular.js?v=0:8260
nodeLinkFn @ angular.js?v=0:7768
(anonymous function) @ angular.js?v=0:7998
processQueue @ angular.js?v=0:13248
(anonymous function) @ angular.js?v=0:13264
$get.Scope.$eval @ angular.js?v=0:14466
$get.Scope.$digest @ angular.js?v=0:14282
$get.Scope.$apply @ angular.js?v=0:14571
done @ angular.js?v=0:9698
completeRequest @ angular.js?v=0:9888
requestLoaded @ angular.js?v=0:9829
```
The stack trace along with the fact that I am running the directive in asynchronous mode suggests there is some race condition that causes the error if the list resource is/is not cached, but I can't figure out what exactly is going on here. I would say that the error is thrown about once every five hard reloads. Do you have any ideas?

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. No definite idea what is wrong, but are you pre-populating the templatecache or do the templates get loaded async on demand? If yes, does using templatecache fix it?

Could you show me the actual view code rather than a simplified version? The error suggests that the `dir-pagination-controls` directive is being linked before the `dir-paginate` has even been *compiled*, which might happen, if say the `dir-paginate` is within an `ng-if` which does not resolve to "true" fast enough or something like that.

**Comment by benelliott** [comment]
Thanks for getting back to me. I was not explicitly populating the templateCache but interestingly, doing so seems to make the error completely reproducible - that is, it happens 100% of the time if I prepopulate the templateCache with a string of the template file's contents.

I should also have mentioned that I use a custom controls template, and using the default template seems to make the error less frequent but does not prevent it completely. Just for reference, this is the full HTML of the controls template that I'm using (pagination-controls.html):

```
<ul class="pagination" ng-if="1 < pages.length">
    <li ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == 1 }" ng-click="setCurrent(1)">
        <p>&laquo;</p>
    </li>
    <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == 1 }" ng-click="setCurrent(pagination.current - 1)">
        <p>&lsaquo;</p>
    </li>
    <li ng-repeat="pageNumber in pages track by $index" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == '...' }" ng-click="setCurrent(pageNumber)">
        <p>{{ pageNumber }}</p>
    </li>
    <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == pagination.last }" ng-click="setCurrent(pagination.current + 1)">
        <p>&rsaquo;</p>
    </li>
    <li ng-if="boundaryLinks"  ng-class="{ disabled : pagination.current == pagination.last }" ng-click="setCurrent(pagination.last)">
        <p>&raquo;</p>
    </li>
</ul>
```

In my app config I do
```
paginationTemplateProvider.setPath('/static/apps/common/partials/pagination-controls.html');
```

and when I tried explicitly prepopulating the templateCache, I put this in my app.run method:
```
    $templateCache.put('/static/apps/common/partials/pagination-controls.html', '...stringified template HTML here...');

```

Unfortunately I cannot share the full code as it is a proprietary project but I have not removed any directives from the excerpt that I pasted above.

**Comment by benelliott** [comment]
I did a bit more digging today and you were spot-on about the controls directive being linked before the content directive is compiled. This happens because my `dirPaginate` directive is working on a reasonably complex directive that includes other nested custom directives, all using `templateUrl` to load their templates (if I just switch my outermost directive out with a simple div the error goes away!). 

From the Angular documentation:
 > Because template loading is asynchronous the compiler will suspend compilation of directives on that element
 > for later when the template has been resolved.  In the meantime it will continue to compile and link
 > sibling and parent elements as though this element had not contained any directives.
 
 > The compiler does not suspend the entire compilation to wait for templates to be loaded because this
 > would result in the whole app "stalling" until all templates are loaded asynchronously - even in the
 > case when only one deeply nested directive has `templateUrl`.
 
 > Template loading is asynchronous even if the template has been preloaded into the {@link $templateCache}

So I can either load my directive templates through `template` instead of `templateUrl` (which I don't really want to do) or I can figure out a way to force your directive to wait for `dir-paginate` before linking `dir-pagination-controls`. I'll look into this a bit more soon and post back if I find a solution.

**Comment by josx** [comment]
@benelliott  did you solve ii? can you show us how?

**Comment by benelliott** [comment]
Hi, yes I solved it by forking the library and replacing this error with a warning. I submitted a pull request which has now been merged so if you are seeing an error then try updating to the latest release of the library.

**Comment by gambolputty** [comment]
@benelliott How did you solve the problem?

**Comment by benelliott** [comment]
As I said above, the library should now just print a warning rather than throw an error.

**Comment by wellrootedmedia** [comment]
So you fixed an error by making it a warning? How does the initial problem?

**Comment by benelliott** [comment]
It fixes the problem by allowing your app to function normally even if the pagination directives have not all been resolved by a particular point in time (rather than throwing an error).

**Comment by ashokgavini** [comment]
what is Items in var response = Items.allPaged($scope.pagination.perPage, $scope.pagination.currentPage - 1);

**Comment by sateesh2499** [comment]
What to do to get rid of this warning message?

**Comment by benelliott** [comment]
@ashokgavini `Items` is an example of a service that uses HTTP to get paged data.

@sateesh2499 The warning is probably happening because the `ng-repeat`ed template you are using for the paged items is so complex that it is not compiled fast enough to be detected by the pagination directive. You could try to simplify the repeated template to see if that helps with the issue.

**Comment by tmAsim** [comment]
> Hi,
> 
> Thanks for the report. No definite idea what is wrong, but are you pre-populating the templatecache or do the templates get loaded async on demand? If yes, does using templatecache fix it?
> 
> Could you show me the actual view code rather than a simplified version? The error suggests that the `dir-pagination-controls` directive is being linked before the `dir-paginate` has even been _compiled_, which might happen, if say the `dir-paginate` is within an `ng-if` which does not resolve to "true" fast enough or something like that.

So how to get out of this warning? looks like due to this I am unable to see pagination control. can you please help?
