### ISSUE TITLE
Sorting anf Pagination not working together

### ISSUE THREAD

**Issue by goutamsmgit** [michaelbromley/angularUtils#170]
Hi,

I am using this directive and using 'orderBy' for sorting.
However when I tried to sort Items per page is not constant.

For example:
Lets say ItemsPerPage is 10 , when i sort; item showed per page changes from 10 to 8, its very ramdom

**Comment by michaelbromley** [comment]
Hi,

Please show me the view code where you use the filter so I can get an idea of what may be causing this.
