### ISSUE TITLE
Failed to instantiate module angularUtils.directives.dirPagination

### ISSUE THREAD

**Issue by sebasira** [michaelbromley/angularUtils#173]
```
Error: [$injector:modulerr] Failed to instantiate module angularUtils.directives.dirPagination due to:
Error: [$injector:nomod] Module 'angularUtils.directives.dirPagination' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

It was working fin then suddenly! BOOM!

**Comment by michaelbromley** [comment]
Did something in your code base change (apart from the huge boom)?

**Comment by sebasira** [comment]
My bad! Sorry scripts where missing on the HTML

**Comment by robbiesmith79** [comment]
Same thing for me. I ass|u|me'd that the bower would add the script line in the html for me. Alas, I just added <script src="bower_components/angularUtils-pagination/dirPagination.js"></script> and all is well with the world.

**Comment by samguergen** [comment]
It looks like the pagination directive doesn't work for more than one table on a page at a time.
