### ISSUE TITLE
dirPagination: Items Per Page Selector

### ISSUE THREAD

**Issue by rjbullock** [michaelbromley/angularUtils#176]
This isn't an issue but a question... Any hints on how I'd implement a drop down that lets the end user select how many items per page are displayed? I couldn't find any examples for this after lots of searching and it seems it'd be a pretty common need.

**Comment by michaelbromley** [comment]
Sure, you can just use a select input and link it to a value on your scope, e.g.

```JavaScript
$scope.itemsPerPage = 10;
```

```HTML
<select ng-model="itemsPerPage ">
  <option value="10">10</option>
  <option value="20">20</option>
  <option value="30">30</option>
</select>
```

**Comment by rjbullock** [comment]
Wow, that's awesome. So easy! Angular is really amazing the more I learn. Thanks!
