### ISSUE TITLE
dir-paginate.-Trying to add spaces between images

### ISSUE THREAD

**Issue by ushaikh147** [michaelbromley/angularUtils#177]
<img height="400" width="400" dir-paginate="image in images | filter:q | itemsPerPage: pageSize" src="{{ image.src }}" current-page="currentPage"></img>

The results display the images all joined to each other.

Trying to add spaces between images..how does that work?

**Comment by michaelbromley** [comment]
Hi,

The image link is broken. Blind suggestion: use css.
