### ISSUE TITLE
dirPagination: allow more than one pagination per page.

### ISSUE THREAD

**Issue by michaelbromley** [michaelbromley/angularUtils#18]
Currently the pagination directive has the limitation that only one instance can exist on a page at once.

There have been a couple of people requesting a way to have multiple instances, and this could be achieved by allowing some kind of identifier to be specified which would link the `dir-pagination-controls` directive with a specific `dir-pagination` directive. 

In this way you could have an arbitrary number of paginations running on one page simultaneously.

**Comment by Geek2016** [comment]
hi there bro i have this situation where i'm stuck w/ i have a to filter the problem is that when i click the button for the other filter the pagination is set to last and do not reset to first not after refresh, any advice  how to deal w/ this?

**Comment by quocanh9ak2** [comment]
thanks michaelbromley. You save my day!.
