### ISSUE TITLE
dirPagination: Passing custom values to template in scope

### ISSUE THREAD

**Issue by Muppets** [michaelbromley/angularUtils#180]
I'm using your pagination directive in Async mode with ngResource to page data. I wanted to show a loading icon in the pagination template when the next page was being loaded. I wanted to solve this in an Angular data binding way, same as the rest of your template, however I could not work out a way to pass this additional loading data into the template without modify your js source which I wanted to avoid.

Modifying your JS with a loading scope property:

![image](https://cloud.githubusercontent.com/assets/638359/8146424/8b285a66-122e-11e5-8d7e-1467a3d5ecb7.png)

Adding my loading spinner to my custom template:

    <li ng-if="boundaryLinks"  ng-class="{ disabled : pagination.current == pagination.last }">
        <a href="" ng-click="setCurrent(pagination.last)">&raquo;</a>
    </li>
    <li ng-show="loading">
        <div class="spinner-loader spinner-loader-page">
            Loading…
        </div>
    </li>

Binding my scope loading parameter to the new property on dir-pagination-controls:

    <dir-pagination-controls boundary-links="true" on-page-change="controller.pageChanged(newPageNumber)" template-url="/views/dirPagination.tpl.html" loading="pageChangeLoading"></dir-pagination-controls>

And finally including this loading flag when pages are changed and query is returned:

        pageChanged(pageNumber) {
            this.$scope.pageChangeLoading = true;
            this.loadPageData(pageNumber);
        }

        loadPageData(pageNumber) {
            this.UserResource.query({ pageNumber: pageNumber },(data) => {
                this.$scope.pageChangeLoading = false;

If you have any suggestions on how I could implement this better, I would welcome it.

If we can't think of any better ways of solving this then maybe adding a data, viewBag or customObject property to the dirPaginationControlsDirective.scope object could be useful for people to be able to pass their own custom objects into the template.

As always, epic utilities and love your work!

**Comment by michaelbromley** [comment]
Hi,

Thanks for the detailed question. I understand what you're trying to do. I am always hesitant at adding new things to the directive API unless there seems to be a fairly widespread need for it. In your case, here are some alternatives I can think of:

1. Show the loading spinner somewhere else. 

2. Extending the first idea, this could even be something like a div just below the pagination controls which, when displaying, covers up the controls via CSS positioning. This could potentially give the effect you are going for without changing the pagination code. Hack factor = 10.

3. Something like this: Make a service that tracks whether the page is loaded yet - `loadingService`. Set `loadingService.pageLoaded = true` when the asyc call returns in your controller.

Then you define another controller, `LoadingController`, into which you also inject the `loadingService`. Now you have access to the loading state of your page calls. You can bind the value of the `pageLoaded` property to the `LoadingController`'s scope. You can then place this controller into your pagination template so you can access the value there, something like:

```
<li ng-if="boundaryLinks"  ng-class="{ disabled : pagination.current == pagination.last }">
    <a href="" ng-click="setCurrent(pagination.last)">&raquo;</a>
</li>
<li ng-controller="LoadingController" ng-show="!pageLoaded">
    <div class="spinner-loader spinner-loader-page">
        Loading…
    </div>
</li>
```


Okay, okay, also a little on the hacky side and adding a bit of complexity to your app. If you really can't live with it, feel free to submit a pull request with your changes and I'll consider adding to the API.

**Comment by Muppets** [comment]
I like the idea of the loadingService. I have similar requirement on most of my controllers to show loading spinners while AJAX calls are happening so this would nicely clean up my controllers from setting loading bools all over the place. My data is already coming from an ng-Resource service so hopefully I can retro fit something into that to say when the service is querying data.

Thanks for your help!
