### ISSUE TITLE
Index collapses after filtering with the given text.

### ISSUE THREAD

**Issue by venkatvb** [michaelbromley/angularUtils#181]
Hi @michaelbromley 

I am using your pagination directive.
I am creating the index number as you suggested in [issue 76](https://github.com/michaelbromley/angularUtils/issues/76)

But the index collapses after searching a text.

Have a look at this [plnkr](http://plnkr.co/edit/GJFbRyGt5nHuzoDlcdQ9?p=preview)

When I search for 'f' in the search box, the index collapses as (1, 4, 5)
I am expecting something like (1, 2, 3)

Thanks.

**Comment by michaelbromley** [comment]
Hi, thanks for providing the demo plunker - that makes my job way easier.

One solution I can immediately think of is to use a $watch on the index like this:

```JavaScript
function RepeatController($scope) {
    $scope.$watch('$index', function(index) {
      $scope.number = (index + 1) + ($scope.currentPage - 1) * $scope.pageSize;
    })
}
```

Check that out and see if it fits your needs.

**Comment by venkatvb** [comment]
Yes that works nice, thanks again.
