### ISSUE TITLE
Using dir-paginate which is nested in two ng-repeat

### ISSUE THREAD

**Issue by ushaikh147** [michaelbromley/angularUtils#182]
Hi, 

I am trying to use dir-paginate which is nested in two ng-repeat and dir-paginate does not work. Any suggestions?

          <div ng-repeat="time in times">
          <div ng-repeat="phi in phis">
           <img height="400" width="400" dir-paginate="theta in thetas | filter:q | itemsPerPage: pageSize" src="image/{{time}}.000000/{{ phi }}/{{theta}}.png" current-page="currentPage"></img>
          </div></div>

Thanks,
Uzma

**Comment by michaelbromley** [comment]
Hi,

Could you be more specific about "does not work"? Even better, put together a demo on Plunker demonstrating what is not working correctly.
