### ISSUE TITLE
dirPaginate: Watch end of clearing pagination

### ISSUE THREAD

**Issue by ricfwolff** [michaelbromley/angularUtils#183]
Hi Michael, great job on the dirPaginate! Thanks!  =)

I just have a little question: Is there anything I can *watch* so I know when the items finished loading?

My problem is that I have to momentarily remove pagination, export the table, and then re-paginate. But it is exporting the filtered table and removing the pagination after my method ends. Do you know if I can put a watch on something to control that?

Thank you very much!

**Comment by michaelbromley** [comment]
Hi, I'm having trouble understanding what exactly you are trying to do. Could you show me a bit of code relevant to the issue?

**Comment by ricfwolff** [comment]
Sorry...

The table is loaded like this:
```html
<tr dir-paginate="item in listItems | filter:{rowVisible: true} | filter:filterString | itemsPerPage: maxItemsPerPage"> ... </tr>
```

And I'm trying to do the following on my script:
```javascript
// Function called by a button to export the html table to Excel
$scope.exportGridToExcel = function () {
    // I save the current "maxItemsPerPage"
    oldMaxItemsPerPage = $scope.maxItemsPerPage;
    // And set it to null, so the table won't be paginated.
    $scope.maxItemsPerPage = null;

    // ** THE PROBLEM HAPPENS HERE **
    // It starts exporting my grid before it is visible on screen. The rows are not loaded yet.
    $("#gridIndex").table2excel({ exclude: ".no-export", name: "Report", filename: "Report" });

    // Put pagination back.
    $scope.maxItemsPerPage = oldMaxItemsPerPage;
 };
```

Please tell me if you need more pieces of the code.

Thanks!

**Comment by ricfwolff** [comment]
Hi, Michael.

I was able to accomplish what I wanted following **finishingmove**'s answer on StackOverflow here:
http://stackoverflow.com/a/15208347/4519548

I created a directive to listen to the end of the ngRepeat:

```javascript
var module = angular.module('testApp', [])
    .directive('onFinishRender', function ($timeout) {
    return {
        restrict: 'A',
        link: function (scope, element, attr) {
            if (scope.$last === true) {
                $timeout(function () {
                    scope.$emit(attr.onFinishRender);
                });
            }
        }
    };
});
```

And on my controller I catched that with $on:
```javascript
$scope.$on('ngRepeatFinished', function(ngRepeatFinishedEvent) {
    //you also get the actual event object
    //do stuff, execute functions -- whatever...
    if ($scope.isExportingGridIndex) {
        $scope.isExportingGridIndex = false;

        $("#gridIndex").table2excel({ exclude: ".no-export", name: "Report", filename: "Report" });

        $scope.maxItemsPerPage = $scope.oldMaxItemsPerPage;
    }
});
```

With html that looks like this:
```html
<tr 
    dir-paginate="item in listItems | filter:{rowVisible: true} | filter:filterString | itemsPerPage: maxItemsPerPage" 
    on-finish-render="ngRepeatFinished">
...
</tr>
```

It worked the way I wanted. Only exporting when angular's finished loading all the items...

But thank you for the quick response!  =)

**Comment by xbipin** [comment]
hi ricfwolff, can u kindly let me know how does ur ng-click have because im stuck in same situation, what i want to do is when i click the export button, i want to remove pagination then export and then repaginate. i created same controller listener and directive but cant seem to trigger it on pressing the button, im new to angular

**Comment by ricfwolff** [comment]
Hi @xbipin! Sorry for the delay. 
My angular controller have the following functions:

Note: I used a component called ALaSql (http://alasql.org/) to do the magic on exporting angular data to excel.

``` javascript
    $scope.loadAllItens = function () {
        var takeNumber = 99999;
        $scope.loadList(takeNumber);
    };

    $scope.exportGridToExcel = function () {
        $scope.loadAllItens();
        $scope.isExportingGridIndex = true;
    };

    $scope.$on('ngRepeatFinished', function () {
        if ($scope.isExportingGridIndex) {
            $scope.isExportingGridIndex = false;
            $scope.exportData();
        }
    });

    $scope.exportData = function () {
        var reportName = 'Report '; 

        var queryColumns = 'Column A, ColumnB, ColumnC';

        alasql('SELECT ' + queryColumns + ' INTO XLSX("' + reportName + '.xlsx", {header:true}) FROM ?', [$scope.myData]);
    };
```

And my HTML has the following on ng-click:

``` html
<a id="ActionExportToExcel" ng-click="exportGridToExcel()" href="">Export To Excel</a>
```

Hope that helps you!
Rick

**Comment by xbipin** [comment]
well the problem i was having was i tried using table2excel with dir-paginate and i had a few filters in it for search etc and if the pages exceeded to more than 1 and then u remove pagination then on n-finish-render event the table would export properly but if the table was just one page length then removing pagination wouldnt generate the event to export the table
