### ISSUE TITLE
Text Filter with Pagination?

### ISSUE THREAD

**Issue by krusk** [michaelbromley/angularUtils#185]
I can't seem to get a normal text filter working with the pagination directive. I am missing something?

    <input type="text" data-ng-model="searchText" />
    <tr dir-paginate="image in images | itemsPerPage: 10 | filter:searchText">

Thanks for the assistance!
K.

**Comment by krusk** [comment]
Disregard, as values hidden in my array were causing it to create false positives.

**Comment by michaelbromley** [comment]
Okay. Also, putting the `itemsPerPage` filter last in the expression is usually recommended (unless you have a particular reason not to).

**Comment by krusk** [comment]
Makes sense. Thanks for the assistance.
