### ISSUE TITLE
dirPagination: pagination not working when use tbody and dynamic rowspan ?

### ISSUE THREAD

**Issue by ahmedamen** [michaelbromley/angularUtils#188]
Hi
i try to use dirPagination with my design but it's not working - in my code i pass rowspan dynamically to group each month day's in one row to get final result as:

![untitled](https://cloud.githubusercontent.com/assets/7356190/8421324/242770f8-1ecd-11e5-8f84-fb2f47bf79d1.png)

HTML Code:

```html
<div class="panel panel-default panel-hovered panel-stacked mb20">
    <div class="panel-heading" style="font-size:15px;">عرض العملاء الغير جاهزين</div>
    <div class="panel-body" dir="rtl" ng-app="jqanim" ng-controller="InvoiceController">
        <input type="text"
               class="form-control input-sm ng-pristine ng-valid ng-touched"
               placeholder="اكتب جزء من الاسم او المدينة او النوع او التاريخ ..."
               tabindex="0"
               aria-invalid="false"
               ng-model="searchText">
        <br />
        <br />
        <table class="table table-bordered">
            <thead>
                <tr class="text-center">
                    <td>الشهر</td>
                    <td>العميل</td>
                    <td>المدينة</td>
                    <td>النوع</td>
                    <td>التاريخ</td>
                </tr>
            </thead>
            <tbody ng-repeat="customer in customersByMonth">
                <tr ng-repeat='cust in customer | filter:searchText'>
                    <td ng-if="$first" rowspan="{{customer.length}}" class="text-center">
                        {{cust.MirageDate | date: 'yyyy-MM'}}
                    </td>
                    <td>{{cust.CustomerName}}</td>
                    <td class="text-center">{{cust.City.CityName}}</td>
                    <td class="text-center">{{cust.Type.TypeName}}</td>
                    <td class="text-center">{{cust.MirageDate | date: 'yyyy-MM-dd'}}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
```

AngularJS Code:

    <script>
        var app = angular.module('jqanim', []);

        app.controller('InvoiceController', [
                           '$scope', '$http', function ($scope, $http) {
                               $http.get("/api/NoReady")
                                   .success(function (data) {
                                       var dataByMonth = {};
                                       data.forEach(itemToMonth);
                                       $scope.customersByMonth = dataByMonth;

                                       function itemToMonth(item) {
                                           item.MirageDate = new Date(item.MirageDate)
                                           var month = item.MirageDate.getMonth();
                                           var year = item.MirageDate.getFullYear();
                                           dataByMonth[year + '-' + month] = dataByMonth[year + '-' + month] || [];
                                           dataByMonth[year + '-' + month].push(item);
                                       }
                                   });
                           }
        ]);
    </script>
i try to use dirPagination to get 2 tbody per page but not working and add dir-pagination-controls and add files dirPagination.js & dirPagination.tpl.html to my project and final code to pagenate is:

```html
<div class="panel panel-default panel-hovered panel-stacked mb20">
    <div class="panel-heading" style="font-size:15px;">عرض العملاء الغير جاهزين</div>
    <div class="panel-body" dir="rtl" ng-app="jqanim" ng-controller="InvoiceController">
        <input type="text"
               class="form-control input-sm ng-pristine ng-valid ng-touched"
               placeholder="اكتب جزء من الاسم او المدينة او النوع او التاريخ ..."
               tabindex="0"
               aria-invalid="false"
               ng-model="searchText">
        <br />
        <br />
        <table class="table table-bordered">
            <thead>
                <tr class="text-center">
                    <td>الشهر</td>
                    <td>العميل</td>
                    <td>المدينة</td>
                    <td>النوع</td>
                    <td>التاريخ</td>
                </tr>
            </thead>
            <tbody dir-pagination="customer in customersByMonth | itemsPerPage: 2">
                <tr ng-repeat='cust in customer | filter:searchText'>
                    <td ng-if="$first" rowspan="{{customer.length}}" class="text-center">
                        {{cust.MirageDate | date: 'yyyy-MM'}}
                    </td>
                    <td>{{cust.CustomerName}}</td>
                    <td class="text-center">{{cust.City.CityName}}</td>
                    <td class="text-center">{{cust.Type.TypeName}}</td>
                    <td class="text-center">{{cust.MirageDate | date: 'yyyy-MM-dd'}}</td>
                </tr>
            </tbody>
        </table>
        <div class="text-center">
            <dir-pagination-controls boundary-links="true" template-url="/dirPagination.tpl.html"></dir-pagination-controls>
        </div>
    </div>
</div>
```

    <script>
        var app = angular.module('jqanim', ['angularUtils.directives.dirPagination']);

        app.controller('InvoiceController', [
                           '$scope', '$http', function ($scope, $http) {
                               $http.get("/api/NoReady")
                                   .success(function (data) {
                                       var dataByMonth = {};
                                       data.forEach(itemToMonth);
                                       $scope.customersByMonth = dataByMonth;

                                       function itemToMonth(item) {
                                           item.MirageDate = new Date(item.MirageDate)
                                           var month = item.MirageDate.getMonth();
                                           var year = item.MirageDate.getFullYear();
                                           dataByMonth[year + '-' + month] = dataByMonth[year + '-' + month] || [];
                                           dataByMonth[year + '-' + month].push(item);
                                       }
                                   });
                           }
        ]);
    </script>

    <script src="~/dirPagination.js"></script>

but not working i still get data as image and no pagination - so please how can i do it with my scenario ?

Thanks a lot ....

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. Unfortunately I don;t have a great deal of free time to take in all that code and try to find the error. What would be really helpful is if you could reproduce the bug in Plunker - this makes my job much, much easier.

**Comment by ahmedamen** [comment]
Thanks a lot Michael

here is bug in Plunker

http://plnkr.co/edit/hr9zj6WMW0G6oRWOxC63?p=preview

as you can see pagination not working - hope you can tell me what is the problem here and how can i fix it to let pagination working with my senario

Thanks a lot ....

**Comment by michaelbromley** [comment]
Just checked out your Plunker demo. I see that you are trying to paginate over an object rather than an array. This is not currently supported, see https://github.com/michaelbromley/angularUtils/issues/20

I suggest you try to work it into an array - I've no plans right now to work on support for paging over objects, sorry.

**Comment by ahmedamen** [comment]
Thanks a lot

i still new with angularjs and if you please can tell me what i must do or how i can make it works that will be great favour 

Thanks again

**Comment by michaelbromley** [comment]
Well, there's nothing Angular-specific involved. I just mean convert the object into an array. 
Looking at your code, I see you start with an array anyway,but then convert it into an object in order to group by month.

I'd suggest you keep it as an array, and use some other strategy to do the grouping.

**Comment by michaelbromley** [comment]
Update: paginating over objects is now supported since version 0.9.0: https://github.com/michaelbromley/angularUtils-pagination/releases/tag/v0.9.0
