### ISSUE TITLE
Having trouble declaring the module needed when using ionic

### ISSUE THREAD

**Issue by stoyo** [michaelbromley/angularUtils#191]
What is the proper syntax for adding the ['angularUtils.directives.dirPagination'] line, when using ionic, because when using ionic it is like that: angular.module('todo', ['ionic'])

**Comment by michaelbromley** [comment]
If you have more than one dependency, just add it to the array:

```JavaScript
angular.module('todo', ['ionic', 'angularUtils.directives.dirPagination']);
```

**Comment by stoyo** [comment]
Everything crashes that way, have you actually tested it?

**Comment by michaelbromley** [comment]
I haven't made a specific test with Ionic and this module, no; but that is the general syntax.

When you say "everything crashes" - what exactly do you mean? Are there some error messages you could post here?

**Comment by stoyo** [comment]
![withoutpagination](https://cloud.githubusercontent.com/assets/9303413/8594273/11a33e08-2648-11e5-9208-f0041ee664f1.jpg)
![withpagination](https://cloud.githubusercontent.com/assets/9303413/8594277/11a72234-2648-11e5-8f93-c87f9a1999e3.jpg)
![listcode](https://cloud.githubusercontent.com/assets/9303413/8594276/11a673b6-2648-11e5-93dd-7b37b88764fb.jpg)
![appcode](https://cloud.githubusercontent.com/assets/9303413/8594275/11a63ba8-2648-11e5-944e-d1edbf3a1dc9.jpg)
![indexcode](https://cloud.githubusercontent.com/assets/9303413/8594274/11a5ad3c-2648-11e5-92b8-2e067430e33a.jpg)


The picture when there is an actual output is the one when pagination is not used, afterwards are the changes I made to try this directive. Based on what the console says about the problem, I think I am just not experienced enough and I don't know how to load the module.

**Comment by michaelbromley** [comment]
Thanks for providing all the screen shots. One thing looks strange to me:

In your HTML, you call your app "starter", i.e. `ng-app="starter"`, but in the JS code you call the module "todo". The error message in the console indicates that Angualr is looking for the module named "starter", which it cannot  find. Try changing your HTML to `ng-app="todo"` and see if that fixes it.

**Comment by stoyo** [comment]
No, it is not that. I just copied it from your example that time and didn't pay attention when changing the names. Same output when the module's name is the same everywhere, though.

**Comment by michaelbromley** [comment]
Strange. I just tested this by adding Ionic to the demo plunker, and it seems to work okay for me: http://plnkr.co/edit/ayncQF?p=preview

**Comment by stoyo** [comment]
Hm, okay, after at least 2 hours of more testing I think I almost got it. I downloaded the files required and made it kind of manually, however,  I have another question now. The problem is that the design is messing around and I am wondering about the styling. That is how the page looks now, it just doesn't make sense.
![outputalmost](https://cloud.githubusercontent.com/assets/9303413/8601072/5b14d130-2672-11e5-8aa2-86999d80b0d2.jpg)

As you can see, the list items are with more padding and look awful and the pages are outputted just unacceptably. Can you please give me a tip or two, what to do, I am thinking of finding the file, responsible for the styling of the dir-pagination-controls, but I am not getting anywhere

**Comment by stoyo** [comment]
![outputalmost](https://cloud.githubusercontent.com/assets/9303413/8601195/494646b8-2673-11e5-8b1a-3ac1d99e674e.jpg)

That is where I got it so far. Can you please tell me where to look for the styling of the dir-paginate-controls so that it doesn't mess around with the output of the page that much. If it matters here is the the code of the page.

![responsible](https://cloud.githubusercontent.com/assets/9303413/8601277/d5d032ba-2673-11e5-897c-65aa7d8a894f.jpg)

Note: the tag dir-pagination-controls is closest there was just not room for it on the picture

**Comment by michaelbromley** [comment]
Hi,
There is no styling included for the pagination controls. It is designed to work with Bootstrap CSS, but in your case you can just style it yourself or copy the part from bootstrap.

**Comment by stoyo** [comment]
Great, thanks for being so helpful, much appreciated !!!
