### ISSUE TITLE
'as results' filtering and itemsPerPage

### ISSUE THREAD

**Issue by DrChills** [michaelbromley/angularUtils#192]
ok, so this is expected - but not desirable:

      dir-paginate="item in items | filter:q | itemsPerPage: pageSize as results"

      {{results.length}}

results.length will return the amount of items per page, instead of the amount of filtered items from filter:q - I'm not sure this is desirable as it renders the 'as results' feature useless. I understand that I can write controller logic however the usual out-of the-box 'as results' feature is excellent when using several filters

**Comment by michaelbromley** [comment]
I wouldn't say it renders the feature useless - just useless in your particular case.

How about something like this: 

```
dir-paginate="item in results = ( items | filter:q ) | itemsPerPage: pageSize"

{{results.length}}
```

**Comment by DrChills** [comment]
Perfect! Thank you, That actually makes more sense to me than the standard way of using 'as results'

**Comment by michaelbromley** [comment]
:+1:

**Comment by tcdevs** [comment]
:+1:
