### ISSUE TITLE
dirPaginate in IE7 and IE8 gives error 

### ISSUE THREAD

**Issue by IreneFelita** [michaelbromley/angularUtils#194]
Hi,

This module is really nice. I use it to replace the out of the box pagination from angular when it comes with sorting.
However, my project required to be compatible with IE8 below .
Is it compatible with IE7 and 8? 
Because I find issue on IE7 and 8 when use Document Mode = 7 and 8 in IE11. 

The error said: 
Unexpected call to method or property access.

I debug the codes and found out the error on below code. However the error only appears after the end of the second call:

    function itemsPerPageFilter(paginationService) {

        return function(collection, itemsPerPage, paginationId) {
            if (typeof (paginationId) === 'undefined') {
                paginationId = DEFAULT_ID;
            }
            if (!paginationService.isRegistered(paginationId)) {
                throw 'pagination directive: the itemsPerPage id argument (id: ' + paginationId + ') does not match a registered pagination-id.';
            }
            var end;
            var start;
            if (collection instanceof Array) {
                itemsPerPage = parseInt(itemsPerPage) || 9999999999;
                if (paginationService.isAsyncMode(paginationId)) {
                    start = 0;
                } else {
                    start = (paginationService.getCurrentPage(paginationId) - 1) * itemsPerPage;
                }
                end = start + itemsPerPage;
                paginationService.setItemsPerPage(paginationId, itemsPerPage);

                return collection.slice(start, end);
            } else {
                return collection;
            }
        };
    }

Do you know how to fix this problem?

**Comment by IreneFelita** [comment]
Oh and I also changed .hasAttribute to .getAttribute to be compatible with IE 8 and below.

    function addNgRepeatToElement(element, attrs, repeatExpression) {
            if (element[0].getAttribute('dir-paginate-start') || element[0].getAttribute('data-dir-paginate-start')) {
                // using multiElement mode (dir-paginate-start, dir-paginate-end)
                attrs.$set('ngRepeatStart', repeatExpression);
                element.eq(element.length - 1).attr('ng-repeat-end', true);
            } else {
                attrs.$set('ngRepeat', repeatExpression);
            }
        }

**Comment by michaelbromley** [comment]
Hi, have you seen [this issue](https://github.com/michaelbromley/angularUtils/issues/64)? Might contain a fix for you.

Specifically, try using `dir-pagination-controls` as a *attribute* rather than an element, since < IE8 doesn't support non-standard elements. So:

```HTML
<div dir-pagination-controls ... ></div>
```

**Comment by IreneFelita** [comment]
Hi,

Thanks for the response.
I did fix the issue using <div dir-pagination-controls ... ></div>
In IE8 it is rendered and working perfectly. 

But in IE7 although it is rendered, when click on the page link, it keep refreshing to page 1.

Do know why this happen.

**Comment by michaelbromley** [comment]
No, I don't know without looking into it. Are there any error messages in the console?

**Comment by gilangaramadan** [comment]
I have a problem like this too, thanks @michaelbromley it works! :)
