### ISSUE TITLE
Is there a "on-page-load" API?

### ISSUE THREAD

**Issue by kanesee** [michaelbromley/angularUtils#196]
There's an "on-page-change" attribute option for <dir-pagination-controls>, but this isn't called on the initial loading of the first page.

The use case is, I need to instantiate some &lt;svg&gt; on the items of the current page.
I can't just do this right after I retrieve all the items because the ng-repeat directive hasn't created all the elements yet and I need an element to attach the &lt;svg&gt; to. I can't do call it right after the ng-repeat directive creates the last item either because the pagination directive removes all of them except the ones on the current page. So I need to wait till the pagination is done with its work.

**Comment by michaelbromley** [comment]
Hi,

There is currently no such API. From your description alone I can't really suggest anything concrete to try. If you have time to put together a plunker demo I might be able to take a look and suggest something.

**Comment by kanesee** [comment]
Sure, that would be great.
Here's the plunker: http://plnkr.co/edit/LfspWDTJUH17yiX7Jd1e?p=preview

Notice that the first page is empty, but if you change pages, the graph pops up because I have a hook to initGraph() thanks to on-page-change.

Now, I could simply call initGraph() right after I get the data (on line 40 of app.js) which is currently commented out. But this doesn't always work due to some timing issue. I think it needs to wait until the DOM is created before calling the initGraph() function, rather than when the scope variable is assigned.

**Comment by michaelbromley** [comment]
Thanks for the demo.

When I uncommented line 40, it worked every time I tested. I mean, I refreshed for a couple of minutes and tried changing the itemsPerPage, but it just seemed to work.

Initially, after reading your last comment I was going to suggest putting the call in a $timeout() in order to guarantee that the code executes only after the current event loop cycle has finished. Then I saw that you already do that. Is that also the case in your non-working real code?

**Comment by kanesee** [comment]
It works most of the time for me too, especially more so on plunker than in my dev environment for some reason.

I think it's just a timing issue and it's not a big deal. In my code, I call it similar to line 40 and I set a slightly higher $timeout value to wait for dir-paginate directive to finish doing what it needs to.
Every once in awhile, the elements haven't been fully created by ng-repeat and I can't write the graph for a few rows. Or the ng-repeat is complete and I write the graph for some rows that get removed by dir-paginate. (at least I think that's what's happening).

Just something to consider in the future. No big deal.
