### ISSUE TITLE
auto-hide="false" not working

### ISSUE THREAD

**Issue by rgpass** [michaelbromley/angularUtils#198]
`auto-hide="false"` is not working. To replicate:

```html
<span dir-pagination-controls auto-hide="false"></span>

<tr dir-paginate="model in models | itemsPerPage:10">
    blah
</tr>
```

Set `models` to an array of size < 10. The `pagination-controls` disappears.

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. Looks like the default external template did not get updated when that feature was added. Can you confirm whether you are using the default template (dirPagination.tpl.html)?

**Comment by rgpass** [comment]
Thanks for the quick response!

I had: `<ul class="pagination" ng-if="1 < pages.length">`
Repo has: `<ul class="pagination" ng-if="1 < pages.length || !autoHide">`

Updated the code and it works.

Totally off topic but always trying to learn: Why do you have `==` in `pagination.current == pagination.last` instead of `===`?

**Comment by michaelbromley** [comment]
Good stuff. 

Regarding the use of `==`, I'm not sure if there is a good reason for that. There may have been one, but if so, I no longer remember what it is. The only reason I can think of would be in the case that you are not sure if the value will be a number or a string containing a number character. 

I suspect it could be changed to `===` without any ill effects.
