### ISSUE TITLE
Er injection error. 

### ISSUE THREAD

**Issue by uncamoe** [michaelbromley/angularUtils#199]
. I installed your directive using bower and I am having an issue getting it injected into my app. Uncaught Error: [$injector:modulerr] and the important part: 0%3DangularUtils.directives.uiBreadcrumbs%26p1.. is this the proper injection? 'ui.router','angularUtils.directives.uiBreadcrumbs', ? 
I have copied this over from attack overflow: http://stackoverflow.com/questions/21970406/how-to-make-automated-dynamic-breadcrumbs-with-angularjs-angular-ui-router/22865873?noredirect=1#comment50906355_22865873

**Comment by uncamoe** [comment]
Posted by Stephen Nielsen

**Comment by michaelbromley** [comment]
Hi,

Did you also include the uiBreadcrumbs.js script in your page too?

**Comment by uncamoe** [comment]
I used bower to install it,  and confirmed

**Comment by michaelbromley** [comment]
Could you paste in the full error message, and also the code where you define your angular app & dependencies?

**Comment by uncamoe** [comment]
I sure can.  I appreciate the help.  Let me get to the office and I will.

**Comment by michaelbromley** [comment]
So... did you ever get to the office? ;)

Closing for now, reopen it if you still need help.
