### ISSUE TITLE
dirPagination: Object of objects not working with dirPagination, only an array of objects.

### ISSUE THREAD

**Issue by abrist** [michaelbromley/angularUtils#20]
Excuse my knowledge on this as I am *very* new to angular.  I have a bit of code that gets some json through ajax, specifically an object of objects.  Using ng-repeat works fine (no pagination).  But if I implement dirPagination, the results do not paginate and no pagination links are displayed (I am including the itemsPerPage filter).  But if I change the object of objects to an array of objects, dirPagination works as expected.

Is this a known issue?  I could push each object into a referential array (and I may just do that), but angular overall seems fine with object containers or array containers (ng-repeat etc).

I am ok with either way, I am just curious if this is WAI/known.
 
Oh yeah, almost forgot - Thanks for the spectacular suite of utils, you rock!

**Comment by michaelbromley** [comment]
Object support now added, see https://github.com/michaelbromley/angularUtils-pagination/releases/tag/v0.9.0

**Comment by prabhakaranarumugam** [comment]
could u please tell how to paginate i hav 3 ng repeat and  nested arrary
