### ISSUE TITLE
"current-page" attribute is ignored after changing page with "dir-pagination-controls"

### ISSUE THREAD

**Issue by inikolov89** [michaelbromley/angularUtils#209]
situation: I use the plugin with a dynamic list - i.e., I add elements to the list with a button: $scope.items = updatedData.items

goal: 
- I want like to go to the page, where a newly created item is placed.
- example: Items per page = 3 -> Current number of items = 3 -> Add new Item -> Automatically jump to page 2 (where the new item is placed)

approach: I dynamically change ”current-page” after adding a new item:
```
$scope.items = updatedData.items
$scope.currentPage = newPageNumber;
```

problem: after a manual page change with ”dir-pagination-controls”, the ”current-page” attribute is ignored even when the value of the respective $scope-variable changes.

This seems to me like a issue, probably related to [issue #120](https://github.com/michaelbromley/angularUtils/issues/120)

**Comment by ffsantos92** [comment]
Controller:
```js
$scope.pagination = {
    current: 2
};
```
Html (example):
```html
<div dir-paginate="item in result.items | itemsPerPage: itemsPerPage" total-items="result.total" current-page="pagination.current"></div>
```

**Comment by michaelbromley** [comment]
@inikolov89 Thanks for the report. Any chance you can put together a demo of the issue on Plunker? Regarding the issue you reference (#120), I was able to get it working (see the Plunker demo there), and have not heard back from the original reporter of the issue.

**Comment by inikolov89** [comment]
Thanks for the fast response.

I created a Plunker demo: [Demo](http://plnkr.co/edit/mFdyzNQQ8QGc014dLoOr?p=preview)

* To reproduce:
 - add 4 new elements
 - use ”dir-pagination-controls” to go to previous page
 - add 1 new element

-> problem: directive stays on the same page - instead of showing the next page of the recently added element

* probable cause - the problem only occurs when using the pagination in a template:
```
<div data-ng-include data-src="'ElementsPagination.tpl.html'"></div>
```

I need to use the pagination in a template - so that we have a modular view architecture.

**Comment by michaelbromley** [comment]
Thanks for the demo. 

I am not totally sure, but I suspect the problem has to do with the way primitive values (number, string) will be "shadowed" due to prototypical inheritance. Supporting this is that if you use `$scope.pagination.currentPage` rather  than `$scope.currentPage` in your demo, it will work.

It looks like ng-include creates its own child scope, which means that as soon as a value for `currentPage` is set in that scope, it will shadow and "overwrite" the one defined in your parent scope.

Hope that helps.
