### ISSUE TITLE
switch from templateURL to ng-include

### ISSUE THREAD

**Issue by LennyLip** [michaelbromley/angularUtils#210]
Pagination Directive.
Cool app, but i want use dynamic url for template.

i think app should use ng-include :

http://stackoverflow.com/a/21835866/1271271

**Comment by michaelbromley** [comment]
Hi, thanks for the suggestion.

I've no plans to add this functionality unless I get more calls for it (this is the first). However, I think you could solve this by creating your own wrapper directives, one for each template you wish to use, which can be then be ng-included in your app.
