### ISSUE TITLE
Bookmark pages

### ISSUE THREAD

**Issue by bighoax** [michaelbromley/angularUtils#214]
Is it possible to bookmark pages? For example if you are on page 10, and you want your user to bookmark and be back to page 10.

Can the page links include get param `page` or something, is that possible now? How would one go about doing that?

**Comment by michaelbromley** [comment]
Hi, yes you can do this. One way would be to use the `$location` service and set the `$location.search('page', currentPage);` whenever you change pages. Then, when the controller is instantiated, you check the value of `$location.search().page` and use that to set the currentPage.
