### ISSUE TITLE
dirPaginate: Next page and current page items showing concurrently

### ISSUE THREAD

**Issue by mechafractal** [michaelbromley/angularUtils#217]
When I click the link to navigate to the next page, the items for the next page are added to the top of the list, then a visible fraction of a second later the items from the previous page are removed.

This looks very odd from the user's point of view and is happening in all of our uses of dirPaginate

I've looked for similar issue on here but can't find any.

Is this a known issue?

Hopefully you can see the issue from this gif based screen grab. Here I am going from Page 3 to Page 4 but for a time, both pages of data are being shown at once.

![dir-paginate](https://cloud.githubusercontent.com/assets/1140834/9357331/46231bfc-467e-11e5-8547-f953a2c2eca0.gif)

**Comment by michaelbromley** [comment]
Are there any animations defined on your rows? This can be a cause of such behaviour.

**Comment by mechafractal** [comment]
I thought that too but there aren't any as far as I can tell. I'll check with the design team and see if they know better than me.

**Comment by mechafractal** [comment]
Our bad. You're right, there was a rogue transition hiding in the CSS. All is well now.

Thanks for the prompt response, very impressive support

**Comment by michaelbromley** [comment]
Good to hear. You got lucky cos I was waiting for some tasks to complete at work and happened to see the little blue message indicator. I usually take *at least* a day, or even weeks. ;)
