### ISSUE TITLE
Sorting paginated results

### ISSUE THREAD

**Issue by Hypocrite** [michaelbromley/angularUtils#219]
Hi,

Is it possible to sort all paginated results in front end or do we need to do this in the backend?

At the moment applying orderBy filter to the paginated list it only affects the visible page but not all results.

Example like this:
```
<div dir-paginate="item in filteredItems = (items | filter:search | filter:type:strict | itemsPerPage: 50 | orderBy:order) track by $index" on-start-render="ngRepeatStarted" on-finish-render="ngRepeatFinished" pagination-id="smallSize" data-items></div>
```

**Comment by michaelbromley** [comment]
Hi,

make sure the `itemsPerPage`filter is at the end of the expression. Then it should work.

**Comment by Hypocrite** [comment]
Changed code to this:
```
<div dir-paginate="item in filteredItems = (items | filter:search | filter:type:strict | orderBy:order | itemsPerPage: 50) track by $index" on-start-render="ngRepeatStarted" on-finish-render="ngRepeatFinished" pagination-id="smallSize" data-items>
```

But I am still getting the same order where the items in order only in the visible page.

**Comment by michaelbromley** [comment]
Do you have time to put together a demo of this behaviour in Plunker? Then I could get a better idea of what might be going wrong.

**Comment by Hypocrite** [comment]
Sure, I can try to get one done tomorrow.

**Comment by Hypocrite** [comment]
I think track by $index was messing with the order. I removed that and it seemed to fix the sort problem.

**Comment by michaelbromley** [comment]
Okay, thanks for following up on that.

**Comment by kanbara** [comment]
I would like to use `track by index' with my set of filters. My code is something like: 

```
  <tr dir-paginate="item in deliveryItems | 
                             orderBy:sortType:sortReverse | 
                             filter:searchDeliveryItems track by item.deliveryItemId |
                             itemsPerPage: 10">

```

This issue still persists for me.
