### ISSUE TITLE
Pagination is not being displayed

### ISSUE THREAD

**Issue by gustavolira** [michaelbromley/angularUtils#221]
Hi,

For some reason the pagination is not being displayed. The results are working and being showing ok at my page, I'm using:
```HTML
<dir-pagination-controls></dir-pagination-controls>

<div class="box-item-test" dir-paginate="test in searchTests.getResult() | itemsPerPage: 10" total-items="10" current-page="1">
```
But <dir-pagination-controls> directive not include the html pagination, the final html still with 
```HTML
<dir-pagination-controls>
```

I'm using "angular-utils-pagination": "~0.8.3" at bower with angular 1.3.17

**Comment by michaelbromley** [comment]
Hi,

Perhaps the template it not being found? Is there any error in the console?

**Comment by gustavolira** [comment]
Hi,

Thanks for your attention.

There is no 404,  Template is being found. It was installed by bower

2015-08-27 4:20 GMT-03:00 Michael Bromley <notifications@github.com>:

**Comment by michaelbromley** [comment]
Hi,

Sorry for the slow reply. I can't think of what this could be from the information you gave me. Other than if you are using IE8, which doesn't like custom tags like `<dir-pagination-controls>`.

Are you able to reproduce the error in a plunker demo?

**Comment by adamcee** [comment]
Hi,

I saw this issue and was confused for a while by something similar. The default setting is to NOT show pagination controls if there are not more than 1 page of items to paginate. So, for pageSize = 10, if there are only 10 items total, page controls will be invisible. The docs describe how to change this behavior. Could that be what's happening here?

**Comment by michaelbromley** [comment]
Closing. Please re-open if this is still an issue.
