### ISSUE TITLE
Angular Throws Exception on dirPagination Load

### ISSUE THREAD

**Issue by jombee** [michaelbromley/angularUtils#222]
When I read the output of my Visual Studio 13 on my project's load, I get the following exception:

Exception was thrown at line 1983, column 11 in http://localhost:50344/Scripts/angular.js

0x800a139e - JavaScript runtime error: [$injector:nomod] Module 'angularUtils.directives.dirPagination' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.4/$injector/nomod?p0=angularUtils.directives.dirPagination

It DOES NOT affect the functionality of dirPagination, but it is strange that it comes up. 

In my index.html, I have the link to dirPagination.js declared after my link to angular itself and before the declarations of dependency for my app's module in app.js. 

As I said, dirPagination is working anyway, but it is a noodle scratcher as to why angular can't find it. Just want to make you guys aware of it. 

Awesome library by the way! Thank you!

**Comment by michaelbromley** [comment]
Hi,

so to get this straight - the error only occurs in the VS2013 IDE and not in the browser console?

**Comment by jombee** [comment]
Yea that is correct. Sorry for not responding sooner.

**Comment by michaelbromley** [comment]
Okay. In that case, I'm not going to address this issue unless more people run in to it, since it sounds like a peculiarity of a specific IDE rather than a bug with the module itself.
