### ISSUE TITLE
Callback specified in on-page-change attribute is not getting called

### ISSUE THREAD

**Issue by arvind88** [michaelbromley/angularUtils#223]
I am working on a mobile app using Ionic Framework.

I want Prev, Next based navigation, so I have removed any code belonging to numbered navigation,

This how the pagination template looks,

```html
<div class="tabs tabs-icon-only pagination" ng-if="1 < pages.length || !autoHide">
    <a class="tab-item" ng-class="{ disabled : pagination.current == 1 }" ng-click="setCurrent(pagination.current - 1);">
        <button class="button icon ion-arrow-left-c"></button>
    </a> 
    <a class="tab-item" ng-class="{ disabled : pagination.current == pagination.last }" ng-click="setCurrent(pagination.current + 1);">
        <button class="button icon ion-arrow-right-c"></button>
    </a>
</div>
```

Pagination is working fine, but the on-page-change attribute on ```<dir-pagination-controls>``` does not seem to work.

Here is the code,

View
```html
<dir-pagination-controls on-page-change="pageChanged(newPageNumber)" template-url="app/pagination/next-prev-pagination.tpl.html"></dir-pagination-controls>
```

<br/>
Controller
```javascript
$scope.pageChanged = function(newPage) {
    console.log("inside pageChanged");
    if (audioService.getMediaStatus() == 1 || audioService.getMediaStatus() == 2 || audioService.getMediaStatus() == 3) {
        vm.isPlaying = false;
        audioService.stop();
    }
}
```

I have added the console statement for debugging. Though the navigation is working, nothing gets printed in the console.

<br/>
Even tried with the alternative using $scope.$watch(), but seems to work only during page load.

Code for the same,
```html
<li dir-paginate="question in questions | itemsPerPage: 1" current-page="currentPage">
    ...
    ...
</li>
```

Controller
```javascript
$scope.$watch('currentPage', function(newValue, oldValue) {
    console.log("inside watch");
    $scope.pageChanged();
});
```

watch() is fired only once during page load and not while navigating through pagination.

Any help on this.

**Comment by michaelbromley** [comment]
Hi,

Thanks for the detailed post. Looking at the code you posted, I don't see any obvious issues that could explain this. I've never used Ionic so I don't know if it could be something peculiar to that framework.

Is it possible to reproduce the error in a plunker?

**Comment by arvind88** [comment]
It was a syntax problem.

I had used ngController directive to bind controller class with the view and ```<dir-pagination-controls>``` was outside the controller div.

Code with error,

```
<div ng-controller="MyCtrl">
    ...
    ...
</div>
<dir-pagination-controls on-page-change="pageChanged(newPageNumber)" template-url="app/pagination/next-prev-pagination.tpl.html"></dir-pagination-controls>
```

<br/>
After changing it to this, it started working

```
<div ng-controller="MyCtrl">
    ...
    ...
    <dir-pagination-controls on-page-change="pageChanged(newPageNumber)" template-url="app/pagination/next-prev-pagination.tpl.html"></dir-pagination-controls>
</div>
```
<br/>
As I am new to angular, I was not aware of the concept of scope.

**Comment by michaelbromley** [comment]
Ok, no worries and thanks for the update.
