### ISSUE TITLE
Asynchronous data doesn't get rendered upon a fulfilled promise

### ISSUE THREAD

**Issue by twilliamsgsnetx** [michaelbromley/angularUtils#224]
I am pulling data in from a service to my controller, via a promise, and also caching it in localStorage. The data initially did not display, but when I refreshed and it was using the localStorage everything worked peachy.

After hours I tracked it down to this pagination directive, which I completely didn't expect. What would cause the data to not display when the promise returns, through the pagination directive? It displays if I use ng-repeat.

**Comment by pcnate** [comment]
You likely need a code example to get any help and determine if this is more than just a request for help.

**Comment by twilliamsgsnetx** [comment]
It's not help that I need, because I've decided to stick with angular bootstrap paginate which works right out of the box with the same data.
