### ISSUE TITLE
Index of items reseting

### ISSUE THREAD

**Issue by flacohenao** [michaelbromley/angularUtils#227]
Hi, this is not a bug, but its good to be considered like a furute improvement of the directive.

Even with the directive working for example if a i have 2 pages paginated ecery page has an $index to themselves.

Is not that too hard to implement CRUD functionalitys? like deleting or updatig passing the $index of a list asumming that the ng-repeat gives it to you?

its just an opinion, maybe we can keep the original index of the list!!

**Comment by michaelbromley** [comment]
Hi,

I'm not totally sure that I understand what you are suggesting. Do you mean you would like some way to get the index of the items in the collection which takes into account the page you are one? I.e. with 10 items per page, the "index" of the first item on the second page is "11"?

**Comment by flacohenao** [comment]
yes sir, that's what im suggesting, but anyway I solved it using a regular bucle for iterate the objects in the collection and do the CRUD stuffs

**Comment by michaelbromley** [comment]
Okay. You may also want to look at this issue: https://github.com/michaelbromley/angularUtils/issues/181 which discusses how you could implement such logic in your controller.
