### ISSUE TITLE
pagination-id not working with ids (strings)

### ISSUE THREAD

**Issue by vapits** [michaelbromley/angularUtils#228]
Hi there, i think there an issue here.

I'm having multiple instances of paginations in one app like this:

```` HTML
<div data-id="{{app._id}}" ng-repeat="app in dataApps track by app._id">
    <div dir-paginate="set in app.apis | itemsPerPage: 5" pagination-id="app.name">
    </div>
</div>
````

(the dom is simplified for this example)

So my problem is that in my pagination-id i had app.name and everything worked ok except if user have apps with the same name (that's possible).

So i try to change it to app.id
which is provide a STRING id like "26341ae0-56d9-11e5-8765-1230e89bf4e8"

Then everything stopes working and get errors like this:

````console
Error: [$parse:syntax] Syntax Error: Token 'ae0' is an unexpected token at column 6 of the expression [26771ae0-56d9-11e5-8090-8770e89bf4e8__currentPage] starting at [ae0-56d9-11e5-8090-8770e89bf4e8__currentPage].
http://errors.angularjs.org/1.3.18/$parse/syntax?p0=ae0&p1=is%20an%20unexpected%20token&p2=6&p3=26771ae0-56d9-11e5-8090-8770e89bf4e8__currentPage&p4=ae0-56d9-11e5-8090-8770e89bf4e8__currentPage

Pagination directive: the pagination controls (id: testapp) cannot be used without the corresponding pagination directive, which was not found at link time.
````

Any ideas?

**Comment by michaelbromley** [comment]
Hi,

I think the errors are caused by the hyphens in your id string. Variables in angular generally follow the syntax rules of JavaScript, and as such hyphens are not valid in a variable name. This came up a few times in the same context that you report, and I wrote a short article about it a while back if you want to read about the issue in further detail: http://www.michaelbromley.co.uk/blog/410/a-note-on-angular-expressions-and-javascript-identifiers

**Comment by vapits** [comment]
Ok i understand it.

So as data cannot changed.

Can i add a filter in pagination-id? like "app.id | filter"?

**Comment by michaelbromley** [comment]
I'm not totally sure - I've never tried that before. Try it and let me know. Also, I just noticed another thing which will give you problems - variable names cannot start with a number. Your filter will have to make sure the first character is not a number and remove all hyphens / convert to underscore for example.

**Comment by vapits** [comment]
Nope filter is not working.

Yeap you are right but still if i ad for example an "_" in front of my var nothing changes.

Hmmm i have to make it work if you find any solution please share it ;) if i do first i will also of course.

**Comment by vapits** [comment]
BTW hre's my filter:

````javascript
.filter('replaceDashes', function() {
        return function(input) {
            if(input) {
                return input.replace('-', '_');
            }
        }
    })
````

It seems to stop in the first dash. it replace the dash and not replacing the others.

**Comment by michaelbromley** [comment]
Try changing the return line of the filter to this:

```JavaScript
return "_" + input.replace(/-/g, '_');
```

**Comment by vapits** [comment]
Cool that helps a little bit. I get read the errors but pagination is not working still and i've got this console warning:

````console
Pagination directive: the pagination controls (id: testapp) cannot be used without the corresponding pagination directive, which was not found at link time.
````

**Comment by vapits** [comment]
I think it has to do that pagination directive is printed before filter returns result, that's the reason i'm getting this warning so i think filter is not an option.

**Comment by vapits** [comment]
Well it's very strange...

I cooperation with my backend colleague we create a new object named varId which provide a valide variable like: "_26771ae0_56d9_11e5_8090_8770e89bf4e8"

Still getting the warnings and no pagination. It works only with app.name, with nothing else.

**Comment by vapits** [comment]
Well the second solution worked sorry i wasn't change the pagination-id in pagination control.

Well i guess this issue is closed.

Thanks @michaelbromley

**Comment by michaelbromley** [comment]
Glad you got it sorted :+1:
