### ISSUE TITLE
Check Box Status Lost after navigating between pages

### ISSUE THREAD

**Issue by ghost** [michaelbromley/angularUtils#230]
I have a table populated using the dir-paginate directive. The table has two columns one with a string and other one is a checkbox.

Now the problem is , 
I select the checkbox in the current page , navigate to the next page and check some there. If I navigate to the firstpage again, previously selected checkboxes state got lost.

How can I fix this?

Thank You

-
Vinay Reddy

**Comment by michaelbromley** [comment]
Hi,

Managing state between pages is not something that this module takes care of. There should be a fairly simple solution to what you want to do, but without knowing anything about your implementation, I cannot tell you what that would be.

Show me the controller and view code that you are referring to, and I'll try to advise.

**Comment by agriboz** [comment]
I have the similar issue  with `ng-options`navigating between pages (that pagination creates).

http://plnkr.co/edit/0YoVkv2hR0uM6H5b4xIA?p=preview

**Comment by michaelbromley** [comment]
Hi @agriboz. I think you might just have some logic errors in your code. First of all, I don't think you need `ng-selected` with a select input if you are using `ng-options` - the fact you use `ng-model` should take care of selecting the right one.

Secondly, although I am not *sure* what you intend the behaviour to be, you are binding *all* the select boxes to the same object key. Try something like this:

```HTML
 <select ng-options="item.StudentNo as item.FirstName for item in enrollmentList"
                        ng-model="tableSelection['id_' + enrollment.StudentNo]"></select>
```

**Comment by agriboz** [comment]
@michaelbromley This approach worked quite well with `angular ui-bootstrap typehead` plugin also. Thanks for your help btw.

**Comment by michaelbromley** [comment]
Closing. Please re-open if this is still an issue.
