### ISSUE TITLE
dirPaginate: How do I get the data that is currently being displayed?

### ISSUE THREAD

**Issue by mattmccormick** [michaelbromley/angularUtils#232]
Hi there,

Thanks for the tool.  It's very useful.

How do I get the data that is currently being displayed?  I need to make an AJAX call to get additional data for items but to save requests, I'd like to do it only when the data is being displayed to the user (so I don't need to make requests for things that are never shown).

I'm confused as to how I go about getting the data that is currently shown.  I thought about just trying to calculate from the current page and numItems per page but I'm also using filtering so that changes things.

Thanks

**Comment by michaelbromley** [comment]
Hi,

If I understand you correctly, you can do that with an expression like this:

```HTML
<element dir-paginate="user in results = (posts | filter:search) | itemsPerPage:10"></element>
```

`results` will then contain the results on that page, including the filtering.

See https://github.com/michaelbromley/angularUtils/issues/95 for an alternative syntax too.

**Comment by mattmccormick** [comment]
Hi @michaelbromley Thanks for the response.

This will give me all the results from all pages.  So if there are 2 pages of 10 items each, results will contain 20 items.  I'm trying to get the results that are only displayed on the current page so just the first 10 results.  

Instead I need to include the itemsPerPage to get just the results displayed.

    <element dir-paginate="user in results = (posts | filter:search | itemsPerPage:10)"></element>

Thanks for the help!
