### ISSUE TITLE
dir-repeat itemsPerPage over object 

### ISSUE THREAD

**Issue by SNiels** [michaelbromley/angularUtils#235]
You can ng-repeat over objects. Ng-repeat will then iterate over every property of that object.
This is not possible with the dir-repeat itemsPerPage.

**Comment by michaelbromley** [comment]
Yes, I'm aware of this. I've got an idea how to fix it, just need to find some time. Will try for this week.

**Comment by michaelbromley** [comment]
This is now fixed in the latest release - see https://github.com/michaelbromley/angularUtils-pagination/releases/tag/v0.9.0
