### ISSUE TITLE
Aggregating results throws unexpected end of expression

### ISSUE THREAD

**Issue by rmckeel** [michaelbromley/angularUtils#238]
Hello,

  You have made a nice product!

  I am having an 'Unexpected end of expression: filtered = (data.recipes ...) error produced in the console when I try to get the aggregate of a set of filters.

Works:
```html
<div dir-paginate="recipe in data.recipes | itemsPerPage:pageSize" current-page="currentPage">
```
Doesn't work:
```html
<div dir-paginate="recipe in filtered = (data.recipes | itemsPerPage:pageSize)" current-page="currentPage">
```

Notice the only change is a ng-repeat legal ...filtered = (...) so that I can get the length of the filtered object elsewhere on the page.

Any thoughts on why this wouldn't work?

Thanks!

  Ryan

**Comment by michaelbromley** [comment]
Hi,

No obvious reason why this wouldn't work. Are you able to reproduce the error in a Plunker demo? Have you checked whether the expression (minus the itemsPerPage filter) works in ngRepeat? Checked versions of Angular & this module?

**Comment by rmckeel** [comment]
Michael, I may be able to make a Plunker demo later this week.  I have had similar issues in other products (https://github.com/simplicitylabs/si-table/issues/29), but I was not able to create a complete enough demo in a reasonable amount of time before settling for a second-best alternative (modifying the offending code).  The issue with si-table was that it was doing some additions to the ng-repeat line then some string manipulation; it didn't expect a parentheses in the code to evaluate, but it is still valid code.

I will report back when I have more info.  Thanks ~

**Comment by rmckeel** [comment]
Hey Michael,

  OK, I worked on a plnkr, and realized something important.  It works fine, as long as the variable does not wrap itemsPerPage.  This makes sense, because I don't want what is filtered AND what is visible on the page, but all the filtered items.

http://plnkr.co/edit/657rUnRHiGrhmpoUbQDx?p=preview

e.g.

```html
meal in filtered = (meals | filter:q) | itemsPerPage: pageSize
```

```html
meal in filtered = (meals | filter:q | itemsPerPage: pageSize)
```
Produces console error "Token 'undefined' is unexpected, expecting [)] at column null of the expression [filtered = (meals | filter:q] starting at [filtered = (meals | filter:q]."

Thus, my problem has gone away with the wrapped filtering I want excluding the itemsPerPage filter.

I'll close the ticket, as it seems unlikely anyone would want itemsPerPage included in a variable like that.

Thank you!

  Ryan
