### ISSUE TITLE
Resolving attributes on the same element as dir-paginate-start

### ISSUE THREAD

**Issue by jaireth** [michaelbromley/angularUtils#239]
In the example:
    &lt;tr dir-paginate-start="item in view.data.Items | itemsPerPage: view.data.PageSize" total-items="view.data.Total" current-page="view.data.Page" ng-class="{ unsucessful: !item.Successful }">

The angular code in the ng-class attribute doesn't get processed at all. This seems to work for anything I add, for example, adding:  data-test="{execution.Successful}" will just show what's literally there in the inspector.

**Comment by michaelbromley** [comment]
Hi there,

Check out this plunker: http://plnkr.co/edit/DdbDewLbEZb5i59kxXcd?p=preview

I am using `dir-paginate-start` and `-end` on a table and, as in your example above, I am usingthe value of the item to set the class via `ng-class`. It seems to work fine.

Perhaps you can put together a plunker to demonstrate the issue you are running into.

**Comment by michaelbromley** [comment]
Closing. Please re-open if this is still an issue.
