### ISSUE TITLE
dirPagination: multiple instances with ng-repeat broken

### ISSUE THREAD

**Issue by LeleDev** [michaelbromley/angularUtils#241]
After the last update (0.9.0), multiple instacens with ng-repeat seems to be broken and throw an error. Here is part of my code:

```
 <div ng-repeat="eventsCategory in eventsCtrl.eventsCategories">
      <tr dir-paginate="event in eventsCtrl.eventsData[eventsCategory.label].events | itemsPerPage:eventsCtrl.eventsPerPage" pagination-id="eventsCategory.label" total-items="eventsCtrl.eventsData[eventsCategory.label].totalEventsNum" current-page="eventsCtrl.eventsFilters[eventsCategory.label].pageNumber" ng-click="eventsCtrl.showEventDetails(event)">
   Sample Content
   </div>
</div>
```
I could set up a fiddle but I guess that the problem is easier to spot directly from the last release diffs in the code, since these changes are quite few

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. What is the exact error? A fiddle would be helpful - the main change is a pretty complex regex that is beyond my mental abilities to debug just by looking at a diff ;)

**Comment by LeleDev** [comment]
http://jsfiddle.net/2ZzZB/2342/

Before I need some help to make your directive work in a fiddle... (injections problems)

**Comment by jarvigames** [comment]
I have the same issue, the problem is that pagination Id attribute is not binded in dir-paginate directive, this one is taken statically 
```javascript
                 line:70 var rawId = tAttrs.paginationId || DEFAULT_ID;
```

**Comment by michaelbromley** [comment]
Thanks for the pointer. I won't have time to write a patch until later in the week.

**Comment by michaelbromley** [comment]
Okay, I've had time to look into this this morning. (Un)fortunately I cannot reproduce any error - it would really help to know what error your console gives, by the way.

To make a demo of the issue, try modifying the demo plunker (sorry I should have linked to this before) http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview

@jarvigames - the reason the id is not binded on that line is that this is the compile function, where we don't yet have access to a "scope" object with which to interpolate a value. A [few lines down from there, within the link function](https://github.com/michaelbromley/angularUtils/blob/de1ce3fbf249d351bb72d665a695f3126c81bcb0/src/directives/pagination/dirPagination.js#L77) you can see that we are now able to parse the literal string value of the pagination-id. 

I've just double checked this is working okay with a couple of new tests, and as far as I can tell it is working ok. Again, if you are able to reproduce the error in a way I can take a look at, I'll do so.

**Comment by LeleDev** [comment]
Here you go with the plunker:
http://plnkr.co/edit/PyseR8qCfUkkjuHG6zya?p=preview

If I use the following expression:
``` | itemsPerPage:eventsCtrl.eventsFilters.sharedTasksFilters.eventsPerPage```
It does break, if I use some other expressions, like:
``` | itemsPerPage:eventsCtrl.eventsPerPage```
It doesn't

**Comment by LeleDev** [comment]
I suspect that the regexp ```var filterPattern = /\|\s*itemsPerPage\s*:\s*(.*\(\s*\w*\)|([^\)]*?(?=as))|[^\)]*)/;`` instead of ```var filterPattern = /\|\s*itemsPerPage\s*:[^|\)]*/;``` messed up something for my specific field names

**Comment by michaelbromley** [comment]
@LeleDev Great, thanks for the plunker. Really weird issue. Hope to get some time tomorrow to fix.

**Comment by LeleDev** [comment]
Any news?

**Comment by michaelbromley** [comment]
Not yet. Hopefully later this week. Since I have to work on this stuff out of work hours, it can be difficult to find the time.

**Comment by LeleDev** [comment]
Ok! ;)

**Comment by michaelbromley** [comment]
Hi, you are totally correct that the regex was to blame. Specifically the part `(?=as)`, which is there to match the "alias" syntax, but was also matching the string "as" in the word "sharedTasksFilters".

The fix was simply to make sure there is a space around the "as" in the regex. Pushing a fix to master now, and if you use the bower/npm version, I'll probably do a patch release today or tomorrow (depending on how many of the other issues I manage to get fixed).

**Comment by LeleDev** [comment]
Great!!
