### ISSUE TITLE
[Noob] How can i get the value of "pagination.current" outside the directive scope

### ISSUE THREAD

**Issue by Abhith** [michaelbromley/angularUtils#242]
Hi, Is there anyway to get the value of "pagination.current" outside the directive scope. Since i wanted to display something like "Showing 1-10 of 20" in some where outside the scope. So to calculate the current displaying range, i have to know the value of "pagination.current" at least.

Everything else working great. Thanks :)

**Comment by michaelbromley** [comment]
Hi,

Sure, you can just use the `current-page` attribute on the `dir-pagination` directive and assign a scope variable which will reflect the value of `pagination.current`, but be available outside the directive. 

See the [docs for more info](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#dir-paginate).

**Comment by Abhith** [comment]
Thanks :+1:
