### ISSUE TITLE
angular-utils-pagination isn't handling data the same as ng-repeat

### ISSUE THREAD

**Issue by jondthompson** [michaelbromley/angularUtils#246]
The following two code snippets should result in the same data, but one is loaded prior to the state change and the other is loaded asynchronously. They're not.  ng-repeat works with both of them, but I switched to [angular-utils-pagination](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#installation), and the latter code works, but the former code does not.

However, I don't see a difference in the arrays that are being generated, and they work with ng-repeat.
I'm going to crosspost this issue to angular-utils-pagination and ui-router as well, as it's not handling the difference properly, as I'm not certain whether [uirouter](https://github.com/angular-ui/ui-router) or [restangular](https://github.com/mgonto/restangular/) is in error for giving the wrong information in the first place.

#### doesn't work with angular-utils-pagination
```javascript
.state( 'users', {
    url:'/users',
    controller: 'UsersCtrl',
    templateUrl: 'users/Users.tpl.html',
    data:{ pageTitle: 'Users' },
    authenticate: true,
    resolve: {
      users: ['Users', function(Users){
        return Users.getList({embed:'roles,user_certifications'});
      }]
    }
  })
.controller( 'UsersCtrl', function UsersController( $scope, users ) {
  $scope.users = users;
})
.factory('Users', function(Restangular){
  return Restangular.service('users');
})
;
```

#### works with angular-utils-pagination
```javascript
.state( 'users', {
    url:'/users',
    controller: 'UsersCtrl',
    templateUrl: 'users/Users.tpl.html',
    data:{ pageTitle: 'Users' },
    authenticate: true
  })
.controller( 'UsersCtrl', function UsersController( $scope, Users ) {
  Users.getList().then(function(result){
   $scope.users = result;
   });
})
.factory('Users', function(Restangular){
  return Restangular.service('users');
})
;
```

**Comment by jondthompson** [comment]
Here's the other two issues I created for this issue.
https://github.com/angular-ui/ui-router/issues/2308#issuecomment-147878147
https://github.com/mgonto/restangular/issues/1252

**Comment by michaelbromley** [comment]
Hi there,

Thanks for the code, makes the problem clear. What I am missing is what exactly you mean when you say that the pagination module doesn't work in the first instance. Does it throw an exception? Any output in the console? What do you see that is not what you expect?

Fill me in a bit more - best would be to reproduce the issue in Plunker - and I'll check it out.

**Comment by jondthompson** [comment]
It doesn't give an error, but doesn't show the list, despite ng-repeat working in the same instance. I'll write a plunker to reproduce.

**Comment by michaelbromley** [comment]
Okay. Also I just pushed some changes that *may* have something to do with your issue today. make sure you test against the latest version of dirPagination.js in the master branch.

**Comment by jondthompson** [comment]
It looks like your changes fixed my issue.

**Comment by jondthompson** [comment]
I would like to know what the changes were that caused this and why it was fixed, as I have another ticket in restangular because the two patterns return different data.

**Comment by michaelbromley** [comment]
You can see the diff of the change that may have solved your issue here: https://github.com/michaelbromley/angularUtils/commit/6944504cdc3ab52d89edcef5e955e4a57ca2133d

It has to do with using a `pagination-id` that resolves to a string containing a non-alphanumeric character such as a period or hyphen. This confuses Angular's $parse service which then means the directive cannot internally figure out the current page, which was causing it to display an empty list.
