### ISSUE TITLE
Problem downloading Meteor package

### ISSUE THREAD

**Issue by jbelmont** [michaelbromley/angularUtils#247]
{ build-a-recipe-maker } master » meteor.bat add angularutils:pagination
 => Errors while adding packages:

While checking for angularutils:pagination@0.9.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

I am getting this error when I try to add meteor package via Windows 7 operating system.
The package does not exist on my local meteor directory.

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. I'm looking into how to fix this. I don't know much about meteor - someone else set up the package stuff for me and I just type "meteor publish" every so often...

**Comment by jbelmont** [comment]
Okay I will wait till then.

**Comment by deltaag** [comment]
I am getting the same issue on Ubuntu 14.04, meteor 1.2.0.2, while trying:
meteor add angularutils:pagination

Thanks in advance!

**Comment by retroconduct** [comment]
I am also getting the same, happens with both versions 0.9.0 and 0.9.1

**Comment by spookmx** [comment]
I tried 0.9.0 and doesnt have a problem, if you use the latest version of the angular-meteor generator you will be able to add and use the package without problems.

Issue reported on the generator:
https://github.com/ndxbxrme/generator-angular-meteor/issues/22
