### ISSUE TITLE
Will search text works with asynchronous paging?

### ISSUE THREAD

**Issue by simkimsia** [michaelbromley/angularUtils#248]
I found your github via your blog

http://www.michaelbromley.co.uk/blog/108/paginate-almost-anything-in-angularjs

Your example allows search text.

<img width="801" alt="screen shot 2015-10-18 at 5 23 24 pm" src="https://cloud.githubusercontent.com/assets/245021/10563449/1b3672c2-75bd-11e5-8ed7-3b7969768f88.png">

You also provide a asynchronous server side paging example.

Is there a way to do search text using asynchronous server side paging?

**Comment by michaelbromley** [comment]
Sure, but the search would have to be implemented on the server side. Taking the [example async set up from the docs](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#working-with-asynchronous-data), you'd have to send the query string to the server with the request, e.g. as a GET parameter.
