### ISSUE TITLE
Tutorial http://angular-meteor.com/tutorials/angular1/search-sort-pagination-and-reactive-vars angularutils:pagination doesn't work

### ISSUE THREAD

**Issue by varelad** [michaelbromley/angularUtils#249]
$meteor add angularutils:pagination

While checking for angularutils:pagination@0.9.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

OS. Mac 10.11

If someone can help me.

**Comment by michaelbromley** [comment]
Duplicate of https://github.com/michaelbromley/angularUtils/issues/247
