### ISSUE TITLE
Pagination for multi-column thumbnails in photo gallery?

### ISSUE THREAD

**Issue by porwig** [michaelbromley/angularUtils#251]
Hi Michael,

Thanks for sharing your code, and your knowledge! I am new to AngularJS (apologies if this is a newbie question) - would your solution for pagination work for an image gallery, with each url having a main image, and also multiple columns of thumbnails that each link to a different url? The url at the end of this post is essentially what I want to create in AngularJS, but I also want to add pagination for the thumbnails (so I don't end up with a sidebar with lots and lots of rows when more images get added to an image gallery: http://nearmiddlefar.com/galleries/birds/american-kestrel-1.html

**Comment by michaelbromley** [comment]
Hi,

Should be fine. The content of the pagination is not important (whether image, text, or something else). If it can be represented as a list of things (as is certainly the case in your example), then it will work.

I suggest you just give it a go and let me know if you run into any problems you can't fix for yourself by reading the docs.

**Comment by porwig** [comment]
Great, thanks Michael - I will do as you suggest!

**Comment by michaelbromley** [comment]
Ok! I'll close this issue now, but feel free to re-open if you need further assistance.
