### ISSUE TITLE
itemsPerPage in dir-paginate

### ISSUE THREAD

**Issue by hervethouzard** [michaelbromley/angularUtils#254]
Hello,

Whne using something like this:
<tr dir-paginate="week in weeks | itemsPerPage: 25">

Is there a way to change 25 with a variable?

Bye,
Hervé

**Comment by michaelbromley** [comment]
Hi,

Is something missing there? I don't understand the question.

**Comment by hervethouzard** [comment]
In your readme / documentation, the value of itemsPerPage is supposed to be a value or an expression, I tried with an expression, aglobal JS var and a value from $scope but none of them runs.

**Comment by hervethouzard** [comment]
Sorry I just saw that the code is missing...
I was talking about this:
`<tr dir-paginate="week in weeks | itemsPerPage: 25">`
I can't change 25 to a  JS var of a var in my scope.

**Comment by michaelbromley** [comment]
Ah okay. If you look at the [demo plunker](http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview), the itemsPerPage is specified by a scope variable and it works fine:

```HTML
 <li dir-paginate="meal in meals | filter:q | itemsPerPage: pageSize" current-page="currentPage">{{ meal }}</li>
```

Therefore something must be wrong with your implementation - perhaps the directive is not in the scope you think it is? If you can't figure it out, then post your view & controller code and I'll take a look.

**Comment by hervethouzard** [comment]
Hello,

That's ok, can't figure out what happened but it's running.
Sorry for the disturb.
