### ISSUE TITLE
$last and $index in pagination

### ISSUE THREAD

**Issue by hervethouzard** [michaelbromley/angularUtils#255]
Hello,

When using dir-paginate, $index and $last are related to current page, is there a way o get the original values ?

bye
Hervé

**Comment by michaelbromley** [comment]
There is no built-in method, but it is pretty simple to calculate based on the current page, and the number of items per page.

For example, the following methods might give you an idea how it could be done: 

```JavaScript
$scope.myIndex = function($index) {
  return $scope.itemsPerPage * ($scope.currentPage - 1) + $index;
}

$scope.myLast = function(item) {
  return item === $scope.collection[$scope.collection.length -1];
}
```

**Comment by hervethouzard** [comment]
Thanks a lot
