### ISSUE TITLE
dirPagination: Go back to first page on changing filter

### ISSUE THREAD

**Issue by abennouna12** [michaelbromley/angularUtils#257]
Hi,

I have an issue, when I search for something using filters, they current page remain the same.

Example if I search on something, there is 200 rows resulting, when I go to the page 8 and I add another thing on my filter, it remains on the page 8 instead of going to the page 1

**Comment by michaelbromley** [comment]
If you want it to go to page 1, you could just add some logic to your filter input that tells it to reset the `current-page` value back to 1 when it is changed. Example:

```HTML
<input type="text" ng-model="q" ng-change="currentPage = 1" />

<ul>
  <li dir-paginate="item in collection | filter: q | itemsPerPage: 10" current-page="currentPage">...</li>
</ul>
```

**Comment by michaelbromley** [comment]
Closing. Please re-open if this is still an issue.

**Comment by Geek2016** [comment]
i have the same issue pls help helpe po

**Comment by Geek2016** [comment]
help me plssssssssssss
