### ISSUE TITLE
not able to use the pageNumber in the view.

### ISSUE THREAD

**Issue by arasub** [michaelbromley/angularUtils#262]
Hi,
  We want to display the serial number on the pagination. so we want to use pageNumber to get the serial number of the item on the grid. if we use $index+1 for every page serial number will start from 1. instead i want to show the running serial-number by multiplying the page number with the index. below with my view code.

<tr>
<th ng-click="sort('id')">S.No<span class="glyphicon sort-icon" ng-show="sortKey=='id'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span></th>
<th ng-click="sort('Name')">Category Name<span class="glyphicon sort-icon" ng-show="sortKey=='first_name'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span></th>
</tr>
<tr dir-paginate="cate in category|filter:search|itemsPerPage:3 ">						
	<td><% (pageNumber * $index)+1 %> </td>
       <td><% cate.name %></td>
</tr>

thanks
arasub

**Comment by michaelbromley** [comment]
Hi. I don't see a question here. What is the issue exactly?

**Comment by arasub** [comment]
Hi,

 issue in the above is pageNumber  always undefined.
thanks
arasu.b

**Comment by michaelbromley** [comment]
Okay. Can you show me the rest of the view code where you define the `dir-paginate` directive? Also, what is that template syntax?

**Comment by arasub** [comment]
here with my dir-paginate and controls
```
<tr dir-paginate="cate in category|filter:search|itemsPerPage:3 ">						
	<td><% (pageNumber * $index)+1 %> </td>
       <td><% cate.name %></td>
</tr>


 <dir-pagination-controls max-size="3" direction-links="true" boundary-links="true" > </dir-pagination-controls>

```

**Comment by michaelbromley** [comment]
Thanks. You need to bind to the `pageNumber` scope variable like this:

```HTML
<tr dir-paginate="cate in category|filter:search|itemsPerPage:3 " current-page="pageNumber">
```

**Comment by arasub** [comment]
thanks michaelbromley. It worked.

**Comment by vinothrbt** [comment]
hi,

issue is in my pagination the first 1 2 3 pages showing when i click no. 3 its not showing next no. 4 th page.
