### ISSUE TITLE
filter:notarray error

### ISSUE THREAD

**Issue by arasub** [michaelbromley/angularUtils#263]
Hi Michael,

I'm stuck with the below error, not sure what's root cause of the below. Am i missing some thing on invoking pagination ?
```
<tr dir-paginate="cate in category|filter:search|itemsPerPage:3 " current-page="pageNumber">
```
Error: [filter:notarray] Expected array but received: {}
http://errors.angularjs.org/1.4.7/filter/notarray?p0=%7B%7D

Thanks
arasu.b

**Comment by michaelbromley** [comment]
Hi,

I am guessing that `category` is not an array. The `filter` filter can only be used with arrays. This is clearly explained in the AngularJS docs that you link to above.

**Comment by arasub** [comment]
yup thanks.
