### ISSUE TITLE
dirPaginate: disappears after a second controller is opened and then closed

### ISSUE THREAD

**Issue by cmlee1220** [michaelbromley/angularUtils#265]
Excellent directive with thorough instructions! It's very well done! 

I am a noobie in AngularJS, so I was very grateful to find your pagination directive.  One question though: the pagination that is on the background page disappears after I open a second or third modal window. Do you suggest using the page handler in the other controllers like one of the earlier comments? (By Brett McNamara e.g. scope.onPageChange({ newPageNumber: num, range: scope.range });) I hesitate because it's not really changing since it's only in the background, and I don't think the range applies to my case. Any suggestions would be much appreciated!

**Comment by michaelbromley** [comment]
Hi,

Thanks - glad you like the module so far. 

Not knowing how your code is put together, it's very hard for me to advise. If the pagination disappears, this suggests that perhaps the collection is being somehow emptied when a modal window opens.

Could it be that you are sharing the reference to the collection and then changing it's contents somehow?

If you could post a demo or the relevant parts of your view/controller, I'll check it out.

**Comment by cmlee1220** [comment]
Thanks for the prompt response!
I created a Plnkr , though I couldn't get the ng-repeat, in this case dir-paginate, to work.  In any case, you can see the structure of my code and the two modals that I have set up in the different controllers.  The pagination stays on the background, but after opening the second modal, it disappears.

http://plnkr.co/edit/i3vZFKLAshRltUUB7VTO?p=preview

Thanks again for your time and help.

**Comment by michaelbromley** [comment]
Hi,

Sorry for the lack of response. Not had a lot of time to deal with issues for a while. Is this still something that needs resolving for you?

**Comment by cmlee1220** [comment]
Hi Michael,

Thanks for following up.  Yes, I was able to fix it and it's working wonderfully.

Cris
