### ISSUE TITLE
ng-if not working correctly when inserted into element with dir-paginate

### ISSUE THREAD

**Issue by DoGi114** [michaelbromley/angularUtils#266]
```
<tr dir-paginate="workingTimes in listOfWorkingTimes | orderBy: 'date' | itemsPerPage: 5" ng-if="workingTimes.date > today">
                <td>{{ workingTimes.date}}</td>
                <td>{{ workingTimes.from | date: "HH:mm"}}</td>
                <td>{{ workingTimes.to |  date: "HH:mm"}}</td>
                <td ng-if="workingTimes.how_much_to_work.hours < 12 && workingTimes.how_much_to_work.minutes < 10">0{{ workingTimes.how_much_to_work.hours }}:0{{workingTimes.how_much_to_work.minutes}}</td>
                <td ng-if="workingTimes.how_much_to_work.hours < 12 && workingTimes.how_much_to_work.minutes >= 10">0{{ workingTimes.how_much_to_work.hours }}:{{workingTimes.how_much_to_work.minutes}}</td>
                <td ng-if="workingTimes.how_much_to_work.hours >= 12 && workingTimes.how_much_to_work.minutes >= 10">{{ workingTimes.how_much_to_work.hours }}:{{workingTimes.how_much_to_work.minutes}}</td>
                <td ng-if="workingTimes.how_much_to_work.hours >= 12 && workingTimes.how_much_to_work.minutes < 10">{{ workingTimes.how_much_to_work.hours }}:0{{workingTimes.how_much_to_work.minutes}}</td>
                <td><span ng-repeat="position in workingTimes.positions">{{position.name}}</span></td>
                <td><a ui-sref="editHoW({id: workingTimes.id})" class="btn btn-small btn-warning">Edit</a></td>
                <td><a ng-click="workingTime.deleteWorkingTime(workingTimes)" class="btn btn-small btn-danger">Delete</a></td>
</tr>
```
Or maybe im doing it wrong?

**Comment by michaelbromley** [comment]
Hi,

Could you clarify what you mean by "not working correctly"? What do you expect to happen, and what actually happens?

Also, what type of values you are using in `workingTimes.date` and `today`?

**Comment by DoGi114** [comment]
today and workingTimes.date are the same type, it was working with ng-repeat.
I expect it not to write elements which has date before today date.
instead it is not writing anything on screen

**Comment by michaelbromley** [comment]
Okay. I'll probably have time to investigate tomorrow.

**Comment by DoGi114** [comment]
I know why this is happening, just dont know how to prevent it,
inside of ng-if it cant see workerTimes variable so it cant get date out of it, couse its undefined.

**Comment by michaelbromley** [comment]
Hi,
Just had a bit of time to look into this. Yes, putting `1 , 2` or even just `true` into the ng-if will work. That's because as you say, it seems like the ng-if does not have access to the created `workingTimes` variable.

I'm not sure exactly what is going on here, but unfortunately I cannot spend a lot of time on this now. I will get round to it.

As a work-around (or possibly even a better solution altogether) could you not create a custom filter and add this to the dir-paginate expression?

**Comment by DoGi114** [comment]
Good idea, did not think about it, thanks

**Comment by chrillewoodz** [comment]
Adding a custom filter doesn't work either because the item variable isn't set yet.. Like you said.

**Comment by michaelbromley** [comment]
@chrillewoodz As far as I know a custom filter *should* work - you only need access to the collection `listOfWorkingTimes` and then filter out the ones you don't need before passing it to the `paginate` filter.

If this does not work for you, please post the code you tried and I'll take a loot.

**Comment by DoGi114** [comment]
And it is working. Just to make it clear ;)

**Comment by michaelbromley** [comment]
@DoGi114 Good to hear :+1:  I'll close this issue now since the filter approach is probably the better way to do this.
