### ISSUE TITLE
Keep selected page to return to state

### ISSUE THREAD

**Issue by ruizalvaro** [michaelbromley/angularUtils#270]
I want to keep the page clicked after go other state and back. How can i do that?

http://plnkr.co/edit/ZdrAEjOnCwPfMFvHBuMa
Click on page 3, click that item, an go back keeping page 3

Thanks a lot

**Comment by michaelbromley** [comment]
Hi,

This is not something specific to this module - it's just a case of storing the state somehow. I've implemented a solution for this which involves updating the `$location.search()` value to store the page in the URL. This can be done in the `on-page-change` callback. Then, when the controller containing the pagination loads again, read the value of current page from the URL and set the `current-page` value to this.

**Comment by ruizalvaro** [comment]
Can you tell me where is that implemented solution ? Thanks

**Comment by michaelbromley** [comment]
Hi, the implementation is not anywhere public - just within private projects I have worked on. You'll have to figure it out for yourself, but here is a rough idea of what your controller might look like: 

```JavaScript
// controller

$scope.currentPage = $location.search().page || 1;

$scope.pageChange = function(newPageNumber) {
  $location.search('page', newPageNumber);
}
```

```HTML
<dir-pagination-controls on-page-change="pageChange(newPageNumber)" />
```
