### ISSUE TITLE
Responsive Pagination

### ISSUE THREAD

**Issue by hebert-nr** [michaelbromley/angularUtils#271]
Looking at the UI Bootstrap, there's a way to resize the pagination using "max-size" and I don't see anything like this in your code.

I've played with a few things and have even been able to get the number of results per page to change, but the paging remains the same.

Is there a simple way of resizing the pagination based on the width of the window?

As an example: http://demo.sodhanalibrary.com/angular-bootstrap/responsive-pagination.html

Or even: https://codyhouse.co/demo/pagination/index.html#0

Otherwise, I am very happy to have this simple util available for use. Thank you!

**Comment by michaelbromley** [comment]
Hi,

No, this module does not include such functionality. However, you could implement this yourself without too much trouble I think. I've never done anything like this but perhaps it will work:

You can use the [`max-size`](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#dir-pagination-controls) attribute to set how many pages to display. In your controller you can query the width of the viewport and then use some algorithm to decide how many pages should be displayed at a given width, and update the value of `max-size` accordingly.
