### ISSUE TITLE
Synchronous XMLHttpRequest error on executing paginationTemplateProver.setPath()

### ISSUE THREAD

**Issue by adamcee** [michaelbromley/angularUtils#272]
I have gotten the pagination directive working, however when setting the template in a .config() of my main app module as directed, I received the following errors in the console: 
````
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

WARNING: Tried to load angular more than once.
````

The pagination controls are not subsequently loaded.

From looking at the code, I think that the $get() call in the setPath function is the reason why - maybe it needs to be updated to make an asynch request.

Please let me know what other information I can provide, or if I am doing something wrong. Thank you.

**Comment by michaelbromley** [comment]
Hi,

Can you show me how you set the path in your config block? The `$get` method is just a standard pattern used by all Angular providers, so I don't think that would be the issue.

**Comment by adamcee** [comment]
Sorry for delay on this. Will try to show code soon. I followed the example from the README pretty directly. Sounds like I confused the `$get` for a JQuery `$get` -- my mistake.

**Comment by michaelbromley** [comment]
Closing. Please re-open if this is still an issue.
