### ISSUE TITLE
uiBreadcrumbs: Resolve property not working with nested named view

### ISSUE THREAD

**Issue by moniuch** [michaelbromley/angularUtils#273]
Hi,
I gave a try to uiBreadcrumbs as I was after automated breadcrumbs from detail page, which I could not achieve with other modules.
It worked but not right away.
I had the following state setup:

```javascript
                    .state('company.ourstaff', {
                        url: "/our-staff",
                        views: {
                            'content@root': {
                                templateUrl: 'modules/company/staff/staff.html',
                                controller: 'StaffController',
                                controllerAs: 'staff',
                                resolve: {
                                    people: function(StaffService){
                                        return StaffService.getStaff()
                                    }
                                }
                            }
                        },
                        data: {
                            displayName: 'Our Staff'
                        }
                    })
                        .state('company.ourstaff.detail', {
                            url: "/:personId",
                            views: {
                                'detail': {
                                    templateUrl: 'modules/company/staff/staff.detail.html',
                                    controller: 'StaffDetailController',
                                    controllerAs: 'staffdetail',
                                    resolve: {
                                        currentPerson: function(StaffService, $stateParams){
                                            return StaffService.getPerson($stateParams.personId * 1);
                                        }
                                    }
                                }
                            },
                            data: {
                                displayName: '{{ currentPerson.name }}'
                            },
                        });
```

What I had to do was promote the `resolve` property by two levels (so that it lined up with `data`) to match your example.

While I'm glad it works, I'm sort of concerned whether this is not a sign of something bad going on in my code which will break down as my app grows - usually the `resolve` property is put next to `controller` and `templateUrl`.

**Comment by michaelbromley** [comment]
Hi,

thanks for the report. I see what you mean. I guess it could be an issue if a single state has multiple named views, each of which have their own resolves. 

I've not got time to work on this at the moment, but I will leave this issue open as an enhancement and either myself or some generous person with some free time can work on it.

**Comment by hornetnz** [comment]
As a further example, my states views do each have their own resolve...so I don't think I'm able to promote the resolves up to the data level to make this work. Any chance you'd be able to help get this working soon?

`.state(Constants.SEARCH_CONTACTS_CONTACTPROFILE, {
            url: '/orgs/:externalOrgId/contacts/:profileId',
            data: {
                displayName: '{{ cpc.contactProfile.lastName }}'
            },
            views: {
                '': {
                    templateUrl: 'app/contacts/contact-profile.tmpl.html',
                    controller: 'ContactsProfileController',
                    controllerAs: 'cpc',
                    resolve: {
                        contactProfile: function (contactProfileService: IContactProfileService, $stateParams: any) {
                            return contactProfileService.getContactProfile(<string>$stateParams.externalOrgId, <string>$stateParams.profileId)
                                .then(function (contactModel: IContact) {
                                    return contactModel;
                                });
                        }
                    }
                },
                'address@search.contacts.contactProfile': {
                    templateUrl: 'app/components/address/address.tmpl.html',
                    // This is a fragile way to assign the address, but the only thing that's worked until we can investigate better alternatives
                    controller: function ($scope: any, addressService: IAddressService) {
                        $scope.addressData = $scope.$parent.cpc.contactProfile.address;
                        $scope.googleMapUrl = addressService.getGoogleMapURL($scope.addressData);
                    }
                },
                'notes@search.contacts.contactProfile': {
                    templateUrl: 'app/components/notes/notes.tmpl.html',
                    controller: 'NotesController',
                    controllerAs: 'nc',
                    resolve: {
                        notesInfo: function ($timeout: ng.ITimeoutService, $stateParams: any) {
                            return $timeout(function () {
                                return {type: Constants.NOTES_TYPE_CONTACT, profileId: <string>$stateParams.profileId};
                            }, 10);
                        }
                    }
                }
            }
        })`

**Comment by michaelbromley** [comment]
Hi,

I'm afraid I no longer use this directive in any of my live projects, so I have little incentive to keep it up to date. I just added a note to the readme to this effect.

What this means is that it is very unlikely that I will find the time to debug and fix this issue. Sorry to have to say it, but I think you will appreciate an honest answer.

If this is a critical issue for you or your business, and you decide to invest the time to debug and fix, then I will welcome a pull request to this repo.
