### ISSUE TITLE
Asynchronous Data Loop on last page

### ISSUE THREAD

**Issue by LeoCreer** [michaelbromley/angularUtils#275]
I have a issue where i request last page 4,056 items in 100 items per page on the last page 46 if clicked the page will show additional pages  47 48 49 ....  when clicking any of these pages 47 48 49 it will take you back to page 1.

How do I stop this from happening?

**Comment by michaelbromley** [comment]
Hi,

can you show me the relevant code, or event better make a demo on plunker showing the issue?

**Comment by michaelbromley** [comment]
Closing. Please re-open if this is still an issue.
