### ISSUE TITLE
sort items based on value of a field of json object. 

### ISSUE THREAD

**Issue by devarajphukan** [michaelbromley/angularUtils#277]
Here, my pList is a list of objects, where I have a field "price", which is a number. I want to sort my results based on that. I have tried orderBy : 'price' : reverse. But that results in showing only one result and angular brackets also shows up in my page in the browser. 

```HTML
<div dir-paginate="obj in pList | itemsPerPage:10 ">	
					

                        <div class="image">
						<a href="#propertyDetail?propid={{obj._id}}">
							<span class="btn btn-default"><i class="fa fa-file-o"></i>{{obj.title}}</span>
						</a>
						 <img src="../images/detail-img1.jpg" alt="" />
					</div>
					<div class="price">
						<i class="fa fa-home"></i>For {{obj.type}}
						<span>{{obj.price}}</span>
					</div>
					<div class="info">
						<h3>
							<a href="#propertyDetail?propid={{obj._id}}" >Luxury Apartment with great views</a>
							<small>{{obj.location}}</small>
						</h3>
						
						

					</div>
				</div>
```

**Comment by michaelbromley** [comment]
Hi,

Sorry about the delay in answering. If this is still an issue, could you reproduce it in a plunker? It will make it easier for me to help you out. You can use this as a start: http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview

**Comment by michaelbromley** [comment]
Closing. Please re-open if this is still an issue.
