### ISSUE TITLE
How can i get the value of "range.total" outside the directive scope

### ISSUE THREAD

**Issue by ruisilva450** [michaelbromley/angularUtils#283]
Hi, I wanted to get access to this variable outside the directive scope to show something like "Filtered results: {{range.total}}" on my controller.

Any easy way of doing this?

Thanks!

**Comment by michaelbromley** [comment]
`range.total` is equal to the number of items in the collection, after any filters have been applied which might modify it.

You can get access to this number from your controller by writing the expression like this:

```HTML
<li dir-paginate="item in filteredItems = (collection | filter: q) | itemsPerPage: pageSize">..</li>

total = {{ filteredItems }}
```

**Comment by ruisilva450** [comment]
Thank you. Exactly what I need
