### ISSUE TITLE
Stuck at bottom of page when navigating to a new page

### ISSUE THREAD

**Issue by chaiyitsheng** [michaelbromley/angularUtils#284]
If I have dir-paginate control at the bottom of the page, is there anyway to show the top of the page each time I navigate to a new page? 

Thanks

**Comment by michaelbromley** [comment]
Hi, this is answered here: https://github.com/michaelbromley/angularUtils/issues/142

**Comment by chaiyitsheng** [comment]
Dear Michael,

Thanks very much....appreciate your help :)

On Mon, Jan 18, 2016 at 4:11 AM, Michael Bromley <notifications@github.com>
wrote:

> Hi, this is answered here: #142
> <https://github.com/michaelbromley/angularUtils/issues/142>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michaelbromley/angularUtils/issues/284#issuecomment-172376110>
> .
>



-- 
*Chai Yit Sheng*
Director
RISC*Micro* Sdn Bhd
*Tel: 012-2193911*
