### ISSUE TITLE
It isn't possible to access the filtered items within the view

### ISSUE THREAD

**Issue by alexdrans** [michaelbromley/angularUtils#285]
Attempting to use the same method as ng-repeat to access the filtered list within the scope of the view fails i.e.

`dir-paginate="item in filteredList = (list | filter1 | filter 2 | orderBy | itemsPerPage)`

`{{item}}` fails to find the item in the scope.

**Comment by michaelbromley** [comment]
Try putting the `itemsPerPage` filter *outside* the parentheses. Let me know if that helps.

**Comment by alexdrans** [comment]
That worked, thank you! Should this be added to the documentation?

**Comment by michaelbromley** [comment]
Good. There is actually already a section addressing this issue in the FAQ: https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#why-does-my-sort--filter-only-affect-the-current-page
