### ISSUE TITLE
pagination and max-size

### ISSUE THREAD

**Issue by PhilFlash** [michaelbromley/angularUtils#287]
Hi,
If I change the value of max-size (in dir-pagination-controls), the number of pagination links to display is not updated.
IMHO, the variable "paginationRange" is not updated in dirPaginationControlsLinkFn function.
In my case, I have replaced (in 2 functions : goToPage and generatePagination)
```javascript
scope.pages = generatePagesArray(num, paginationService.getCollectionLength(paginationId), paginationService.getItemsPerPage(paginationId), paginationRange);
}
```
by
}
```
scope.pages = generatePagesArray(num, paginationService.getCollectionLength(paginationId), paginationService.getItemsPerPage(paginationId), Math.max(scope.maxSize, 5));
}
```
and all is ok for me. But I am not sure that this patch is ok for all cases.

Philippe

**Comment by michaelbromley** [comment]
Hi. Thanks for the report. I'll check it out and write a test case for it and check whether your proposed fix is okay with the existing tests.

**Comment by michaelbromley** [comment]
Fixed now! Your suggestion was basically sound, but I just needed to add a watcher so that changes to maxSize get immediately propagated to the page links.
