### ISSUE TITLE
programmatically set Pagination

### ISSUE THREAD

**Issue by dk31791** [michaelbromley/angularUtils#288]
Hello,

i want to set pagination in dirpagination programmatically.

my page contains two grid and i had already used 

```
<dir-pagination-controls pagination-id="cust"></dir-pagination-controls>
```

to provide different ids.

my pagination is working correctly but when i try to go to some other page by calling gotoPage function using my program both grid pagination are redirecting to that particular page.

please provide valid method to set pagination programmatically.

thanks

**Comment by michaelbromley** [comment]
Hi,
This should work as long as there is a valid scope value for "cust". If not, the directive will interpret it as a string literal and they will both  have id "cust". Could you show me a bit more controller & view code?

**Comment by michaelbromley** [comment]
Closing. Please re-open if this is still an issue and provide more information as requested above.
