### ISSUE TITLE
Breadcrumb only ever shows the current page

### ISSUE THREAD

**Issue by dhintze** [michaelbromley/angularUtils#291]
I'm using angular 1.3.16, ui-router 0.2.13, and angular-utils-ui-breadcrumbs 0.2.2. I've followed the getting started steps. The breadcrumb only ever shows the current page. When debugging, the breadcrumbs are always empty. I'm changing states with both $state.go and ui-sref, neither seem to update the breadcrumb array.

Feel like I'm missing something simple here... would love to use this!

**Comment by michaelbromley** [comment]
Hi,

Sorry about the long wait. To be honest I am no longer using this module in any current projects, so have not been keeping it up to date with the new released of the libraries - and have no intention to do so (sorry - just a matter of needing to prioritize my limited free time).

Having said that, I will leave this open in the case that someone else may have time to look into it.
