### ISSUE TITLE
Setting max-size to less than 5

### ISSUE THREAD

**Issue by amrinder23** [michaelbromley/angularUtils#292]
Hi Michael,

If i need to set max-size to less than 5 what changes do i need to make in the directive itself to show the page links properly?

Regards
Amrinder

**Comment by michaelbromley** [comment]
Hi,

You'd have to modify [this line](https://github.com/michaelbromley/angularUtils/blob/a5e1a86f9bfb8847b3ab986da966668732ebe135/src/directives/pagination/dirPagination.js#L251). I can't guarantee that you'll get sensible results with a lower value than 5 though. What is your use-case?
