### ISSUE TITLE
dirPagination: problem injecting the Module

### ISSUE THREAD

**Issue by rhsu0268** [michaelbromley/angularUtils#293]
Hi, I'm having toruble injecting the module into my angular application. 

Is angularUtils.directives.dirPagination the name?

Thanks!

**Comment by michaelbromley** [comment]
Hi,

Yes, that is the correct name. It would help if you provided any error message and also the code where you declare the module.

**Comment by rhsu0268** [comment]
Hi Michael, 

Thanks for reaching out. I'm doing this in a node.js application. And following your instructions with npm install angular-utils-pagination. 

And then when I did: angular.module('myApp', ['angularUtils.directives.dirPagination']);

I am getting an injector error. 

I also tried to link to the files directly but that doesn't seem to be helping either. Any suggestions here?

**Comment by michaelbromley** [comment]
Are you including the `dirPagination.js` file in your app? And how do you use this in a node app? I've not heard of that before.

**Comment by rhsu0268** [comment]
Yes, that's correct. I did include dirPagination.js with simple script tags. But your basic example isn't working for me.

**Comment by capc** [comment]
I got the same problem too
![screenshot from 2016-02-26 04 32 16](https://cloud.githubusercontent.com/assets/9016203/13341636/2d23ffda-dc43-11e5-99a5-0313fcfc23cc.png) i only use one controller

**Comment by michaelbromley** [comment]
@capc That is not enough for me to go off. It looks from that error like you might have an error finding a module named "academian". 

@rhsu0268 I cannot do anything on this without seeing some more code and context of how this is used in a node app. Can you paste the exact error?

**Comment by rhsu0268** [comment]
Hi Michael, 

Thanks for getting back to me. I was able to get the sample code from plank to work with my project. 

**@capc**: I think a good approach is to take Michael's sample code from plank as a starting point. If you can get his example to work, then adapt it to fit whatever data you need to display in your project.

**Comment by michaelbromley** [comment]
@rhsu0268 Good to hear. I'll close this issue now.

**Comment by capc** [comment]
@rhsu0268 Thanks man! It worked..

**Comment by capc** [comment]
@michaelbromley With this plugin, is it possible to have 2 paginations on the same page?? I tried but it seems both paginations got synchronized somehow.
