### ISSUE TITLE
Current Page Not Resetting

### ISSUE THREAD

**Issue by ewaschen** [michaelbromley/angularUtils#294]
Hi, When I do a search and load the data, I click to a different page, everything is working fine but when I do a new search the page does not go back to 1.  In my code I have 
`current-page="currentPage"` and when I do a new search I set `$scope.currentPage=1`.  This doesn't reset the page.  I looked into the scope and found 
![cp](https://cloud.githubusercontent.com/assets/9055167/13028535/b7c380ce-d23f-11e5-947c-1a7d4ea29fbb.png).  It seems the pagination is reading from pagination.current and not from my variable even though I defined it in the html.

Thanks

**Comment by michaelbromley** [comment]
Hi,

What you describe *should* work. Can you show me your controller code so I can see if anything is amiss there?

**Comment by ewaschen** [comment]
Hi, controller code is large but here is the important stuff

```
angular.module('gaegenericapp')
  .controller('TrainingCtrl', ['$rootScope','$scope','$location','$window','$filter','$routeParams','$http','$popover','KeywordService','CoursesService','CoursesSearch','UserSearchQueryService',
      function ($rootScope,$scope,$location,$window,$filter,$routeParams,$http,$popover,KeywordService,CoursesService,CoursesSearch,UserSearchQueryService) {
	$scope.signOnURL = "";
	$scope.skillsoftList = [];
	$scope.typesList = [];
	$scope.showSkillSoftResultLength = false;
	$scope.currentPage = 1;
	$scope.pageSize = 15;
	$scope.totalResults = 0;
```

```
function runSearch(url, searchType){
		$scope.skillsoftList = []; // Reset Results
		$http.post(url,{}).then(function(skillsoftSearchResult){
                      if(...){...}
                      else{
                      ...
                                   if(searchType != "Pagination"){
						$scope.showSkillSoftPage = true;
						$scope.basicSearch = false;
						$scope.currentPage = 1;
					}
                      }
```

So right when the controller opens I set currentPage then in my http request I set the current page again if the search Type is not pagination (search button was clicked).  I'll try the update your source code and see if that helps

**Comment by michaelbromley** [comment]
Does the value of `$scope.currentPage` get updated to 1 after the http call? Can you show me the relevant view code?

**Comment by baodinh** [comment]
Hi, 
Is it right for your idea ?
https://plnkr.co/edit/reQUcExQsjlzG0Rbi2Bd?p=preview

**Comment by michaelbromley** [comment]
@baodinh Yes, that is what I had in mind.

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, feel free to re-open.
