### ISSUE TITLE
save pagination state between route pages

### ISSUE THREAD

**Issue by misherone** [michaelbromley/angularUtils#295]
Hi. First, let me thank you for your awsome work.
Maybe I'm missing something obvioius.
I want to save pagination state (current page and page size) when I pass to another route page (e.g. detail of some element from pagination items list).
Currently I solve this using a factory:
```
app.factory("$paginationSettings", function () {
  return {
    currentPage: 1,
    pageSize: 7
  };
});
```
then i inject it to the controller and update service vars in `pageChangeHandle`:
```
app.controller('pits', ['$scope', '$paginationSettings', function ($scope, $paginationSettings) {
  $scope.currentPage = $paginationSettings.currentPage || 1;
  $scope.pageSize = $paginationSettings.pageSize || 5;
// some code
$scope.pageChangeHandler = function (num) {
    $paginationSettings.currentPage = num;
    $paginationSettings.pageSize = $scope.pageSize;
  };
}]);
```
Is there any better solution for that?

**Comment by michaelbromley** [comment]
Hi,

The module itself has no opinion about how to manage app state - so you could use any method. The one you show above is perfectly valid, but here is another way you could do it:

**Persist the pagination state to the URL** via `$location.search()`. E.g. in the `pageChangeHandler`, you do something like:

```JavaScript
$location.search({
  p: num,
  size: $scope.pageSize
});
```

which will give you a URL like `localhost/myApp/myView?p=3&size=25`. Then when you load that controller again, you read those values back into you scope. 

This has the advantage of making your paginated list bookmark-able, and it is also a very usual way to do things, not just in the Angular world.
