### ISSUE TITLE
Pagination won't work across tabs

### ISSUE THREAD

**Issue by andrewmoko** [michaelbromley/angularUtils#298]
I have 3 tabs (on the same page) which have different lists and paginations. 

The first pagination control seems to reflect on the other two. Is there a way to get around this?

Thanks
-Andrew

**Comment by michaelbromley** [comment]
Hi,

Can you show me the code?

**Comment by andrewmoko** [comment]
Hi Michael,

Here is a snipplet

Thanks

`<script type="text/javascript">
    
    jQuery(".tabs").tabs();

</script>

<form novalidate >

    <div class="tabs">
        <ul>
            <li>
                <a href="#items">Items</a>
            </li>
            <li>
                <a href="#operations">Operations</a>
            </li>
            <li>
                <a href="#transactions">Transactions</a>
            </li>
        </ul>
        
        <div id="items">
            <table style="margin-bottom:5px;" class="manage-entities-table">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="clickable-tr" dir-paginate="item in items | itemsPerPage: itemLimit" total-items="itemTotalNumberOfResults" current-page="itemCurrentPage">
                        <td ng-click="showItemDetails({item: item})">{{item.item.name}}</td>
                        <td>{{item.quantity}}</td>
                    </tr>
                </tbody>
            </table>
            <div id="below-entities-table" ng-hide="items.length == 0">
                <span style="float:right;">
                    <div class="entity-pagination">
                        <dir-pagination-controls on-page-change="searchItemStock(entity.uuid, itemCurrentPage)"></dir-pagination-controls>
                    </div>
                </span>
                <br />
            </div>
        </div>

        <div id="operations">
            <table style="margin-bottom:5px;" class="manage-entities-table">
                <thead>
                <tr>
                    <th>Date Created</th>
                    <th>Operation Type</th>
                    <th>Operation Number</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                <tr class="clickable-tr" dir-paginate="itemOperation in itemStockOperations | itemsPerPage: itemStockOperationLimit" total-items="itemStockOperationTotalNumberOfResults" current-page="itemStockOperationCurrentPage">
                    <td>{{itemOperation.dateCreated | date: 'dd-MM-yyyy, h:mma'}}</td>
                    <td>{{itemOperation.instanceType.name}}</td>
                    <td>{{itemOperation.operationNumber}}</td>
                    <td>{{itemOperation.status}}</td>
                </tr>
                </tbody>
            </table>
            <div ng-hide="itemStockOperations.length == 0">
                <span style="float:right;">
                    <div class="entity-pagination">
                        <dir-pagination-controls on-page-change="searchItemStockOperation(entity.uuid, itemStockOperationCurrentPage)"></dir-pagination-controls>
                    </div>
                </span>
                <br />
            </div>
        </div>

        <div id="transactions">
            <table style="margin-bottom:5px;" class="manage-entities-table">
                <thead>
                <tr>
                    <th>Date Created</th>
                    <th>Operation</th>
                    <th>Item</th>
                    <th>Batch Operation</th>
                    <th>Expiration</th>
                    <th>Quantity</th>
                </tr>
                </thead>
                <tbody>
                <tr class="clickable-tr" dir-paginate="itemTransaction in itemStockTransactions | itemsPerPage: itemStockTransactionLimit" total-items="itemStockTransactionTotalNumberOfResults" current-page="itemStockTransactionCurrentPage">
                    <td>{{itemTransaction.dateCreated | date: 'dd-MM-yyyy, h:mma'}}</td>
                    <td>{{itemTransaction.operation.operationNumber}}</td>
                    <td>{{itemTransaction.item.name}}</td>
                    <td>{{itemTransaction.batchOperation.operationNumber}}</td>
                    <td>{{itemTransaction.expiration | date: 'dd-MM-yyyy'}}</td>
                    <td>{{itemTransaction.quantity}}</td>
                </tr>
                </tbody>
            </table>
            <div ng-hide="itemStockTransactions.length == 0">
                <span style="float:right;">
                    <div class="entity-pagination">
                        <dir-pagination-controls on-page-change="searchItemStockTransaction(entity.uuid, itemStockTransactionCurrentPage)"></dir-pagination-controls>
                    </div>
                </span>
                <br />
            </div>
        </div>
    </div>
</form>
`

**Comment by andrewmoko** [comment]
Hi Michael,

Here is a snipplet.

<script type="text/javascript">
    
    jQuery(".tabs").tabs();

</script>

<form novalidate >

    <div class="tabs">
        <ul>
            <li>
                <a href="#items">Items</a>
            </li>
            <li>
                <a href="#operations">Operations</a>
            </li>
            <li>
                <a href="#transactions">Transactions</a>
            </li>
        </ul>
        
        <div id="items">
            <table style="margin-bottom:5px;" class="manage-entities-table">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="clickable-tr" dir-paginate="item in items | itemsPerPage: itemLimit" total-items="itemTotalNumberOfResults" current-page="itemCurrentPage">
                        <td ng-click="showItemDetails({item: item})">{{item.item.name}}</td>
                        <td>{{item.quantity}}</td>
                    </tr>
                </tbody>
            </table>
            <div id="below-entities-table" ng-hide="items.length == 0">
                <span style="float:right;">
                    <div class="entity-pagination">
                        <dir-pagination-controls on-page-change="searchItemStock(entity.uuid, itemCurrentPage)"></dir-pagination-controls>
                    </div>
                </span>
                <br />
            </div>
        </div>

        <div id="operations">
            <table style="margin-bottom:5px;" class="manage-entities-table">
                <thead>
                <tr>
                    <th>Date Created</th>
                    <th>Operation Type</th>
                    <th>Operation Number</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                <tr class="clickable-tr" dir-paginate="itemOperation in itemStockOperations | itemsPerPage: itemStockOperationLimit" total-items="itemStockOperationTotalNumberOfResults" current-page="itemStockOperationCurrentPage">
                    <td>{{itemOperation.dateCreated | date: 'dd-MM-yyyy, h:mma'}}</td>
                    <td>{{itemOperation.instanceType.name}}</td>
                    <td>{{itemOperation.operationNumber}}</td>
                    <td>{{itemOperation.status}}</td>
                </tr>
                </tbody>
            </table>
            <div ng-hide="itemStockOperations.length == 0">
                <span style="float:right;">
                    <div class="entity-pagination">
                        <dir-pagination-controls on-page-change="searchItemStockOperation(entity.uuid, itemStockOperationCurrentPage)"></dir-pagination-controls>
                    </div>
                </span>
                <br />
            </div>
        </div>

        <div id="transactions">
            <table style="margin-bottom:5px;" class="manage-entities-table">
                <thead>
                <tr>
                    <th>Date Created</th>
                    <th>Operation</th>
                    <th>Item</th>
                    <th>Batch Operation</th>
                    <th>Expiration</th>
                    <th>Quantity</th>
                </tr>
                </thead>
                <tbody>
                <tr class="clickable-tr" dir-paginate="itemTransaction in itemStockTransactions | itemsPerPage: itemStockTransactionLimit" total-items="itemStockTransactionTotalNumberOfResults" current-page="itemStockTransactionCurrentPage">
                    <td>{{itemTransaction.dateCreated | date: 'dd-MM-yyyy, h:mma'}}</td>
                    <td>{{itemTransaction.operation.operationNumber}}</td>
                    <td>{{itemTransaction.item.name}}</td>
                    <td>{{itemTransaction.batchOperation.operationNumber}}</td>
                    <td>{{itemTransaction.expiration | date: 'dd-MM-yyyy'}}</td>
                    <td>{{itemTransaction.quantity}}</td>
                </tr>
                </tbody>
            </table>
            <div ng-hide="itemStockTransactions.length == 0">
                <span style="float:right;">
                    <div class="entity-pagination">
                        <dir-pagination-controls on-page-change="searchItemStockTransaction(entity.uuid, itemStockTransactionCurrentPage)"></dir-pagination-controls>
                    </div>
                </span>
                <br />
            </div>
        </div>
    </div>
</form>

**Comment by andrewmoko** [comment]
Is it possible to set an id (paginationId) from the UI? I think that might solve the problem. All the controls have one paginationId i.e __default

**Comment by andrewmoko** [comment]
Solved: I set the pagination-id on both <dir-pagination-controls> and next to the dir-paginate.

Thanks

-Andrew

**Comment by michaelbromley** [comment]
Good to hear.
