### ISSUE TITLE
v0.10.1 filter text working only for current page

### ISSUE THREAD

**Issue by YannisMarios** [michaelbromley/angularUtils#305]
Hello,

I have updated to latest version but it seems that text filter is not working for all pages but only for the current on.

my view (Jade):

.container.full-height
   .col-md-12
      input.form-control(id="search", type="text", placeholder="Filter text", ng-model="q")
      table.table(id="suppliers-list-table")
         thead
            th.suppliers-table-name
               | Supplier ID
            th.suppliers-table-name
               | Supplier Name
            th.suppliers-table-edit
            th.suppliers-table-delete
         tr(dir-paginate="supplier in suppliers | filter:q | itemsPerPage:20" total-items="totalSuppliers" current-page="pagination.current")
            td {{ supplier.SupplierID }}
            td {{ supplier.SupplierName }}
            td
               a(href="/suppliers/" + " supplier._id ")
                  i.fa.fa-eye.fa-fw
      dir-pagination-controls(on-page-change="pageChanged(newPageNumber)")

Thank you

**Comment by michaelbromley** [comment]
Hi,

You are using the `total-items
