### ISSUE TITLE
Pagination Not working properly in two tabs

### ISSUE THREAD

**Issue by pankaj805** [michaelbromley/angularUtils#308]
Hi,

I have two panel tabs implemented. In both of them i have two tables showing different results from different collections.

Now i have implemented dir-paginate in both of the tables.

Now in both tabs, i have searched results being displayed.

When i navigate to second page in tab 1,

navigation also happens in tab2.

Is there any way to fix it?
so they would work separately?

Please, i need help urgently.

Thanks in advance

**Comment by michaelbromley** [comment]
Hi, are you using a pagination id to distinguish the two pagination instances? See https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#multiple-pagination-instances-on-one-page

If yes, and it still doesn't work, please show me some code.

**Comment by pankaj805** [comment]
Hey, thanks. I had missed that. Was searching for something like that only
