### ISSUE TITLE
changing page seems to show two sets of data`

### ISSUE THREAD

**Issue by jmls** [michaelbromley/angularUtils#311]
When I move from page to page, for a brief period of time both pages seem to be show, before the old page is hidden and the current page is shown

What could be the cause of this?

**Comment by michaelbromley** [comment]
Hi,

This is usually caused by animations on the list items. See https://github.com/michaelbromley/angularUtils/issues/226 for a discussion and ideas for work-arounds.

**Comment by jmls** [comment]
I thought that, but can't find any animations at all

the only thing that may be causing a problem is that the content is inside an angular material tab

**Comment by michaelbromley** [comment]
angular-material uses ngAnimate for a lot of things. I guess the fact that ngAnimate is included in your app means that animation hooks are being added to the ngRepeat in your pagination. See [this comment](https://github.com/michaelbromley/angularUtils/issues/226#issuecomment-148419744) for a way to disable these hooks just for the pagination and let me know if that helps.
