### ISSUE TITLE
 App Already Bootstrapped with this Element 'document'

### ISSUE THREAD

**Issue by VinuOye** [michaelbromley/angularUtils#312]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

VM3509:26435 WARNING: Tried to load angular more than once.

angular.js:63 Uncaught Error: [ng:btstrpd] App Already Bootstrapped with this Element 'document'
http://errors.angularjs.org/1.3.20/ng/btstrpd?p0=document

Getting this error on meanjs project with this  'angularUtils.directives.uiBreadcrumbs'

**Comment by michaelbromley** [comment]
Hi,

I've seen this kind of "tried to load more than once" error occur when there is a wrong `templateUrl` combined with a server rewrite rule - the server tries to load the template file, cannot find it, so rewrites the url and serves the index file again, which of course includes the AngularJS library script.

Please check whether this is the case for you - check the dev tools network tab to see what is being loaded for the pagination template.
