### ISSUE TITLE
pagination directive: the itemsPerPage id argument (id: tableConfig.key) does not match a registered pagination-id.

### ISSUE THREAD

**Issue by patrickrioux** [michaelbromley/angularUtils#313]
Hi,

When updating to the latest version 0.11.0 I'm getting the following error:
pagination directive: the itemsPerPage id argument (id: tableConfig.key) does not match a registered pagination-id.

My pagination-id is being set properly. Version 0.10.0 is working good but not 0.11.0.

A breaking change has been introduced and looks like related with the deregisterInstance code addition in V0.11.0?

**Comment by michaelbromley** [comment]
Thanks for the report. There was no regression in the unit tests with v0.11.0 - are you doing something "special" with the module? Are the controls inside and ngIf or something else which might be destroying the scope in the middle of usage?

**Comment by patrickrioux** [comment]
Thank you for the answer. The pagination control have a ng-if="tableRows.length > 0".
But I'm running the same code with 0.10.0 and working great. Some of the changes for 0.11.0 is a breaking change. For now, I'll be using 0.10.0 and won't upgrade to 0.11.0.

**Comment by michaelbromley** [comment]
Ok, reverting to 0.10.x makes sense for now. When I get time, I'll add some unit tests for you type of use case and try to fix the changes to 0.11.0.

**Comment by michaelbromley** [comment]
@patrickrioux If you have time, could you try to reproduce the issue by forking [this plunker demo](http://plnkr.co/edit/b37IdFFJUokaeSummETX?p=preview) - it is using the latest version (0.11.0 right now) so hopefully you should be able to reproduce.

**Comment by fonzy2013** [comment]
I reverted to 0.10.0 as well as I got the same results after adding the following packages:
    "angular-loading-bar": "^0.9.0",
    "angular-animate": "^1.5.3"
Later when I have time I will try to help and debug why these packages break 0.11.0 but not 0.10.0

**Comment by michaelbromley** [comment]
Please update to v0.11.1 (I reverted the memory-leak fix) and let me know if this solves this issue.

**Comment by patrickrioux** [comment]
Hi Michael,

Sorry for not having the time to update the plunker demo although I took some times to test v0.11.1
I confirmed that your changes fixed the issue. Thank you.
