### ISSUE TITLE
dir-pagination-controls and dir-paginate is not working  in Microsoft Internet Explorer 

### ISSUE THREAD

**Issue by ajaiswal595** [michaelbromley/angularUtils#315]
It neither showing pagination-controls nor the data.
The same code is working in Chrome.

                          <dir-paginate="x in tableNames | filter:searchText| itemsPerPage: usersPerPage"
                                total-items="totalUsers" current-page="pagination.current"
                                pagination-id="importedtable">

                           <dir-paginate="y in tableNames | filter:searchSavedQueryTable | itemsPerPage: usersPerPage"
                                    total-items="totalUsers" current-page="pagination.current"
                                    pagination-id="savedqueryid"> in "tr " tag
 
please resolve the problem as soon as possible. Thanks

**Comment by michaelbromley** [comment]
Hi,

In your code above, you are using `dir-paginate` as an element. It is supposed to be used as an attribute. Please see the docs.

Older versions of IE do not like non-standard element names, so try using `dir-pagination-controls` as an attribute on a div, rather than an element.
