### ISSUE TITLE
Custom Filter not populating pages with full amount of pageSize

### ISSUE THREAD

**Issue by JeanHules** [michaelbromley/angularUtils#316]
I am very close, perhaps you can help me... I have a list that I am paginating in groups of 10. 

`dir-paginate="unit in units | itemsPerPage: pageSize | filterSearch: filter : category as q track by $index"`

The issue I am having is when I use my filter, filterSearch, it filters out the correct items, but does not fill the pages to the full amount of 10. So one page 1 for example, default is 10. After I filter, page 1 then has 3 items. yet there are still the same amount of pages as default.  Does that make sense?

Is it possible to reinitiate the directive on filter?

**Comment by michaelbromley** [comment]
Hi,
Put the itemsperpage filter last in the expression.

**Comment by JeanHules** [comment]
I tried that and get this error in console:

`pagination directive: the 'itemsPerPage' filter must be set. <div class="location-item " dir-paginate="unit in units | filterSearch: filter : category as q track by $index | itemsPerPage: pageSize" current-page="currentPage">`

**Comment by michaelbromley** [comment]
Sorry, I was not specific enough (writing on my phone). Put it after any filters but before the `as` and `track by` parts.

**Comment by JeanHules** [comment]
ah ok. That did work with the help of a duplicate array of filtered items. Thanks and great directive.
