### ISSUE TITLE
Items per page

### ISSUE THREAD

**Issue by huquduy** [michaelbromley/angularUtils#317]
Hi Micheal, i get error when set items per page equal 101, how can i fix it? thanks!

**Comment by chaideos** [comment]
@huquduy I think you will need to change the max-size attribute on the <dir-paginate-controls> 

e.g. <dir-pagination-controls max-size="101">
    </dir-pagination-controls>

**Comment by michaelbromley** [comment]
@huquduy Hi, I'm afraid I'll need some more information:

What does your code look like, and what is the exact error?

**Comment by huquduy** [comment]
sorry, I've fixed them, that error from i set max=30 in input html (so angular cannot get value when it's 101), thanks @michaelbromley, :+1:

**Comment by michaelbromley** [comment]
Ok, good.
