### ISSUE TITLE
ItemPerPage and CurrentPage cause two pageChangeEvent 

### ISSUE THREAD

**Issue by veshu** [michaelbromley/angularUtils#318]
I have  following setup http://plnkr.co/edit/LoDCQVVnJVJTwAlDIhCN?p=preview
1. Two controls (top and bottom)
2. async loading case where data comes from api (scenario, with meals and totalItems)
3. Now all is fine except when
 - set pageSize to 5
- go to page 2
- open the console and clear
- copy and paste 20 in pageSize box
-watch the console , it will call page change function twice.

Any help would be great.

**Comment by michaelbromley** [comment]
Hi,

Thanks for the demo. I can reproduce the issue and I can see why it happens. There are $watchers set up which react to changes in both `itemsPerPage` and `currentPage` and invoke `onPageChange` on any changes.

You can see that changing the value of `itemsPerPage` in your demo will trigger the `onPageChange` callback, regardless of whether the page changes. 

Does this not make sense in an async loading scenario? If you change the number of items per page, you would need to make a new request to the server, no?

**Comment by veshu** [comment]
Thnx for follow up. 

It needs to make a request but only once. I did very ugly workaround at the moment as storing current page number before ajax and set to null once request complete the ajax and check the stored number in the pageChanged method.

It won't be a major issue if data is not loaded from remote API. But will greatly impact performance in my case as I was using API which has large payload.

Any better idea to fix this?

**Comment by okolawol** [comment]
If i have a text search box along with the pagination. I need to change the current-page back to 1 manually when search returns results. The thing is when current page is set to one, onPageChange is invoked which calls the server again! So now we have 2 duplicate calls.

**Comment by MangeshPimpalkar** [comment]
I am facing the same issue.
There are 2 calls made for a click if you are using multiple instance of controls for the same grid.
my workaround was to cancel the previous call to the server but it would be great if we could have a solution for this.

**Comment by dderichs** [comment]
I am also facing this issue.
@MangeshPimpalkar could you please provide the workaround?

**Comment by michaelbromley** [comment]
A more general work-around to the above issues is to not use the `on-page-change` callback, but instead to set up a `$watch` on the `current-page` scope var:

```JavaScript
$scope.currentPage = 1;
$scope.$watch('currentPage', myAsyncFunction);
```

```HTML
<li dir-pagination="item in items | itemsPerPage: 10" current-page="currentPage">...</li>
```

@veshu here is a modified version of your demo which implements this approach: http://plnkr.co/edit/6dkeZnVBAayC2OQwRAl9?p=preview

Please let me know if this works in your case.

**Comment by veshu** [comment]
Thanks, it is working on your plunker. I did test with search text box too and is fine.

But couldn't verify on my app right now. I will implement in next project and get back if it won't work.

**Comment by michaelbromley** [comment]
Ok, sounds good. I'll close this now and you can re-open if needed.
