### ISSUE TITLE
When I set a pagination ID returns Syntax Error: Token '__currentPage' is an unexpected token at column 4 of the expression [184__currentPage] starting at [__currentPage].

### ISSUE THREAD

**Issue by laudess** [michaelbromley/angularUtils#319]
Hello, I am working on a page with different bootstrap tabs. Each tab has it's own pagination so I need to have one dir-paginate for each tab. I have dir-paginate inside a ng-repeat, but when It comes to define the pagination-id it throws me this error:
Syntax Error: Token '__currentPage' is an unexpected token at column 4 of the expression [184__currentPage] starting at [__currentPage].

This is my code:

`<div class="tab-pane" ng-repeat="protocolo in getMezclasAdministracion.Object" id="protocolo-{{ protocolo.Codigoprotocolo }}">
                            <ul>
                                <li pagination-id="protocolo.Codigoprotocolo" dir-paginate="mezcla in protocolo.Mezcla_AdministracionList | itemsPerPage: 1" class="mezcla-container"></li>
</ul>
</div>`

Thank you

**Comment by banbanchs** [comment]
Same issue here. Two tabs + same template + two controller. Version 0.10.1 is working good.
=>  #313

**Comment by michaelbromley** [comment]
Hi,
In v0.11.0 I introduced a change that fixes a fairly serious memory leak. It looks like it was too aggressive in the way it cleans up references and there are a couple of issues now - this included - where things break when the pagination is inside a directive that dynamically destroys DOM (e.g. ngIf, ngRepeat)

For now, just use 0.10.1 - unless you need template strings (also introduced in 0.11.0), you are not missing out on anything new. I will fix this as soon as I get some time to invest.

**Comment by michaelbromley** [comment]
@laudess  @banbanchs  If you have time, could someone try to reproduce the issue by forking [this plunker demo](http://plnkr.co/edit/b37IdFFJUokaeSummETX?p=preview) - it is using the latest version (0.11.0 right now) so hopefully you should be able to reproduce. This will greatly help me resolve the issue.

**Comment by michaelbromley** [comment]
Please update to v0.11.1 (I reverted the memory-leak fix) and let me know if this solves this issue.

**Comment by banbanchs** [comment]
@michaelbromley issue solved!
