### ISSUE TITLE
Problem with sorting that jumps

### ISSUE THREAD

**Issue by kristiandanielsson** [michaelbromley/angularUtils#320]
Hi, I have a sorting on my table based on an array of strings. The table is build in that way so when I press a row, several childrows is pushed out.

The pagination works fine, and the sorting as well, until the number of rows exceeds the itemsPerPage attribute. Then suddenly the sorting jumps around.

This problems doesn't happend the first time the page is loaded, it's after I clicked around a bit in my table.

Now I wonder if there is by any chance a way of "refreshing" the pagination?

**Comment by michaelbromley** [comment]
Hi,

Could you provide some code so I can try to understand the issue better? If you are able to [reproduce the issue in Plunker](http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview) that would make it much easier for me to help.

**Comment by kristiandanielsson** [comment]
Hi,

Sorry for being slow with the plunker. Here it is: http://plnkr.co/edit/ObfQmHZuyZCY3xDuccZN?p=preview. The sorting is based on the column "Sorting". And when I below refer to "row" I mean Value1 column :)

1: Press the row with Value1 = 1.
2: Press the row with Value1 = 12. Now you should see 5 subrows under row 12.
3. Decrease to pagesize input from 70 to 7, now you should see that the sorting is wrong, the subrows for row 12 is presented under row 10, and not row 12.
4: Try increase pagesize again, then the sorting is corrected again,

**Comment by michaelbromley** [comment]
Thanks for the demo. The solution is to ensure that the `itemsPerPage` filter comes after your `orderBy` filter in the dir-paginate expression:

```
<tr dir-paginate="row in rows
    | orderBy:sortType:sortReverse 
    | itemsPerPage:pageSize" ng-click="toggleRow(row)">...
```

This is quite common mistake - there is a [note on it in the FAQ](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#why-does-my-sort--filter-only-affect-the-current-page)

**Comment by kristiandanielsson** [comment]
Thank you very much. This helped me alot.
