### ISSUE TITLE
Question: pagination template

### ISSUE THREAD

**Issue by nkamenar** [michaelbromley/angularUtils#322]
Would it be possible to use the pagination template so instead of numbering pages 1, 2, 3... based on how many items you want to show, you displayed the pagination 0-9 | A-F | G-K | L-P | Q-U | V-Z and all items are placed into the respective place? I have AJAX code that I can use to request a "page" of data that would match the above template but I don't know how I could map the pages to the pagination control. If this is possible and you have a small example that would be amazing, thanks!

**Comment by michaelbromley** [comment]
Hi,

There is no simple way of doing this with this module. Such a system uses an entirely different method of splitting pages than the simple "array slice" method required by regular pagination. In an alphabetical system, each page would contain some arbitrary number of items which can only be known by inspecting the entire collection.

I'm afraid you'll have to build your own.
