### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by hackel** [michaelbromley/angularUtils#323]
I was going to upgrade dirPagination (0.8.4 to 0.11.0), but in looking through the commits, it just says "See release notes" for every release.  I must be blind because I can't find any release notes anywhere on either repo.  Where should I be looking?  I just want to know if there are any breaking changes I should be concerned about.  Thanks!

**Comment by michaelbromley** [comment]
Hi,

Yeah, I understand why it might be tricky to find. I'll add a link to the README: https://github.com/michaelbromley/angularUtils-pagination/releases

Note - v0.11.0 has a potentially breaking change (actually more of a bug) depending on how you use it (see https://github.com/michaelbromley/angularUtils/issues/319). If you get errors with that version, use 0.10.1. Unless you really need template strings, you are not missing anything.

**Comment by hackel** [comment]
Aha, thanks!
