### ISSUE TITLE
dirPagination v0.11.0 - Pagination Semi-Broken

### ISSUE THREAD

**Issue by BonnieDoug** [michaelbromley/angularUtils#325]
Hi, I have recently implemented dirPagination into my project. I'm attempting to iterate over a JSON Object which work's to a point.

On initial page load the Pagination works great. However if I navigate away from the page but then return the pagination breaks with an error of:

    pagination directive: the itemsPerPage id argument (id: __default) does not match a registered pagination-id.
    Error: instances[instanceId] is undefined

I currently implement it as per the documentation with:

    
    <div ui-view ng-init="getData()">
       <tr dir-paginate="data in datas| toArray:false | filter:query | orderBy: sortKey:reverse | itemsPerPage:5">
       </tr>
        <dir-pagination-controls
        max-size="5"
        direction-links="true"
        boundary-links="true" >
       </dir-pagination-controls>
    </div>

    
    $scope.getData = function () {
        DataSender.get('Data').then(function (data) {
            if (data) {
                $scope.datas = data;
            }
        });
    };

The data still gets loaded however the pagination buttons do nothing except error into the console. It also breaks filtering, though I think this is just a knock on effect. If I replace dir-paginate with ng-repeat it works when navigating between pages but obviously without the pagination ability.

I'm using Angular v1.5.1 and dirPagination v0.11.0

**Comment by BonnieDoug** [comment]
Having read other issues, I tried rolling back to version 0.10.1, which fixes the issue. Something to do with garbage collection?

**Comment by michaelbromley** [comment]
Please update to v0.11.1 (I reverted the memory-leak fix) and let me know if this solves this issue.

**Comment by BonnieDoug** [comment]
Sorry for the late reply. Yes this has fixed the issue and it works great again.
