### ISSUE TITLE
dirPagination in modal(ngDialog) not working properly when is opened twice in a row.

### ISSUE THREAD

**Issue by sabin-iliescu** [michaelbromley/angularUtils#326]
I have the following problem:

First time that I open the modal the pagination is working properly.
I close the modal(ngDialog) and then I open it again.
This time if I press next page ng-click="setCurrent(pagination.current + 1)" the value becomes 11, practically on click it concatenates pagination.current that is 1 with 1 resulting 11.
If I print {{pagination.current}} the first time it prints on click 2 and the second time I open the modal it prints 11.
I have tried to modify the template like this:
ng-click="setCurrent(parseInt(pagination.current, 10) + 1)"
but is not working.

I must mention that I'm in a repeater and I'm using id for linking dir-paginate to dir-pagination-controls.
Maybe someone can provide another idea.

Thank you very much.

**Comment by michaelbromley** [comment]
Hi,

Sounds really strange. Can you reproduce it in a demo by forking and modifying this Plunk: http://plnkr.co/edit/b37IdFFJUokaeSummETX?p=preview ? That would make it possible for me to look into what is going on.

**Comment by sabin-iliescu** [comment]
Hi Michael,
It was strange indeed but it was my fault, I have declared in my controller:
$scope.pageSize = '10';
$scope.currentPage = '1'; 
after I have modified them like this:
$scope.pageSize = 10;
$scope.currentPage = 1;
the pagination started to work properly.

Thanks

**Comment by michaelbromley** [comment]
Ok, glad you got it fixed. 

Just a friendly reminder - if you open an issue and later resolve it, *please* close the issue and let the maintainer know what the resolution was. It makes life much easier for people like me who have to invest free time in supporting open source projects.
