### ISSUE TITLE
dirPaginate: Troubles with $http.get

### ISSUE THREAD

**Issue by Hardronox** [michaelbromley/angularUtils#327]
I have $http.get request to the server instead of simple array, and it returns me my content. It works fine but when I look inside my firebug, It sends not 1 request, but as many same requests as inside pageSize variable.

**Steps to reproduce**:
You can just put this or mb some another working request inside your "MyController" (not instead, just put it there and take a look into a firebug), and include $http into your controller ofc:

$http.get('/blog/get-blogs').success(function(response){
    //console.log(response);
    //$scope.blogs=response;
  });

**Expected result**:
1 request

**Actual result**:
 as many same requests as inside pageSize variable(10 by default)

Any relevant code:
```

```

**Comment by Hardronox** [comment]
looks like trouble is in the my view file. still dont know where, but i think its all okay with your pagination, sorry for bothering you

**Comment by michaelbromley** [comment]
ok, no worries.
