### ISSUE TITLE
dirPagination v. 0.11.1: 'filter:searchText as results' not working when before itemsPerPage

### ISSUE THREAD

**Issue by agwm2013** [michaelbromley/angularUtils#328]
When using filter:searchText as results, the error is: itemsPerPage filter must be set. 

Can be recreated by placing as results after filter in example: http://plnkr.co/edit/7pH3Dw?p=preview 

Works as expected if itemsPerPage filter is first (though this obviously does not filter as per the FAQ in the ReadMe).

**Comment by michaelbromley** [comment]
Yes, that is because it is not valid syntax for ngRepeat. From the docs:

> Please note that `as [variable name] is not an operator but rather a part of ngRepeat micro-syntax so it can be used only at the end (and not as operator, inside an expression).

So in your case, if you want to get a reference to all the filtered items *before* they are paginated, you can do it like this:

```
dir-paginate="item in results = (collection | filter: searchText) | itemsPerPage: pageSize"
```

**Comment by agwm2013** [comment]
Thanks, I definitely missed this in the docs when troubleshooting before posting.
