### ISSUE TITLE
dirPagination: page navigation problem

### ISSUE THREAD

**Issue by thangaduraiarepo** [michaelbromley/angularUtils#329]
I am using dirPagination in client side as well as server side(Asynchronous Setup). The issue is client side pagination is not navigate another page. 

 Steps to re produce the issue is,
1.First open the server side pagination page, 
2.Then open the client side pagination page.
3. Now click the next page(Page Number 2), data is not changing(Showing first page data), But pagination controls was changed.

if i opened the client side pagination page first means, it working fine.

Page navigation need to work while i am switch from server side pagination page to client side pagination page.

**Comment by michaelbromley** [comment]
Hi,

I'm afraid I can't quite figure out what you mean. Please could you provide some code?

**Comment by thangaduraiarepo** [comment]
Following code only i am using.

**For Client Side pagination:**

`     <table>
        <thead></thead>
         <tbody>

							<tr  ng-show="resultData.length>0"  dir-paginate="result in resultData|filter:search|orderBy:sortKey:reverse|itemsPerPage:noOfRows">
								<td class="wrap" ng-cloak>{{result.firstName}}</td>
								<td class="wrap" ng-cloak>{{result.lastName}}</td>

								<td class="wrap" ng-cloak>{{result.phoneNumber}}</td>
								<td class="wrap" ng-cloak>{{result.emailAddress}}</td>
							</tr>
							<tr ng-show="!resultData.length">
				<td colspan="6" align="center">No Records Found</td>
				</tr>
						</tbody>
						
					</table>
					<dir-pagination-controls max-size="5" direction-links="true" boundary-links="true" >
    					</dir-pagination-controls>`


**For Server Side Pagination:**

`            <table>
             <thead></thead>
       <tbody>
	<tr dir-paginate="result in resultData|itemsPerPage:resultData.itemsPerPage"
					current-page="resultData.pageNumber" total-items="totalRecords">
					
					<td><span>{{result.name}}</span></td>

					<td title="Phone Number">{{result.phoneNumber}}</td>
					<td title="Age">{{result.age}}</td>
				</tr>
				<tr ng-show="resultData.length==0">
					<td colspan="11"><center>
							<strong>No Records Found!!!</strong>
						</center></td>
				</tr>
			</tbody>
		</table>

		<dir-pagination-controls ng-show="resultData.length>0" max-size="5" on-page-change="searchFromPage(newPageNumber)"  direction-links="true" boundary-links="true" >
    					</dir-pagination-controls>`

Actually the issue is page navigation is not working in client side pagination, if i open server side pagination page first. The page was highlighted as 2nd but data for second page is not loading, only showing first page data.

**Comment by thangaduraiarepo** [comment]
While using Server Side Pagination:

The instance object returned like this: (displayed in console)

`m {$$childTail: m, $$childHead: m, $$nextSibling: null, $$watchers: Array[11], $$listeners: Object…}`

**$$nextSibling: null**

While using Client Side Pagination:

The instance object returned like this: (displayed in console):

`m {$$childTail: m, $$childHead: m, $$nextSibling: m, $$watchers: Array[11], $$listeners: Object…}`


**$$nextSibling: m**

I think here is the issue. With out visiting server side pagination, Client side pagination returning $$nextSibling value is m. Once visited the Server side pagination $$nextSibling value is changed to null. Because of this client side pagination navigation is working but data is not changing. Showing first page data only. Even clicking any page. 

Please guide me, if i did wrong.

Thanks

**Comment by brunoneve** [comment]
Show your controller

**Comment by michaelbromley** [comment]
I still don't really understand, sorry. Do you mean you are trying to do both server-side and client-side pagination at the same time?

Please describe the use case in detail and, as mentioned above, show your controller code.

**Comment by thangaduraiarepo** [comment]
Thanks for your response.

Ya i am using both Server-Side and Client-Side pagination. But Server-Side pagination in different page, Client-Side pagination in different page. 

Finally, i solved this issue by using pagination id. I am giving different pagination Id for both pagination controls,

**Comment by michaelbromley** [comment]
Hi, okay. In future, could you please close the issue and state how you resolved it once it is solved? That is helpful for the maintainer (me) so that I don't need to spend time re-reading the thread in the future.
