### ISSUE TITLE
Assigning unique pagination-id for each element while looping

### ISSUE THREAD

**Issue by guytalmor** [michaelbromley/angularUtils#330]
**Description of issue**: I am using the pagination library to loop over and exhibit elements, for which I want to assign different pagination IDs. My problem is that I am unable to assign variables under "pagination-id". I tried the conventional angular way as follows:

pagination-id="variable_{{$index}}"

however, for some reason this doesn't work in the pagination module. Any idea how I can assign a unique ID to each element I am presenting using the loop?

**Comment by anderson-fachini** [comment]
Try to put the ID between quotations
`pagination-id="'variable_{{$index}}'"`

**Comment by michaelbromley** [comment]
Sorry for the slow reply. You should be able to do this like so:

```
pagination-id="'variable_' + $index"
```

Note the single quotes around "variable".
