### ISSUE TITLE
dirPagination: setCurrent does not account for all conditions for different templates

### ISSUE THREAD

**Issue by MangeshPimpalkar** [michaelbromley/angularUtils#331]
**Description of issue**: When using the custom page control with input field.
If we input -1 or a number above the max Count(scope.pagination.last) it does not fall back to first page or last page.Then after you click on next button or previous button doesn't do anything.

Original Code-  

            scope.setCurrent = function(num) {
                if (paginationService.isRegistered(paginationId) && isValidPageNumber(num)) {
                    num = parseInt(num, 10);
                    paginationService.setCurrentPage(paginationId, num);
                }
            };

**Modified code **:

           scope.setCurrent = function (num) {
                if (paginationService.isRegistered(paginationId)) {
                    if (isValidPageNumber(num)) {
                        num = parseInt(num, 10);
                    } else if (angular.isUndefined(num)) {
                        num = 1;
                        goToPage(num);
                    } else {
                        num = parseInt(scope.pagination.last, 10);
                    }
                    paginationService.setCurrentPage(paginationId, num);
                }
            };

Please let me know if this code is correct.I had to modify this code for my project.

**Comment by MangeshPimpalkar** [comment]
@michaelbromley :eyes:

**Comment by michaelbromley** [comment]
Hi,

So you mean that instead of having page links, you have an `<input>` field where the page number can be entered?

Looking at your modified code, it looks like if I set it to `-1`, it will set the current page to the last page, rather than the first.

**Comment by MangeshPimpalkar** [comment]
@michaelbromley I modified the code little bit.

When i set the input to any negative number the num param in the function setCurrent comes as undefined and then we reset the num to 1

**Comment by michaelbromley** [comment]
Hi, I've not got enough time to invest in trying to re-create this issue. If you have time, please fork and modify this Plunk: http://plnkr.co/edit/b37IdFFJUokaeSummETX?p=preview to show the problem with the current implementation.

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, feel free to re-open.
