### ISSUE TITLE
Use template string instead of templateUrl in ui-breadcrumbs

### ISSUE THREAD

**Issue by rafaeleyng** [michaelbromley/angularUtils#332]
As far as I can see, this is not possible currently.

In my current scenario, I don't see the fit for templateUrl, but I could use a option to pass a template string.

I'm developing a `common` project (that uses ui-breadcrumbs) and a lot of other projects that use this `common` project, installing it as a npm dependency. Webpack bundles it all together, but in my dependent projects (the ones that depend on the common), the HTML template file (that would live inside the `common` project) is burried inside node_modules/my-common-project, so I can't reach that HTML file with some URL.

**Comment by MangeshPimpalkar** [comment]
I wanted to use the string I used it like it.

`$scope.paginationTemplate = $templateCache.put('angularUtils.directives.dirPagination.template', $templateCache.get('/views/pagination.view.html'))`

where I use my custom template.

**Comment by rafaeleyng** [comment]
@MangeshPimpalkar Do you think this would be doable in breadcrumbs too? It just doesn't seem to work with template, only with templateUrl

**Comment by michaelbromley** [comment]
Hi,

You are correct that it is currently not possible to specify a template string. That module was written way before the days of Webpack, so such a thing was not a common requirement (at least in my own projects).

The suggestion of using the `$templateCache` service could work for you. In your app run block, for example, you could do something like:

```
$templateCache.put('myBreadcrumbsTemplate.html', require('myTemplate.html'));
```

and then you specify `myBreadcrumbsTemplate.html` as the `template-url` attribute for the breadcrumbs. Not tested, but could work.

**Comment by rafaeleyng** [comment]
@michaelbromley It did work! That was nice.

Any chances of installing ui-breadcrumbs with npm?

**Comment by rafaeleyng** [comment]
I did installed pointing to the angularUtils Github repo. But I had to use the commit hash since there isn't a tag.

**Comment by michaelbromley** [comment]
@rafaeleyng I've not got time atm to make an npm version. The commit hash should be pretty safe - I rarely change that code since I don't use it myself in production any more.
