### ISSUE TITLE
dirPagination: Focus does not return to the top of the page when new page is selected

### ISSUE THREAD

**Issue by mdd-itn** [michaelbromley/angularUtils#334]
Michael, thanks for this --it is terrific. But I do have a small issue -- in Microsoft Edge and in Google Chrome (only browsers I've tested so far), when you click to move to a new page, the focus doesn't shift -- i.e., the screen does not return to the top of the screen. In stackoverflow, for example, when you click the page numbers at the bottom, the focus does go back to the top of the screen.

Here is my code:`<aside class="col-md-8" ng-controller="playScriptCtrl">
                        <div class="sidebar">
                            <div class="side product-item vertical-divider-left">
                                
                                <div dir-paginate="segment in script | itemsPerPage: 10">
                                    <p ng-if="segment.owner!='NA'" class="character"> {{segment.owner}}</p>
                                    <p ng-class="segment.type" ng-bind-html="segment.text"></p>
                                </div>

                                <dir-pagination-controls></dir-pagination-controls>
                                        
                            </div>
                        </div>
                    </aside>`

(This is an html fragment inside a larger page.)
Can you help? Thank you!

**Comment by michaelbromley** [comment]
Hi, please see this issue where this is discussed: https://github.com/michaelbromley/angularUtils/issues/142

Have a go at implementing the solution discussed there, and let me know if it works for you.

**Comment by mdd-itn** [comment]
Thank you Michael! I did use the generic window.scroll concept as you described and it seems to be working fine.


I appreciate the prompt response!


Martin


Martin Denton
Editor/Founder
Indie Theater Now
www.indietheaternow.com


________________________________

**Comment by michaelbromley** [comment]
Good, glad you got it working.
