### ISSUE TITLE
paginationService: Need to set current page programmatically

### ISSUE THREAD

**Issue by gtarcea** [michaelbromley/angularUtils#337]
**Description of issue**:
I'm using the pagination service in a todo list manager. The way it works is you hit return on the current todo item and it opens a new one below it. For example
I am here ---> 1
               new item <--- new item will be inserted here
                     rest of list

If I am on the last item in the page, then when I insert a new item it will be created on the next page. When this case occurs, I need to switch to the next page and set the focus on that item. Otherwise the user doesn't see the new item (unless they know to switch to the next page when this case occurs).

**Steps to reproduce**:
Create a new item below the current item, when the current is on the page boundary.

**Expected result**:
I need an interface to switch to the next page.

**Actual result**:
What actually happens is the new item is inserted on the next page, but the display stays on the current page.

**Demo**: 

Any relevant code:
I used the paginationService (I realize we aren't supposed to use it) to switch to the next page. The code looks as below (taskIndex is the index of the current task (that is the task the user hit return from to create the new task). I use this to determine if I'm on a page boundary and if so, switch to the next page.

```js
function gotoNewTasksPage(taskIndex) {
        let instanceId = paginationService.getLastInstanceId();
        let currentPage = paginationService.getCurrentPage(instanceId);
        let itemsPerPage = paginationService.getItemsPerPage(instanceId);
        let remainder = (taskIndex+1) % itemsPerPage;
        if (!remainder) {
            // On a page boundary, so new item will be created on the next page.
            // Switch to that page.
            paginationService.setCurrentPage(instanceId, currentPage+1);
        }
    }
```

**Comment by michaelbromley** [comment]
Hi,

Thanks for the detailed write-up. Have you tried binding to the `current-page` attribute and then just setting it in your controller? E.g.:

```HTML
<ul dir-paginate="item in todos | itemsPerPage: 10" current-page="currentPage">
...
</ul>
```

Then you have this var, `$scope.currentPage` which you can manipulate directly to change the current page. It would be much simpler than trying to use the internal `paginationService`.
