### ISSUE TITLE
uiBreadcrumbs: displayName binding from controller

### ISSUE THREAD

**Issue by flache** [michaelbromley/angularUtils#340]
In my scenario, I am loading a resource via a promise and I would like to use the promise result as display name. I do not want to use the router's `resolve` method for that.

Is it possible to bind data from the controller directly to the display name?

**Comment by michaelbromley** [comment]
Hi,

No, promise resolutions may only come from the `resolve` state property. The idea behind the directive is that it is completely config-driven - you just set up the state definitions and then let it do the rest. Changing it ad-hoc from controllers is a different approach but unfortunately not one which is supported here.
