### ISSUE TITLE
dirPagination: On state change, default pagination-id no longer registered?

### ISSUE THREAD

**Issue by hackel** [michaelbromley/angularUtils#342]
Using dirPaginatoin 0.11.0:

I have pagination setup and it's been working great.  I only have one pagination per pager, so I haven't needed to set a pagination-id (using __default).  I'm also using ui.router, and added some code to automatically change states when certain parameters change.  When it does this, it navigates to the new state, but then gives me the error:
`the itemsPerPage id argument (id: __default) does not match a registered pagination-id` (5-6 times)
It seems to be trying to run the itemsPerPage filter before the page has fully re-loaded, and so in that short span of time, the pagination-id isn't registered.

I've been trying to debug this without much success and would appreciate any ideas.  In my controller constructor, I tried logging `paginationService.isRegistered('__default')` and it always returns true *before* I get the error message.  So I guess it is being deregistered after that, but I can't imagine why.  I will attempt to replicate the issue in a Plunker as well.

Thanks in advance.

Edit: Absolutely no luck reproducing this so far, everything works perfectly.  http://plnkr.co/edit/hGdPHHNLTLPeX5kgTccG?p=preview

**Comment by ctoestreich** [comment]
We run into this now as well

<img width="1150" alt="screen shot 2016-04-26 at 1 32 00 pm" src="https://cloud.githubusercontent.com/assets/691357/14829864/508a14e2-0bb3-11e6-8bdf-276caad662a4.png">
<img width="578" alt="screen shot 2016-04-26 at 1 31 16 pm" src="https://cloud.githubusercontent.com/assets/691357/14829863/50892c26-0bb3-11e6-8ac5-6fc7a2340ecb.png">

**Comment by ctoestreich** [comment]
the problem was with 0.11.0, but with the master raw version in teh demo above it seems okay

**Comment by michaelbromley** [comment]
Yes, the latest version is 0.11.1 - it was released to address these specific bugs. The plunk works because it points directly to the master branch version of dirPagination.js.

I'll close this and you can re-open if you still have issues with the latest version.
