### ISSUE TITLE
Not working with angular material design

### ISSUE THREAD

**Issue by lolaswift** [michaelbromley/angularUtils#343]
Hi Michael
I try to use the module with angularjs+material design but it doesn't work. version 0.11.1

**Description of issue**:
When click on the page number,for example, page 2, it doesn't change the content to page 2.
~~~~~~
this.setCurrentPage = function(instanceId, val) {
			console.log("pageservice setcurrentpage called");
			console.log(instanceId); //outplut  "_default"
			console.log(val);// output page number, for example "2"
            instances[instanceId].currentPageParser.assign(instances[instanceId].context, val); //this doesn't seem to work
        };
~~~~~~
some codes:
~~~~~

<md-content class="padded-content-page">
	<md-list>
    <md-subheader class="md-no-sticky">Logs</md-subheader>
    <md-list-item class="md-3-line" dir-paginate="log in ::vm.logs | itemsPerPage: 5">
        <div class="md-list-item-text">
            <h3>{{::log.timeStamp | date:"MM/dd/yyyy 'at' h:mma" : 'UTC' }}</h3>
            <h4>{{::log.title}}</h4>
            <p>{{::log.text}}</p>
        </div>
    </md-list-item>
	<md-list-tem>
	    <dir-pagination-controls></dir-pagination-controls>
	</md-list-tem>
    <md-divider ></md-divider>
</md-list>
</md-content>
~~~~~~

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. Can you recreate the behaviour in a Plunker demo? I've not got the time at the moment to do that myself, but if you could do it, I can certainly have a go at debugging it for you.

Fork and modify this Plunk: http://plnkr.co/edit/b37IdFFJUokaeSummETX?p=preview and link back to it here.

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, feel free to re-open.
