### ISSUE TITLE
'dir-paginate-controls' broken in IE 11 with SharePoint modal

### ISSUE THREAD

**Issue by malick7** [michaelbromley/angularUtils#345]
Hi Michael, 

While using 'dir-pagination-conrol' the pageNumber is not extrapolated to its value, instead {{ pageNumber }} is itself getting displayed in UI. 

![dir_paginate-issue](https://cloud.githubusercontent.com/assets/6679375/14890058/c94555e6-0d7e-11e6-90ab-2b58fb10309e.PNG)

I've tried using dir-pagination-control both as element and attribute since you have mentioned in lots of places that we should use it as attribute.

**dir-pagination-controls direction-links="true" max-size="5" /dir-pagination-controls
div dir-pagination-controls={ direction-links:true, max-size:5} /div**

I'm using the default template-url for the same. 
The problem occurs in production environment, I tried to reproduce the issue in my local dev environment but wasn't successful so I couldn't give you a plunkr link. 

Any help/suggestion is very much appreciated.
Thanks :)

Edit 1:
I've observed a few things by playing around a little. 
I'm actually loading the pagination result as an iframe in a Microsoft SharePoint modal dialog - SP.UI.ModalDialog.

**https://msdn.microsoft.com/en-us/library/office/ff410058(v=office.14).aspx**

The above behaviour - {{pageNumber}} being dsiplayed, happens only if I use SP.UI.ModalDialog. If i instead do this :
**window.parent.location = 'some url'**
to display the pagination result, then the data binding happens correctly and appropriate page numbers are displayed.  

**From code - dirPagination.js:**
```
$templateCache.put('angularUtils.directives.dirPagination.template', 'ul class="pagination" ng-if="1 < pages.length"><li ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == 1 }"><a href="" ng-click="setCurrent(1)">&laquo;</a></li><li ng-if="directionLinks" ng-class="{ disabled : pagination.current == 1 }"><a href="" ng-click="setCurrent(pagination.current - 1)">&lsaquo;</a></li><li ng-repeat="pageNumber in pages track by $index" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == \'...\' }"><a href="" ng-click="setCurrent(pageNumber)">{{1+1}}</a></li><li ng-if="directionLinks" ng-class="{ disabled : pagination.current == pagination.last }"><a href="" ng-click="setCurrent(pagination.current + 1)">&rsaquo;</a></li><li ng-if="boundaryLinks"  ng-class="{ disabled : pagination.current == pagination.last }"><a href="" ng-click="setCurrent(pagination.last)">&raquo;</a></li></ul');
```

This is where the template for dirPaginationControls is set. I think the expression is not evaluated for some reason. I even tried to change it to some thing like **{{1+1}}** to check if it evaluates to 2, instead {{1+1}} only is being displayed. 

So I feel the data binding in templateCache isn't working if we are loading it using SP.UI.ModalDialog.
Is there any other way we can do data binding other than {{ }} to evaluate and display the result?

Any thoughts?
Thanks :)

**Comment by michaelbromley** [comment]
Hi,

Unfortunately this is a really specialized issue - I have zero experience with SharePoint. So I assume that other Angular things *do* work in your dialog? 

Have you tried using a different template, rather than the default $templateCache version?

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, feel free to re-open.
