### ISSUE TITLE
Pagination not updating after filter

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [michaelbromley/angularUtils#349]
Am using dir-pagination directive for pagination, its working fine but while filtering pagination not getting update

![pag-error](https://cloud.githubusercontent.com/assets/15795961/15109746/97f242c2-15fa-11e6-80e7-4261eab5b820.png)

Below is mycode:

```
 <tbody dir-paginate="booking in bookinglist | itemsPerPage: 30 | orderBy:sortKey:reverse">
        <tr ng-repeat="orders in booking.order | filter: booking_filter | dateRange: startDate : endDate | orderBy:sortKey:reverse">
          <td>{{booking.customer_name}}</td>
          <td>{{orders.order_id}}</td>
          <td>{{orders.service_name}}</td>
          <td>{{orders.employee_name}}</td>
          <td>{{orders.area_name}}</td>
          <td>{{orders.booking_date | date:"dd/MM/yyyy"}}</td>
          <td>{{orders.booking_time}}</td>
          <td>{{orders.status}}</td>
          <td class="g-btn-full-width">
            <button type="button" ng-click="EditBooking(orders._id)" class="btn btn-primary"><span class="fa fa-pencil"></span></button>
            <button type="button" ng-click="DeleteBooking(orders._id)" class="btn btn-danger"><span class="fa fa-trash"></span></button>
            <button type="button" ng-click="InvoiceGenerate(orders._id)" class="btn btn-warning">Invoice</button>
          </td>
        </tr>
      </tbody>
    </table>
    <dir-pagination-controls>
        max-size="5"
        direction-links="true"
        boundary-links="true"
    </dir-pagination-controls>
    </div>
```

**Comment by michaelbromley** [comment]
I'm not sure I understand the intent of your code, but to me it looks strange:

* you are paginating over the `tbody` element, which means you will end up with a `<table>` with multiple (up to 30)  `<tbody>` elements, each of which contains some rows.
* you are *not* filtering the paginated `tbody`s, but just sorting them with the `orderBy` filter.
* in any case you probably want the `itemsPerPage` filter to go last, after all other filters. See [this FAQ question for an explanation](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#why-does-my-sort--filter-only-affect-the-current-page)

I hope that helps as a start. Let me know if you need further assistance.
