### ISSUE TITLE
dir-paginate load all data before filtering itemPerPage

### ISSUE THREAD

**Issue by FarshadKazemi** [michaelbromley/angularUtils#350]
Hi guys

I'm developing an angular app that loads my list of users in a table. As quantity of users is big, I need use pagination. But there is one problem:

When I click on next page button (for example num#2) , first, table shows all users (all data load), then (itemPerPage) filter apply.

    <tr dir-paginate=" x in user | filter : searchFunction | itemsPerPage : 15">
    <td>{{x.id}} </td>
    </tr>
    <dir-pagination-controls max-size="15" direction-links="true" boundary-links="true" >
    </dir-pagination-controls> 

Any suggestion will be appreciated ...

**Comment by michaelbromley** [comment]
Not sure without knowing more about your code. Could it be that the searchFunction filter has something to do with the behaviour? Does it still behave that way if you leave that filter out?

**Comment by FarshadKazemi** [comment]
Dear Michael , Tanks for your answer 

I tested my codes again and noticed that when I load my page (with pagination) in main page (via ngView), this problem occurs. Otherwise it works correctly.

**main.html** --- mainCtrl as Controller

    <div id="ngViewContainer" class="slide" ng-view dir="ltr"></div>

**myPage.html** --- userCtrl as Controller

    <tr dir-paginate=" x in user | filter : searchFunction | itemsPerPage : 15">
    <td>{{x.id}} </td>
    </tr>
    <dir-pagination-controls max-size="15" direction-links="true" boundary-links="true" >
    </dir-pagination-controls> 


**userCtrl**

    app.controller('userCtrl', function ($scope) {
    $scope.user = [
        {"id": 1, "username": "User#1", "name": "Name#1"},
        {"id": 2, "username": "User#2", "name": "Name#2"},
        {"id": 3, "username": "User#3", "name": "Name#3"},
        {"id": 4, "username": "User#4", "name": "Name#4"},
        {"id": 5, "username": "User#5", "name": "Name#5"},
        {"id": 6, "username": "User#6", "name": "Name#6"},
        {"id": 7, "username": "User#7", "name": "Name#7"},
        {"id": 8, "username": "User#8", "name": "Name#8"},
        {"id": 9, "username": "User#9", "name": "Name#9"},
        {"id": 10, "username": "User#10", "name": "Name#10"},
        {"id": 11, "username": "User#11", "name": "Name#11"},
        {"id": 12, "username": "User#12", "name": "Name#12"},
        {"id": 13, "username": "User#13", "name": "Name#13"},
        {"id": 14, "username": "User#14", "name": "Name#14"},
        {"id": 15, "username": "User#15", "name": "Name#15"},
        {"id": 16, "username": "User#16", "name": "Name#16"},
        {"id": 17, "username": "User#17", "name": "Name#17"}
    ];
    });

Also, I removed searchFunction, but nothing changed ...

If you need more details, please give me your email address to send my codes.

**Comment by michaelbromley** [comment]
Hi, I'm afraid I don't have the time to look through your source files. If you are able to reproduce the behaviour in a Plunker demo, then there is a good chance that I can help you out better.

Start with [this](http://plnkr.co/edit/b37IdFFJUokaeSummETX?p=preview) and see if you can reproduce, then save your update and post the link back here.

**Comment by FarshadKazemi** [comment]
Hi again dear Michael , thank you so much for your answer.
I finally solve this issue. The problem was in one of my CSS files. 
I've used below code for animating hover effect :

    .table > tbody > tr { background: #242425; transition: background 0.5s }
    .table > tbody > tr:hover { background: #e5e5e5 }

It takes 0.5s for animation of each row and when I change page, it causes some delay.

:+1: :+1:

**Comment by michaelbromley** [comment]
Glad you got it sorted, thanks for sharing the details of the cause.
