### ISSUE TITLE
Hardcode directive tamplate URL

### ISSUE THREAD

**Issue by achuyan-triggmine** [michaelbromley/angularUtils#354]
**Description of issue**: create a possibility to add template url by using template: require('...')

**Steps to reproduce**: webpack create file bundle.js. How can I upload tampate url?

**Expected result**: template: require('./uiBreadcrumbs.tpl.html'),

**Actual result**:

**Demo**: (for dirPagination, fork and modify this Plunk: http://plnkr.co/edit/b37IdFFJUokaeSummETX?p=preview)

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Hi,

Please see this comment (and surrounding discussion for a way to do this: https://github.com/michaelbromley/angularUtils/issues/332#issuecomment-206788003
