### ISSUE TITLE
pagination directive: the itemsPerPage id argument (id: __default) does not match a registered pagination-id

### ISSUE THREAD

**Issue by UmerIftikhar** [michaelbromley/angularUtils#359]
I have written the following directive, and when I include it directly in to the html file it works perfectly fine. However, when I compile it at run time, it gives this error:
**demo.js:131 pagination directive: the itemsPerPage id argument (id: __default) does not match a registered pagination-id**

		var app = angular.module("tableApp", ['angularUtils.directives.dirPagination']);
		app.directive("w3TestDirective", function() {

			return {

				template: [
						'Enter the Table Name:    <input type="text" name="table_ID" ng-model="tableName"><br>',
						'Coulmn id:    <input type="text" name="column_ID" ng-model="columnID"><br>',
						'Coulmn name:  <input type="text" name="column_Name" ng-model="columnName"><br>',
						'<br>',
						'<button ng-click="myFunction()">Add a New Coulmn!</button>',
						'<br>',
						'<br>',
						'<h2>{{tableName}}</h2>',
						'<table id="myTable" width="100%" class="table table-striped table-bordered datatable">',
						'<thead>', 
						'<tr>',
						'<th ng-repeat="header in myColumns">{{header}}</th>',
						'</tr>',
						'</thead>',
						'<tbody>',
						'<tr dir-paginate="row in MyRecCollection | itemsPerPage: 7 | filter:mySearchColumns">',
						'<td ng-repeat="header in myColumns">{{ row[header] }}</td>',
						'</tr>',
						'</tbody>',
						'</table>',             
						'<dir-pagination-controls max-size="5" direction-links="true" boundary-links="true" ></dir-pagination-controls>'                

					].join(''),

				controller: function($scope, $element,$http) {
				$scope.tableName = "TABLE NAME";            
				$scope.columnID = "";
				$scope.columnName = "";
				$scope.searchID = "";
				$scope.searchName = "";
				$scope.count = 0;
				$scope.myColumns = [];
				$scope.mySearchColumns = {};

				$http.get('http://www.w3schools.com/website/Customers_MYSQL.php').success(function (data) {

						$scope.MyRecCollection = data;
						console.log($scope.MyRecCollection[0]);
				});

				$scope.myFunction = function() {

						if( ($scope.columnName != "" && $scope.columnID != "") ){

								if($scope.myColumns.indexOf($scope.columnID) == -1){
									$scope.myColumns.push($scope.columnID);
								}       

						}
					//console.log("HELLO");
				}

				$scope.mySearchFunction = function() {

						if( ($scope.searchName != "" && $scope.searchID != "") ){

										$scope.mySearchColumns[$scope.searchID] = "";

						}       

				}       

				}   

			};

		});

Code when the user clicks on certain button to add the table:

		angular.injector(['ng', 'myApp']).invoke(function ($compile) {
			var $scope = angular.element(document.body).scope();
			var $compiled = $compile("<w3-test-directive></w3-test-directive>")($scope);
			$scope.$digest();

		});

When I call this function, I get the error message.

**Comment by ram535ii** [comment]
+1 I've got exactly this issue. Sadly I can't add any additional details.

**Comment by ram535ii** [comment]
@UmerIftikhar upgrade to version 0.11.1. A fix was attempted in 0.11.0 but has been reverted in the newer version. See #313 for more details.

**Comment by michaelbromley** [comment]
@ram535ii Yes, that's the solution. Thanks for sharing that!
