### ISSUE TITLE
uiBreadcrumbs: access to $resolve keys not working with angular-ui-router 1.0.0

### ISSUE THREAD

**Issue by KeithGillette** [michaelbromley/angularUtils#360]
**Description of issue**:
Attempting to use UI-Breadcrumbs with Angular UI-Router 1.0.0 fails to display data from $resolve keys, though static text and simple angular expressions work.

**Steps to reproduce**:
Replace AngularJS & Angular UI-Router script references in [uiBreadcrumbs demo Plunkr](http://plnkr.co/edit/bBgdxgB91Z6323HLWCzF?p=preview) index.html with:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0/angular.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/1.0.0-alpha.5/angular-ui-router.min.js"></script>

```

**Expected result**:
uiBreadcrumbs Plunkr continues to work with angular-ui-router 1.0.0 (and Angular1.5).

**Actual result**:
uiBreadcrumbs directive displays no data.

**Comment by michaelbromley** [comment]
Hi,

I'm afraid I no longer use this directive in any of my live projects, so I have little incentive to keep it up to date. I just added a note to the readme to this effect.

What this means is that it is very unlikely that I will find the time to debug and fix this issue. Sorry to have to say it, but I think you will appreciate an honest answer.

If this is a critical issue for you or your business, and you decide to invest the time to debug and fix, then I will welcome a pull request to this repo.

**Comment by KeithGillette** [comment]
I definitely appreciate the direct reply. The breadcrumbs feature is not a high-priority for us right now, but if we choose to build on your excellent work to implement it after Angular UI-Router 1.0.0. exits beta, we'll definitely contribute the fixes back via a pull request.
