### ISSUE TITLE
max-size reduction not working please help tried usin 0 and 1 , no effect at all

### ISSUE THREAD

**Issue by RasaqAgbas** [michaelbromley/angularUtils#361]
-- Michael 

=======
(Delete the above. Fill in the rest as applicable)

**Description of issue**: max-size does not change after changing the number

**Steps to reproduce**:

**Expected result**: only direction link and boundary link show up

**Actual result**: all links show up

**Demo**: (for dirPagination, fork and modify this Plunk: http://plnkr.co/edit/b37IdFFJUokaeSummETX?p=preview)

Any relevant code:
```
 <dir-pagination-controls
                                            max-size="0"
                                            direction-links="true"
                                            boundary-links="true" >
                                            </dir-pagination-controls>

```

**Comment by michaelbromley** [comment]
Hi,

From the readme: 

> max-size (optional, default = 9) Specify a maximum number of pagination links to display. The default is 9, and the minimum is 5 (setting a lower value than 5 will not have an effect).

If you want only the direction and boundary links, you need to use a custom template.

**Comment by RasaqAgbas** [comment]
ok thanks
