### ISSUE TITLE
dirPagination to show loading image when navigate from page 1 to page 2

### ISSUE THREAD

**Issue by dhiman252** [michaelbromley/angularUtils#365]
I am using the latest version for angular 1.5 and did not found anything related to how to show a loading image when a user navigates from one page to another, is there any attribute from which I can call the controller function to show a loading image ?

**Comment by michaelbromley** [comment]
This is out of the scope of this module - it is something you just need to implement yourself.

Assuming you are using server-side paging, then you already know when a loading indicator should be shown - show it when you fire the request to get the next page of data, and hide it when that request returns with the data.
