### ISSUE TITLE
filter only filters on the current page

### ISSUE THREAD

**Issue by ifasina** [michaelbromley/angularUtils#369]
**Description of issue**: When I try to filter the table generated via pagination, it only filters the current page. For example, there is a name "John" on page 2 of the pagination, when I am on page 1 and I do a search for "John" it doesn't show up. If I do the same search on page 2, it shows up just fine.

**Steps to reproduce**:

**Expected result**: It should filter through all pages

**Actual result**: Only filters the current page of pagination

Any relevant code:
```
    <table class="table table-stiped table-hover">
       <th>Name</th>
       <th>Level</th>
       <tr dir-paginate="char in chars | itemsPerPage: 10 | filter:searchQuery">
           <td>{{char.name}}</td>
           <td>{{char.level}}</td>
        </tr>
    </table>
```

**Comment by michaelbromley** [comment]
See https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#why-does-my-sort--filter-only-affect-the-current-page

**Comment by ifasina** [comment]
Oh my, that's embarrassing. Thank you.

**Comment by michaelbromley** [comment]
No worries!
