### ISSUE TITLE
dirPagination: When Page changes the button loses functionality.

### ISSUE THREAD

**Issue by solankesanket** [michaelbromley/angularUtils#370]
![page 1](https://cloud.githubusercontent.com/assets/18712702/16830026/f412219c-49b9-11e6-8fdc-343f00ae692e.PNG)
Hi,
    I'm using dirPagination in a table to paginate the table data, table data includes some buttons and links which is used to open some pop up boxes. When dirPagination is used and go on next page and click on the same button or a link it does not work. [highlighted part is button]
I'm using "bPopup" api for pop up boxes which is written in JQuery.

**Comment by michaelbromley** [comment]
Hi,

I can't really offer any help without seeing a bit of code. Please try to include relevant parts of your view and controller code.
