### ISSUE TITLE
dirPagination : Angular material conflict

### ISSUE THREAD

**Issue by dhiman252** [michaelbromley/angularUtils#374]
**Description of issue**: Including the angular material library cases the pagination directive to pause while switching the records from one page to another

**Steps to reproduce**: create a simple page and include the angular material library and the module in you app using the dirPagination,now switch across the pages 

**Expected result**: There should not be any delay in displaying the records.

**Actual result**: It must not show any delay in showing records when switching pages.

**Demo**: https://plnkr.co/edit/8ByRaRbvZJMEnW4FakoO?p=preview

**Comment by michaelbromley** [comment]
This is caused by the css `transition` property on the `.post` class. Check out this thread for more information: https://github.com/michaelbromley/angularUtils/issues/226
