### ISSUE TITLE
dirPagination: Multiple filters with on of them being a date range. 

### ISSUE THREAD

**Issue by costellos2010** [michaelbromley/angularUtils#385]
I'm using jquery ui for the date picker, and I'm trying to make this tool work with it. So I saw the post with multiple filters, and have that working, but when I try and use my jquery ui field, it shows no results. I think the problem is that it is searching for items that exactly match the unix time stamp, and not ones that fall between the start date and end date. If you need code let me know.

**Comment by michaelbromley** [comment]
Hi,

Sorry about the delay.

As far as I can tell, this is not an issue with my library, but rather a broader question about how to do a specific thing in Angular. Try StackOverflow, since I'm afraid I don't have time to help on this one.
