### ISSUE TITLE
Wrong Path being used file:// instead http:// is this because the script is not running from a hosted server?

### ISSUE THREAD

**Issue by jasonatt** [michaelbromley/angularUtils#386]
I am trying to integrate the disqus directive 

I am running into a few issues due to the way my app is set up. There is a line in the script where the embed .js is called like this

`dsq.src = '//' + scope.config.disqus_shortname + '.disqus.com/embed.js';`

This is returning the following error in the console:

`GET file://mywebsitename.disqus.com/embed.js net::ERR_FILE_NOT_FOUND`

This is happening because the url is returning as file:// and to fix it needs to be http://

I changed the url directly in the line of code and it works however the script calls further external files and injects them in the dom and these also return as file:// hence I get the same error.

Ideas?

**Comment by michaelbromley** [comment]
Hi,

What is the use case where the app is being run from `file://`? Is it an Electron app or something?

The current method is like that so that it works with both http & https. As for the further scripts, this would be done by the Disqus JavaScript, which I do not have any control over.

**Comment by jasonatt** [comment]
Hi Michael,

Yes figured that out thank you for replying.
