### ISSUE TITLE
[Feature Request] Nested repeats in a single pagination. dirPagination 0.11.1

### ISSUE THREAD

**Issue by cadaniel** [michaelbromley/angularUtils#389]
I'm looking to create a nested loop for pagination.
My Json look something like 

```
items:[
  { name:"name",
    sublist:["subitem1", "subitem2",..],
  ....
  }
]
```

And I want to display each sub item on it's own row with other various information. The sublist length is not consistent, and I want to have, let's say 5 items on each page. 

Any relevant code:
Here's what I have

```
    <div data-dir-paginate="user in users.users | itemsPerPage:5">
        <div style="font-size: large; margin-bottom: 1em;" class="row" data-ng-repeat="device in user.devices">
            <div class="col-md-3" ><span data-ng-if="$first">{{user.username}}</span></div>
            <div class="col-md-3" >{{device}}</div>
            <div class="col-md-1" >{{user.keys}}</div>
            <div class="col-md-1" ><a>view</a></div>
            <!--TODO Fix real date-->
            <div class="col-md-2">3:44pm 22-12-16</div>
            <div class="col-md-1" style="margin-right: 0"><a>view</a></div>
        </div>
    </div>
```

Basically I want to paginate the top div, with 5 rows per page of the following div.

**Comment by michaelbromley** [comment]
Hi,

I'm not quite clear on what you are asking here. Are you suggesting a new feature for the pagination module (I am guessing so from the title of the issue)? If so, can you describe it exactly?

Or is this a request for help implementing a specific feature?

**Comment by cadaniel** [comment]
A bit of both? Sorry this isn't the right place to ask.

My problem is showing a list of users, and a user has devices they've logged in on. There is no limit to the number of devices, and is not consistent. I want to show one row for every device. This works into a nested ng-repeat. One over all the users, and the second over all the devices. What I would like to do is paginate so that only, lets say, 10 rows show on a page. This could be one user, it could be 10 users on a page. But if I paginate by 10 users, it could be 50 rows long. Is this possible with the current api?

**Comment by michaelbromley** [comment]
Ok. I think I get it. So you want to paginate the users - that's simple. Do you also want to paginate the devices list on each user row?

**Comment by ptitdje45** [comment]
Just to ask something similar, is it possible to replace the second dir-paginate with a ng-repeat ?

Thanks
