### ISSUE TITLE
Disqus: help needed

### ISSUE THREAD

**Issue by SET001** [michaelbromley/angularUtils#392]
I don't understand what should be the values for `disqus_identifier` and `disqus_url`.
Let's say I have a page with news and I need a new comments thread for each news item. Then I'm trying this configuration:

```
$scope.disqusConfig = {
		disqus_shortname: 'dusqus_shortname',
		disqus_identifier: $scope.article.id,
		disqus_url: '/#/news/'+$scope.article.id,
		disqus_title: $scope.article.title,
	}
```

but it result's in all comments being shown for each news item. Can you give some example?

**Comment by SET001** [comment]
I have make this work in this way:
```
		disqus_shortname: 'avalon-project',
		disqus_identifier: $scope.article._id,
		disqus_url: 'http://127.0.0.1:3000/#!/news/'+$scope.article.id,
		disqus_title: $scope.article.title,
```

**Comment by michaelbromley** [comment]
Hi,

Glad you got it solved. To confirm why your solution worked, here is a bit from the disqus docs:

> To make sure the right thread is always displayed, you should define on your page, using an absolute URL, this.page.url = 'http://example.com/helloworld.html';
Please note that an absolute URL is required for the this.page.url variable. Using a relative URL for this variable may prevent Disqus from loading successfully on the page.
