### ISSUE TITLE
filtering asynchronous data

### ISSUE THREAD

**Issue by spider6282** [michaelbromley/angularUtils#395]
I'm using the asynchronous setup and works as expected. I want to use a search filter as well but it filters only the data in the current page. The order of the filter as suggested is in the right order.

`<div dir-paginate="item in items | filter:dearch | itemsPerPage: itemsPerPage" total-items="totalItems" current-page="pagination.current">
        {{item.name}}
    </div>`

Is it possible to search filter asynchronous data? Any help would be appreciated.

**Comment by michaelbromley** [comment]
Yes, it is possible, but the filtering would have to be implemented on the server side - Angular can only filter the data it can see (in this case, the current page). If the rest of the data from all the other pages is sitting up there on the server, there is no way for Angular to know about it.

So in this case you don't need to user a filter in the `dir-paginate` expression. Assuming your server API supports filtering, you need to pass the filter query when you make the HTTP call.
