### ISSUE TITLE
dir-pagination-controls not showing correctly in bootstrap4

### ISSUE THREAD

**Issue by motasimali** [michaelbromley/angularUtils#396]
Hi!

I have used dirPagination in my application.It works fine with bootstrap 3.3.7, when I use bootstrap 4 the pagination still works fine but the pagination controls align vertically.I have attached a picture for reference + my express javascript(html+expresscode).
![pagination](https://cloud.githubusercontent.com/assets/22102264/18610947/f271cf0a-7d43-11e6-8493-172a0b3a972e.jpg

)

-- Michael

**Comment by michaelbromley** [comment]
The default template is built with Bootstrap 3 in mind. If you need to support Bootstrap 4, you can always [write a custom template](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#writing-a-custom-pagination-controls-template)

Once bootstrap 4 is officially released, I may update the default template.

**Comment by nahidhasanswe** [comment]
First I am sorry. Cause I am a beginner developer at AngularJs. I really love dirPagination. I am also face this problem with bootstrap v4. I will try to resolve the problem for compatible with bootstrap v4. So i want provide the template for pagination. If anything is wrong please forgive me. 

[Here is my template code](https://github.com/nahidhasanswe/Appraisal-System-Online/blob/master/Client%20Side/View/dirPagination.tpl.html)

**Comment by rsamala-osius** [comment]
Thanks, @nahidhasanswe , its working for me

**Comment by alexlarraga1** [comment]
In class shearch dirPaginationsControlsTemplateInstaller and replace the code.
`function dirPaginationControlsTemplateInstaller($templateCache) {
        //-- Bootstrap 3.3.* --//
        //$templateCache.put('angularUtils.directives.dirPagination.template', '<ul class="pagination" ng-if="1 < pages.length || !autoHide"><li ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == 1 }"><a href="" ng-click="setCurrent(1)">&laquo;</a></li><li ng-if="directionLinks" ng-class="{ disabled : pagination.current == 1 }"><a href="" ng-click="setCurrent(pagination.current - 1)">&lsaquo;</a></li><li ng-repeat="pageNumber in pages track by tracker(pageNumber, $index)" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == \'...\' || ( ! autoHide && pages.length === 1 ) }"><a href="" ng-click="setCurrent(pageNumber)">{{ pageNumber }}</a></li><li ng-if="directionLinks" ng-class="{ disabled : pagination.current == pagination.last }"><a href="" ng-click="setCurrent(pagination.current + 1)">&rsaquo;</a></li><li ng-if="boundaryLinks"  ng-class="{ disabled : pagination.current == pagination.last }"><a href="" ng-click="setCurrent(pagination.last)">&raquo;</a></li></ul>');
        //-- Bootstrap 4.* --//
        $templateCache.put('angularUtils.directives.dirPagination.template', '<ul class="pagination" ng-if="1 < pages.length || !autoHide"><li class="page-item" ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == 1 }"><a class="page-link" href="" ng-click="setCurrent(1)">&laquo;</a></li><li class="page-item" ng-if="directionLinks" ng-class="{ disabled : pagination.current == 1 }"><a class="page-link" href="" ng-click="setCurrent(pagination.current - 1)">&lsaquo;</a></li><li class="page-item" ng-repeat="pageNumber in pages track by tracker(pageNumber, $index)" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == \'...\' || ( ! autoHide && pages.length === 1 ) }"><a class="page-link" href="" ng-click="setCurrent(pageNumber)">{{ pageNumber }}</a></li><li class="page-item" ng-if="directionLinks" ng-class="{ disabled : pagination.current == pagination.last }"><a class="page-link" href="" ng-click="setCurrent(pagination.current + 1)">&rsaquo;</a></li><li class="page-item" ng-if="boundaryLinks"  ng-class="{ disabled : pagination.current == pagination.last }"><a class="page-link" href="" ng-click="setCurrent(pagination.last)">&raquo;</a></li></ul>');
    }`

Regards

**Comment by utkarsh-pathak** [comment]
@alexlarraga1, the above code does not work for me.
I am facing the same issue when I update my project from Bootstrap3 to Bootstrap4.

**Comment by evanVerinomics** [comment]
@alexlarraga1, the above code does work for me! 
replace the dirPaginationControlsTemplateInstaller() function from the dirPagination.js file and the solution for bootstrap 4 works. Thanks!
