### ISSUE TITLE
Custom row on the result set

### ISSUE THREAD

**Issue by vraghu1983** [michaelbromley/angularUtils#397]
**Description of issue**: Pagination works just great - however - have a small requirement of the text to be collapsed and shown on click of a button - so did that. 
However - the user readability is bad - so want to show the text on a separate row - how do i do this ? 
Any additional <tr> introduced and paging goes for a toss or results do not get shown. 

**Steps to reproduce**: Just the normal paging

**Expected result**: Working as expected. 

**Actual result**:

**Demo**: (for dirPagination, fork and modify this Plunk: http://plnkr.co/edit/b37IdFFJUokaeSummETX?p=preview)

Any relevant code:
```
                            <tr dir-paginate="ticket in tickets|orderBy:sortKey:reverse|filter:search|itemsPerPage:10">
                                <td>{{ticket.processed}}</td>
                                <td>{{ticket.ticket_rid}}</td>
                                <td>{{ticket.date_created | date : 'dd/MM/yyyy'}}</td>
                                <td>{{ticket.category_text}}</td>
                                <td>{{ticket.purpose_request}}</td>
                                <td>{{ticket.origin}}</td>
                                <td>{{ticket.email_lower}}</td>
                                <td>{{ticket.queuename}}</td>
                                <td>
                                    <button ng-if="ticket.expanded" ng-click="ticket.expanded = false">-</button>
                                    <button ng-if="!ticket.expanded" ng-click="ticket.expanded = true">+</button>
                                </td>
                                <td ng-if="ticket.expanded" ng-repeat-end="">
                                    <p ng-bind-html="ticket.itemcontents"></p>
                                </td>
                            </tr>
```

Want the last piece of the code in a separate <tr> - but not working as intended.

**Comment by michaelbromley** [comment]
Hi,

It sounds like you could achieve what you are attempting with the `-start` and `-end` syntax. See https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#special-repeat-start-and-end-points

```
<tr dir-paginate-start="ticket in tickets|orderBy:sortKey:reverse|filter:search|itemsPerPage:10">
  <!-- first row -->
</tr>
<tr dir-paginate-end>
  <!-- second row-->
</tr>
```

**Comment by vraghu1983** [comment]
Awesome - works like a charm ! - many thanks
