### ISSUE TITLE
angular-utils-ui-breadcrumbs is not working with Production code(bundled version of code)

### ISSUE THREAD

**Issue by vittal288** [michaelbromley/angularUtils#399]
Description:
Module Name: **angular-utils-ui-breadcrumbs**
Issue: This directive is not working with prod code(compressed or bundled version of JS code and which is generated from gulp tool)
Issue Description :  Template "directives/uiBreadcrumbs/uiBreadcrumbs.tpl.html " OR custom template which is mentioned in one fo attribute  **template-url="app/components/common/uiBreadcrumbs.html"** is not working in PROD code but it is fine working with local unbundled or uncompressed of JS file.

Error: **404 error i.e file directives/uiBreadcrumbs/uiBreadcrumbs.tpl.html OR app/components/common/uiBreadcrumbs.html is not found because all JS,HTML files will be merged into one file using gulp.**

Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can:

- Title: Please indicate the module in question, e.g. "dirPagination: X is broken when Y"
- If reporting on dirPagination, please include the version you are using (can be found in the package.json / bower.json file)
- If you are able to reproduce your issue on Plunker, this will vastly increase the chances of a rapid response from me.

**Comment by michaelbromley** [comment]
The error just means the template file is not being found. It sounds like a problem with the way you have your build configured. How do you handle templates in prod? Are you pre-loading them into the template cache, or loading them async via http?

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, feel free to re-open.
