### ISSUE TITLE
dirPagination(V 0.11.1) : wait till Function() is Performed before PageChange/or remember Edited Values

### ISSUE THREAD

**Issue by atodicebear** [michaelbromley/angularUtils#402]
**Description of issue**:
If the page is changed all Edited Values in TextAreas/TextFileds are removed.
**Steps to reproduce**:
Create Table with 2 Pages->Input Text Field with some Input->Change Page-> Edited values are removed.
**Expected result**:
Implement Remember of Values/Form?

This is maybe not a Problem for here and I dont know if it can be Implemented here.
But would be a nice thing.
Otherwise would be my Question be how to do a Workaournd.
Is there somehting like wait for response of a Function before page is Changed?
Kinda:
```
.html
<dir-pagination... onPageChange=myFunctio().$waitResponse?..>
.js
myFunction(){
saveAllValues of actual Page somewhere
return itsDone you can Change the Page
}
```
At the moment I have a Function which Iterate all X Fields over all Y Pages and saves the Values but the new Edits are removed on pageChange so it saves only the Edits on the actual Page.

Thanks for your Work.

**Comment by michaelbromley** [comment]
Hi,

I think I get the problem. Would this be an acceptable work-around:

1. Create an object to hold the values which you wish to persist between page changes.
2. When you load a page of data, create a unique key to represent each row in the list (if your list items have an id, use hat, else you could generate one based on the current page + index in the ngRepeat) and store the value from the text input in the hash object from step 1 with that unique key.
3. When you move to another page, and then back to the original one, you can read the previously-stored values from the hash object.

**Comment by atodicebear** [comment]
Hey,

thank you for Response. That is what Iam actually trying to do. But other Problems occure but there are not connected to this Package.

Still I think for Futore use would something like mentioned a Function "wait for Page Change till you get a Response" extra method nice.

But at the moment can be Closed I think.
Have a nice Day.
