### ISSUE TITLE
Getting object count after filter.

### ISSUE THREAD

**Issue by PringPring** [michaelbromley/angularUtils#406]
After filtering the records how to get the current object count on the current controller.
[stackoverflow question](https://stackoverflow.com/questions/39825212/how-to-get-array-count-of-filtered-result-on-dir-pagination)

**Comment by Aides359** [comment]
You can access the filtered result to a new variable with 

    <li dir-paginate="meal in filteredMeals = (meals | filter:q) 
         | itemsPerPage: pageSize" current-page="currentPage">

and then access `filteredMeals.length`.

**Comment by Aides359** [comment]
also duplicate of #328

**Comment by michaelbromley** [comment]
@Aides359 exactly. Thanks for helping out 👍
