### ISSUE TITLE
Cannot use dir-paginate

### ISSUE THREAD

**Issue by ikwijaya** [michaelbromley/angularUtils#409]
Dear Team,

I have a little project with many datas from server, and i use angular module for smooth loading and filter data. But i have some problem with my code, such as 
1. If i use ng-repeat this code is working normally, but if i change ng-repeat to dir-paginate no result can made.
`<tr dir-paginate="adb in dataADBs | orderBy:sortKey:reverse | filter:search | itemPerPage: pageSize">
          <td>{{ $index+1 }}</td>
          <td>{{ adb.em_nik }}</td>
          <td>{{ adb.em_name }}</td>
          <td>{{ adb.em_account }}</td>
        </tr>`

`<tr ng-repeat="adb in dataADBs | orderBy:sortKey:reverse | filter:search">
          <td>{{ $index+1 }}</td>
          <td>{{ adb.em_nik }}</td>
          <td>{{ adb.em_name }}</td>
          <td>{{ adb.em_account }}</td>
        </tr>`
1. And why i cant load pagination.tpl.html on my file??

This is mycode please for review
https://plnkr.co/edit/Ktv0427yIgUaKZItyBBE?p=preview

Thanks for your attention.
-- IkW

**Comment by michaelbromley** [comment]
Hi,

Looks like you just have a typo - you forgot the "s" in `itemsPerPage`.

**Comment by ikwijaya** [comment]
Hi Sir,

Thanks a lot. And one problem can solve yet, 
@michaelbromley : why the pagination cannot show?

![capture](https://cloud.githubusercontent.com/assets/23114902/19805162/f4f1b7f4-9d3c-11e6-863a-3566aeaf61fa.PNG)


any problem with my code?

thanks,
ikw

**Comment by michaelbromley** [comment]
Hi,

Yes, the problem is that the controls are declared outside the scope of the `ng-app`. If you move your `ng-app` declaration higher up the DOM tree, for example on the <body> element, then it will work: https://plnkr.co/edit/Im6P5RMV46ZZApHVz7ca?p=preview
