### ISSUE TITLE
Will this work even in thousands or millions of data in dirPagination?

### ISSUE THREAD

**Issue by badcoder28** [michaelbromley/angularUtils#413]
Hi, 

I am curious and i am earnestly asking you question regarding the program performance. Will the `dirPagination` be suitable for thousands or even millions of data or larger application?

**Comment by michaelbromley** [comment]
Hi,

The performance limitations would not be directly related to this library, rather you would simply run into memory & processor limits if you try to page over millions of items in memory. Hundreds or even low thousands would probably be fine, but once you get into tens-of-thousands +, you would be much better off to shift the paging logic onto the server, which this library supports. See [this section of the readme on server side paging](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#working-with-asynchronous-data)
