### ISSUE TITLE
Question regarding a custom template

### ISSUE THREAD

**Issue by stinkyfruit** [michaelbromley/angularUtils#414]
Hi I'm working with dirPagination, the latest version as of 12/6/16. I've injected a custom template, but want to add custom classes based off logic I added in my controller. Basically instead of a square around the numbers, I added circles. I'm having issues with adding logic from my controller into the custom template. Can you advise? 

Thanks in advance!
Kristen

**Comment by michaelbromley** [comment]
Hi,

What you describe sounds totally doable. Would you be able to post some code of what you have implemented so far?

**Comment by stinkyfruit** [comment]
Sure!

So I copied over the template:

<ul class="pagination" ng-if="1 < pages.length || !autoHide">
    <li ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == 1 }">
        <a href="" ng-click="setCurrent(1)">&laquo;</a>
    </li>
    <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == 1 }">
        <a href="" ng-click="setCurrent(pagination.current - 1)">&lsaquo;</a>
    </li>
    <li ng-repeat="pageNumber in pages track by tracker(pageNumber, $index)" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == '...' }">
        <a href="" ng-click="setCurrent(pageNumber)">{{ pageNumber }}</a>
    </li>

    <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == pagination.last }">
        <a href="" ng-click="setCurrent(pagination.current + 1)">&rsaquo;</a>
    </li>
    <li ng-if="boundaryLinks"  ng-class="{ disabled : pagination.current == pagination.last }">
        <a href="" ng-click="setCurrent(pagination.last)">&raquo;</a>
    </li>
</ul>


but added styling that's a little different. 

configed the template this way: 

myApp.config(function(paginationTemplateProvider) {
    paginationTemplateProvider.setPath('path/to/dirPagination.tpl.html');
});

and i have a separate component where I added the logic: 

controller() {

function bigCircle(pageNumber) {
  if (pageNumber > 9) {
    return class1;
  } else if (pageNumber > 99) {
    return class2;
  }
}
}
so I want to put the logic into the ng-class of the template, but am having trouble connecting it to my component/controller to the template

**Comment by michaelbromley** [comment]
[First off - a little formatting hint: you can make the code blocks look nice the using three back ticks (`` ``` ``) at the start and end (see [docs](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown))]

Okay, from that code I don't see how the function `bigCircle()` is being exposed to your template. The template can only see members of the controller's `$scope` object, so one way to expose the method would be to define is thus:

```JavaScript
controller($scope) {
  $scope.bigCircle = function(pageNumber) { 
    // ... your code
  };
}
```

Does that help?

**Comment by stinkyfruit** [comment]
Thanks for the tip.

It makes sense but I guess I'm confused on how the template I created is
connected to a controller. If it is, I can't find it.

**Comment by michaelbromley** [comment]
Ah actually I made a mistake - I have not been working with Angular 1.x for many months so I forgot exactly how this library was implemented ;)

So, by default there is only a specific, restricted API available in the custom template, as documented [here](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#writing-a-custom-pagination-controls-template), and the directive uses an isolated scope, which means it will not inherit methods from the parent controller. I guess this is what you have discovered so far...

So, one way to access parent scope methods would be to explicitly use the `$parent` property:

```JavaScript
controller($scope) {
  $scope.bigCircle = function(pageNumber) { 
    // ... your code
  };
}
```

```HTML
<li ng-class="$parent.bigCircle(pagination.current)">...</li>
```

**Comment by stinkyfruit** [comment]
I hope to be using angular 2 soon!

That's perfect. Thanks a lot. I appreciate you taking the time out to help
someone like me :)

**Comment by michaelbromley** [comment]
>  to help someone like me :)

All I know about you is that you use my library, needed help, and asked nicely. That's enough to qualify ;)
