### ISSUE TITLE
dirPagination: Pagination Controls w/Ionic

### ISSUE THREAD

**Issue by ethanmay** [michaelbromley/angularUtils#416]
**Description of issue**: It seems that something is preventing the pagination controls from accessing their scoped functions when I implement dirPagination in Ionic. I did a bit of debugging and found that the `scope.setCurrent` function does not fire when the pagination buttons are clicked.

**Steps to reproduce**: See Plunk for my exact implementation.

**Expected result**: Pagination buttons should work.

**Actual result**: Pagination buttons don't work.

**Demo**: http://plnkr.co/edit/X7hmztx8RrxqGGQjSg2N

Great library! Thanks for your work.

**Comment by michaelbromley** [comment]
Hi,

Thanks for the demo of the issue. I'm not sure why it doesn't work, but I think there is something that Ionic is doing which may be intercepting the click and not causing the `setCurrent` to fire.

I changed the markup of your custom template to:
```HTML
  <div class="button button-light"  ng-click="setCurrent(pageNumber)" ng-repeat="pageNumber in pages track by tracker(pageNumber, $index)" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == '...' }">
    <span>{{ pageNumber }}</span>
  </div>
```

- note that I moved the `ng-click` up to the parent button div. This makes it work.

So, I think we can put it down the the peculiarities of how Ionic is implemented.
