### ISSUE TITLE
Dirpagination: Pagenum and Pagesize  same onchange function 

### ISSUE THREAD

**Issue by matt212** [michaelbromley/angularUtils#417]
**when changing number of records to display(itemperpage) pageChangeHandler is called which is also called when we change number of pages with same param **:

`on-page-change="pageChangeHandler(newPageNumber)" `

**Demo**: (for dirPagination, fork and modify this Plunk: http://embed.plnkr.co/TvWahO/)

Please check console of above plunker 
and check line 49 in script.js file called both times 

how to differentiate between pagenum and pagesize change event !

**Comment by matt212** [comment]
I wanted to set pagesize dynamically after i get value from server 
but since when i do that pageChangeHandler is fired since is mentioned in itemsPerPage: pageSize" in 
`<tr dir-paginate="enums in mrole | filter:q | itemsPerPage: pageSize" total-items="totalUsers" current-page="currentPage">`
hence i request moves one offset further 
and i got two request 0 offset and 1 offset !
Any suggestion to resolve this issue

**Comment by michaelbromley** [comment]
Okay, I get the problem. One workaround could be to watch the value of `currentPage`, and only when that changes do you fetch more data from the server.

**Comment by matt212** [comment]
Ok , I got a hang of it , Correct me if i might be going into wrong direction with below codebase .

```
if($scope.currentPage<=1)
{
base.pageno = 0;
}
else
{
base.pageno = num;
}
```
wherein num is value is get from pagechangehandler
and base.pageno is object, I am sending to api

**Comment by michaelbromley** [comment]
Does the above code work as intended? It is not exactly what I had in mind.

I'll elaborate a bit:

My idea is that you don't event use the `on-page-change` callback at all, since it is being called more than you need. So you can just directly watch the value of `$scope.currentPage` and make new API calls when it changes:

```JavaScript
$scope.watch('currentPage', function(newVal, oldVal) {
  base.pageno = newVal;
  base.pageSize = $scope.pageSize;
  base.searchparam = 'NA';
  Todos.getpaginate(base)
        .success(function(data) {
            $scope.mrole = data.rows;
            $scope.totalUsers = data.count;
        });
```

**Comment by matt212** [comment]
Hi @michaelbromley ,
 
Thanks for your Time and Patience for understanding !

Ok, isolate the on-page-change altogether now, I fully understand your approach 
I have one query, please refer below case scenario
Since we had remove "on-page-change" .

`on-page-change="pageChangeHandler(newPageNumber)"`

Whenever we increase and decrease the input pagesize there should be api call with updated "limit ".
like :-
select * from table limit [pagesize]

How can i achieve this , should i use ng-change on input tag?

Please suggest .

Thanks in advance .

**Comment by michaelbromley** [comment]
No problem!

You have a couple of options for this: 
* you could use `ng-change` as you suggested
* you could use a `$scope.$watch()` on the page size variable, just like with the currentPage example above.

I can't think of any major reason to prefer one approach over the other, so use whichever makes most sense to you.

**Comment by matt212** [comment]
Hi @michaelbromley , 

Thanks for clarification .
So Consolidated solution would be below Codebase it seems , will try and get back on this 
with isolation of "on-page-change" event.

```
$scope.$watch('currentPage', function(newVal, oldVal) {

            base.pageno = newVal;
            base.pageSize = $scope.pageSize
            base.searchparam = 'NA';
            Todos.getpaginate(base)
                .success(function(data) {
                    $scope.mrole = data.rows;
                    $scope.totalUsers = data.count;
                })
        };


        $scope.$watch('pageSize', function(newVal, oldVal) {

                base.pageno = $scope.currentPage;
                base.pageSize = newVal
                base.searchparam = 'NA';
                Todos.getpaginate(base)
                    .success(function(data) {
                        $scope.mrole = data.rows;
                        $scope.totalUsers = data.count;
                    })
            };
```
