### ISSUE TITLE
.popover() function not working on page change

### ISSUE THREAD

**Issue by ankit00000** [michaelbromley/angularUtils#424]
Hi, thank you very much for this awesome lib!
-Ankit

**Description of issue**:
Hi I am using Bootstrap PopOver but it show up only on this first page, PopOver stops working on page change.

I have below code on the HTML page, to initialize the .popover() function on all the elements with data-toggle = "popover"
<script type="text/javascript">
 $(document).ready(function () {
       $('[data-toggle="popover"]').popover();
    });
</script>

I guess I have to reinitialize the above .popover() function on page change. but don't know how, could you please let me know how to reinitialize the .popover() function again on setCurrent() call.

Thanks

**Comment by michaelbromley** [comment]
Yes, I can see why this breaks from the code snippet provided. The `.ready()` function will only fire once on the first load.

One idea (a bit hacky in my opinion) is to use the `on-page-change` function on `<dir-pagination-controls>` to re-run the jQuery .popover() plugin once the list has updated. You might need to put it inside a `setTimeout()` depending on the timing of the DOM update.

A better idea would be to create a custom `pop-over` directive which wraps up the jQuery plugin and simply runs the `.popover()` method on the element it is attached to.

**Comment by ankit00000** [comment]
WOW! It worked for me (the bit hacky idea).

I am new to AngularJS so I will try to implement the second approach later.

Many Thanks!!
