### ISSUE TITLE
dirPagination: pagination not updating after filtering

### ISSUE THREAD

**Issue by lsc1025** [michaelbromley/angularUtils#429]
The pagination controls won't update after put stuff in the search textbox, ie. if you search for Asad, the data did get filtered but the pages didn't get rearranged.

**Expected result**:
Pages rearranged

**Actual result**:
Pages were filtered individually

**Demo**:
http://plnkr.co/edit/aco9fM?p=preview

Thanks for your time!

**Comment by michaelbromley** [comment]
See [this FAQ answer](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#why-does-my-sort--filter-only-affect-the-current-page)

 - basically the `paginate` pipe needs to go after the filter.
