### ISSUE TITLE
Filtering with Checkbox

### ISSUE THREAD

**Issue by houssem-yahiaoui** [michaelbromley/angularUtils#434]
I'm using the directive to a search page i'm having thus, in order to filter i need to use checkboxes, is it possible to perform such filtering using checkboxes ?

**Comment by michaelbromley** [comment]
Hi,

I'm not totally sure what you mean. The pagination directive supports any filter which would work in an ng-repeat statement.

**Comment by houssem-yahiaoui** [comment]
In fact it was just for how the check boxing filter will work/behave with the directive, and yes after figuring out how to do so, the directive work like charm, cheers !

**Comment by Ingeskhaled** [comment]
Houssem je te demande de répondre au téléphone. j'espère pour toi que tu ne vas pas faire ce que je pense que tu fais !!

**Comment by Ingeskhaled** [comment]
Bonjour les gars, j'ai publié un message par erreur. Merci de ne pas prendre en compte !!
