### ISSUE TITLE
dirPagination: dirPaginate causes ng-click to fire on all rows in a table when clicking on a single row in IE 8

### ISSUE THREAD

**Issue by jokoso** [michaelbromley/angularUtils#44]
Hi Michael
First, thanks for your pagination solution. I is exactly what I was looking for.

I've run into a problem when using it in IE 8 where I have a table of users to display. Each row has an ng-click directive attached so that when a row is clicked that specific user's details are displayed in a modal dialog. When I run the application in Firefox or Chrome everything works as intended, but when run in IE 8 clicking a row in the table causes a chain reaction where ng-click is fired for every single row in the table, displaying a modal dialog for every single user all at once, and IE 8 ends up hanging.

Here's the code:

``` html
...
<tr dir-paginate="user in users | orderBy:orderByField:isReverseSort | itemsPerPage:15"
    current-page="paginationCurrentPage"
    ng-click="openUserDetailsModal(user)">
  <td>user.name</td>
...
```

I found out that attaching the ng-click directive to each `<td>` element in a row instead of to the `<tr>` element solves the problem, but I can't imagine this is the desired behavior.

**Comment by StuBramley** [comment]
I'm also experiencing this issue and was interested to know if there is an alternative solution to the above workarounds? 
I have several pages with this construct on and oddly it doesn't always work incorrectly. In the instances where it does, it seems that there is an 'ng339' attribute added by Angular to the row, which has an identical value for all rows. In those where it works correctly, this value is unique. I am guessing that this is some means of linking the scope internally to Angular..
