### ISSUE TITLE
Async pagination renders fetched items before changing page?

### ISSUE THREAD

**Issue by kcliffe** [michaelbromley/angularUtils#441]
We've implemented server side paging / filtering in a manner (as far as we can tell) the same as the async sample in the docs. 

What we're seeing is if we click on a page which invokes the server side fetch, the items fetched for the new page are inserted into repeater items for the current page. Then a spit second later... the new items are correctly rendered.

E.g We have items 1-5 on the current page. We click next page. Items 1-10 are rendered (6-10 are inserted first), then the repeater refreshes with items 6-10. 

Our directives:
```
  <tr dir-paginate="rt in vm.List | itemsPerPage: vm.itemsPerPage"
                    total-items="vm.totalItems"
                    current-page="vm.currentPage">
```
```
 <dir-pagination-controls on-page-change="vm.fetchStuff(newPageNumber)"></dir-pagination-controls>
</div>
```

Controller (TypeScript) code
```
 public fetchStuff(newPageNumber?: number): void {
        
        const filterstring: any = this.rosterGroupParentService.getFilter();

        this.rosterService.getRosterTemplates(filterstring, this.search, this.viewCurrent, this.currentPage, this.itemsPerPage).then((response: any) => {
            this.List = response.results;
            this.totalItems = response.total;
        }).catch((response: any) => {
            console.log("Roster templates list - no response");
        });
    }
```

Thanks for any help!

**Comment by kcliffe** [comment]
Closing this issue - turn out it was due to somebody embedding a CSS transition into one of our stylesheets!

**Comment by atefBB** [comment]
Hey @kcliffe ! I have the same issue, how to solve it?

**Comment by kcliffe** [comment]
Atef - I could only suggest the solution we found - a CSS transition was the cause of our issue. Check your stylesheets.

**Comment by atefBB** [comment]
Thanks @kcliffe !
