### ISSUE TITLE
It doesnot work with as keyword in angular js - ng-repeat="friend in friends | filter:q as results"

### ISSUE THREAD

**Issue by yugansh20** [michaelbromley/angularUtils#448]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can:

- Title: Please indicate the module in question, e.g. "dirPagination: X is broken when Y"
- If reporting on dirPagination, please include the version you are using (can be found in the package.json / bower.json file)
- If you are able to reproduce your issue on Plunker, this will vastly increase the chances of a rapid response from me.

-- Michael 

=======
(Delete the above. Fill in the rest as applicable)

**Description of issue**:
When we use 
<div dir-paginate="friend in friends  | itemsPerPage : itemsPerPage as results">
The value of results always remain undefined.
Though results gets assigned in the angular version 1.3.17+. 

**Steps to reproduce**: 
Anywhere in the dir-paginate attribute add "as results" or any variable name and check the value of that variable by printing in console, it will be undefined.
**Expected result**:
The value of results should be the current filtered items/rows that are shown on the page.
**Actual result**:
Undefined.
**Demo**: (for dirPagination, fork and modify this Plunk: http://plnkr.co/edit/b37IdFFJUokaeSummETX?p=preview)

Any relevant code:
```

```

You can check this here - https://docs.angularjs.org/api/ng/directive/ngRepeat.
Check the last example.

**Comment by schester44** [comment]
I'm having trouble with using the 'as' keyword as well. I get the following error

`pagination directive: the 'itemsPerPage' filter must be set. <template-list-item class="table-list-item" dir-paginate="template in $ctrl.items | filter: $ctrl.searchString as filteredTemplates | itemsPerPage: 2" item="template">`

**Comment by schester44** [comment]
ahh disregard.. this is a duplicate.

found my answer here:
https://github.com/michaelbromley/angularUtils/issues/328
