### ISSUE TITLE
dirPaginate: show controls above pagination table

### ISSUE THREAD

**Issue by marclazell** [michaelbromley/angularUtils#47]
I'm looking for a way to show the controls at the top of the table as well as at the bottom. If I put them above I get the following error in the console:

pagination directive: the pagination controls (id: blnTbl) cannot be used without the corresponding pagination directive. <dir-pagination-controls boundary-links="true" template-url="pagination/dirPagination.tpl.html" pagination-id="blnTbl" class="ng-isolate-scope"> 

The paginated table is in a directive, which is inside another directive, which then prints out the table to the screen.

Thanks.

**Comment by psk2** [comment]
Hi, when i'm using your code, it works great, well and fine.
but as I've lot more records to get fetched, when I use sort function in 'dir-paginate', it is sorting the whole all records.
but I need only those records to get sorted which are displaying in the current page using 'itemsperpage' element.
Can some one help me please..
