### ISSUE TITLE
When using bower dirPagination.tpl.html is not installed in directives/pagination

### ISSUE THREAD

**Issue by godinger** [michaelbromley/angularUtils#48]
I used bower to get your program. I have to modify dirPagination.js line 23 (var templatePath) to avoid an error. When bower installs your program, it is installed to bower_componenets\angular-utils-pagination. However, dirPagination.js looks for it in directives/pagination, and it is not there.

To get it to work I have to move/copy the file to directives/pagination. Shouldn't it just look for the file in the same directory as it is in? Otherwise, I have to use this workaround (copy the file manually), which is not desirable, and when you update the file (it would be updated via bower) I'd have to re-copy the file.

**Comment by sjain7200** [comment]
I have added this into my html.<dir-pagination-controls boundary-links="true" on-page-change="pageChanged(newPageNumber)" template-url="dirPagination.tpl.html"></dir-pagination-controls>

But still i am getting http://localhost:8080/Project/dirPagination.tpl.html Failed to load resource: the server responded with a status of 404 (Not Found)
