### ISSUE TITLE
dirPagination: How can I add changing url when page is changed?

### ISSUE THREAD

**Issue by EJIqpEP** [michaelbromley/angularUtils#49]
Hi. Your library is very good but I cannot find any info about how to change page number in url.
For example:
http://example.com/users?page=2
I want to load data for second page on controller init and change page number on click on other page.
I use ui-router if it can help.

**Comment by sanket-webmavens** [comment]
Can anyone give solution/gist for this, sorry but I am not familiar with CoffeeScript. Thanks !!
