### ISSUE TITLE
Reset the pagination to 1 when length changes

### ISSUE THREAD

**Issue by rahil471** [michaelbromley/angularUtils#61]
Hi Michael!
Nice work,
Although I have an issue :
I'm using x-editable(Angular) for edit in place, but when i add a new row(form) to the table it is obviously added to the 1st page.
What i want here to happen is : _When i add a new row i want the pagination to reset to 1st page so that the user can enter details and hit save._

**Comment by williamsousa** [comment]
Hey guys...

I've the same problem, I tried to do $scope.currentPage = 1, but doesn't work.

I wonder if there's another way to force the paging go to No. 1 after clicking a button.

Thanks

**Comment by michaelbromley** [comment]
Hi,

Could you show your code and I can see if there is a reason why it is not working?

**Comment by williamsousa** [comment]
In my directive: (in coffeeScript)
<pre>
scope.currentPage = 1

scope.callService = () ->
       //... call $http.get ...
       scope.currentPage = 1
</pre>

In my view:

<pre>
<dir-paginate current-page="currentPage"></dir-paginate>
<button ng-click="callService()">View More</button>
</pre>

After clicked in the button, will called the service and current-page need to be the first page again, but this not happened.

You know why?

**Comment by giumarzo** [comment]
Hi,
I found a solution:
```
function(collection) {
                        if (collection) {
                            **paginationService.setCurrentPage(paginationId, 1);**
                            var collectionLength = (collection instanceof Array) ? collection.length : Object.keys(collection).length;
                            paginationService.setCollectionLength(paginationId, collectionLength);
                        }
```
