### ISSUE TITLE
dirPagination: IE8 Unknown runtime error & Unexpected call to method or property access.undefined !

### ISSUE THREAD

**Issue by xianxin** [michaelbromley/angularUtils#64]
I downloaded your demo project in plnkr(http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview) and replaced the "data-require" script with local javascript files like 
```javascript
  <script src="angular.js" language="javascript" type="text/javascript"></script>
  <script src="jquery-1.7.min.js" language="javascript" type="text/javascript"></script>
```
Then I run in IE8(Simulated by IE 11 F12 tool) . At first I got this problem : Unknown runtime error , I tracked down the source and found the scene of accident 
```javascript
forEach({
  removeData: jqLiteRemoveData,

  dealoc: jqLiteDealoc,

  on: function onFn(element, type, fn, unsupported){
    if (isDefined(unsupported)) throw jqLiteMinErr('onargs', 'jqLite#on() does not support the `selector` or `eventData` parameters');

    var events = jqLiteExpandoStore(element, 'events'),
        handle = jqLiteExpandoStore(element, 'handle');

    if (!events) jqLiteExpandoStore(element, 'events', events = {});
    if (!handle) jqLiteExpandoStore(element, 'handle', handle = createEventHandler(element, events));
```
in createEventHandler
```javascript
// Remove monkey-patched methods (IE),
    // as they would cause memory leaks in IE8.
    if (msie <= 8) {
      // IE7/8 does not allow to delete property on native object
      event.preventDefault = null;
      event.stopPropagation = null;
      event.isDefaultPrevented = null;
    } else {
```

I don't ready know what happened but i fix this problem by placing "jquery-1.7.min.js" before "angular.js" .

And then i got this "Unexpected call to method or property access.undefined" , i found the solution here(https://github.com/angular/angular.js/issues/1933). You should always set " replace : true " when you use a " restrict:'E' " ! (user-defined tags are not supported by IE 8 by default.)

**Comment by rzero008** [comment]
@michaelbromley 

"However, there is a simple fix to get it working in IE8 - just use dir-pagination-controls as an attribute, rather than an element."

with that said, I just want to clarify if this is correct. I changed it from 
<dir-pagination-controls template-url="dirPagination.tpl.html" pagination-id="cust"></dir-pagination-controls> 
 to
 <div dir-pagination-controls template-url="dirPagination.tpl.html" pagination-id="cust"></div> 
but the pagination still didn't showed up. Any thoughts ?

Thanks Micheal.

**Comment by michaelbromley** [comment]
Hi,

in your example there you have missed an "s" off the end of the attribute name. Does adding one fix it?

**Comment by rzero008** [comment]
Hi,

I'm sorry I mistype it here, its actually div dir-pagination-controls. So going back to my issue I just did make the dir-pagination-controls to element but the pagination still didn't render in IE8. 
![ie8](https://cloud.githubusercontent.com/assets/7752489/6222061/8c5574b6-b688-11e4-8564-a70ffed8399e.jpg)

Thanks Micheal.

**Comment by michaelbromley** [comment]
Ah - the console output reveals the problem. You are using jQuery 2.x, which does not support IE8. You should switch to the [1.x branch](http://jquery.com/download/#jquery-1-x) and see if that works.

**Comment by rzero008** [comment]
Hi,

I did switch it to jquery-1.11.2.min.js and AngularJS v1.2.26 (since 1.3 didn't support IE8). Here is my screenshot. Now the only errors were shown were Unknown runtime error.

![same ie8 problem](https://cloud.githubusercontent.com/assets/7752489/6241433/9cabdb5a-b757-11e4-99b4-4bde2a8ba43a.png)

Thanks Micheal.

**Comment by DevsExMachina** [comment]
Hi Micheal - I'm having problems with IE8 too, running the correct version of Angular & jQuery and dir-pagination-controls as an attribute but get a type error 'Node' is undefined and a the pagination controls cannot be used without the corresponding directive error ... any ideas? Many thanks tim

**Comment by michaelbromley** [comment]
@DevsExMachina Can you show me the view code you are using?

**Comment by DevsExMachina** [comment]
Hi Yes indeed .. html5shiv & respond for IE8 plus the compatible versions of jQuery & Angular with my minified js after..

	

	<script src="app/lib/jquery-1.11.1.min.js"></script>
	<script src="app/lib/bootstrap.min.js"></script>

	<script src="app/lib/angular.min.js"></script>
	<script src="app/lib/angular-route.min.js"></script>

	<script src="app/js/script.js" type="text/javascript"></script>

In the partial ....


<section class="container" ng-controller="MentorsControl">

		<header id="mentorsHeader">
			
			<ul class="filters">
				<li><a href="" ng-click="tag=''">All</a></li>
				<li><a href="" ng-click="tag={company: 'myCompany'}">myCompany</a></li>
				<li><a href="" ng-click="tag={company: 'myCompany2'}">myCompany2</a></li>
				<li><a href="" ng-click="tag={tag: 'industrylead'}">Industry Leaders</a></li>
			</ul>


			<label class="hideOffScreen" for="mentorsSearchId">Search Mentors</label>
			<input ng-model="searchQuery" id="mentorsSearchId" placeholder="Search Mentors">

		</header>

		<div id="mentorsDisplay">

			<div class="mentor" dir-paginate="item in mentorsList | filter : searchQuery | filter: tag | itemsPerPage: 10">

				<span ng-if="item.show">

			    	<img ng-src="{{item.src}}" alt="{{item.name}}" class="img-rounded">

					<div class="figcaption">
						<span class="name">{{item.name}}</span><br>
						<span class="position">{{item.position}}</span>
						<span class="company">{{item.company}}</span>
					</div>

				</span>

		    </div>

		</div>


		<div class="paginationWrapper">


			<div dir-pagination-controls></div>


		</div>

	</section>

In the controller..

	acceleratorControllers.controller('MentorsControl', ['$scope','$http', function($scope, $http){

		$http.get('app/json/stubs/mentors.json').success(function(data){

			$scope.mentorsList = data;

		});

	}]);





![screen shot 2015-06-04 at 10 19 33](https://cloud.githubusercontent.com/assets/4740852/7980907/42353654-0aa3-11e5-9ced-b1c475665769.png)

**Comment by paoloromeo13** [comment]
Hi I too am getting the exact same error as @DevsExMachina. I have the exact same set up as they do only difference being variables names are different but everything else exactly the same.

Is there are fix for this?

**Comment by michaelbromley** [comment]
Hi,

I've not had time to look into this yet (I can generally only work on this in free time at the moment). I'm reopening it and marking it to handle for the next update.

**Comment by tomchiverton** [comment]
With these tiny changes, works for me in IE8 : 
https://github.com/michaelbromley/angularUtils/pull/184

**Comment by beatoss** [comment]
I had the same issue in IE 8. With tomchivertons changes it worked. Thank you both!

**Comment by michaelbromley** [comment]
@tomchiverton thanks for the fix!
