### ISSUE TITLE
Index/row number independent of pagination.

### ISSUE THREAD

**Issue by rahil471** [michaelbromley/angularUtils#76]
Hi Michael,
How can i get row/$index number independent of page number.
I'm Highlighting the table row based on $index but when i use  Pagination the $index is reset to start from 0,1,3... and so on, for every page.

For example the second row of second page should have row number or $index as 7 (if Items per page is 5)

Hope you understood my problem,
Awaiting your response.

**Comment by reshma-ti** [comment]
@michaelbromley thank you for the answer...

**Comment by clean-urls-ceramic** [comment]
> Okay, no problem.
> 
> Re. paginating an object, this is not currently supported. See this issue on it: [#20](https://github.com/michaelbromley/angularUtils/issues/20)





https://openjs.space/questions/the-value-of-index-remains-constant-for-every-page-that-utilizes-dir-paginate
