### ISSUE TITLE
dirPagination: make pagination template embedded

### ISSUE THREAD

**Issue by luisrudge** [michaelbromley/angularUtils#88]
https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#specifying-the-template

The template should be embedded into the directive - accepting an path argument that overrides the default.

**Comment by mpkorstanje** [comment]
What is the current status? I wouldn't mind submitting a pull request.

**Comment by michaelbromley** [comment]
Wow this is really old. I guess the original person dropped it since we've not heard anything for several months.

Feel free to submit a PR and I'll take a look.

**Comment by mpkorstanje** [comment]
Okay. I see where the problem lies.

1. Presently it is not possible to provide both a template and a templateUrl in the directive config object.
2. When the choice needs to be made between the template and templateUrl, only the paginationTemplate.getPath() is available while attrs.templateUrl is not.

I'll see if I can by pass this with the $templateCache.

**Comment by mpkorstanje** [comment]
Done. See #138.

I would give you a plunker to show it works but plunker doesn't seem to be working.

**Comment by mpkorstanje** [comment]
http://plnkr.co/edit/OoktJx?p=preview

Removed the template and template-url from the directive to show it picks up the template from the cache. Couldn't think of a unit test for it.

**Comment by michaelbromley** [comment]
Thanks, I'll have time to properly review and decide on your changes soon, hopefully in the next couple of days.

**Comment by epelc** [comment]
Do you have to add this? It's adding extra html for anyone who doesn't use the default or anyone who uses something besides bootstrap.

**Comment by mpkorstanje** [comment]
Yes. Not having the default html embedded makes this module hard to use with module managers. Playing easy with module managers makes maintenance easier.

**Comment by epelc** [comment]
Could you provide a version of the js without the template embeded?

Also if you use Webpack it's just an extra require if you wanted to use the default template. But I do suppose this might be harder if you use an older tool.

**Comment by benoror** [comment]
+1 this feature, I am having issues using this directive with Webpack:

https://github.com/teux/ng-cache-loader/issues/10
https://github.com/WearyMonkey/ngtemplate-loader/issues/21

**Comment by michaelbromley** [comment]
So, the embedded template fixed things for one toolset and created issues with another...

I'm new to Webpack. Could someone give me a simple explanation of why the embedded template would cause issues?

**Comment by epelc** [comment]
It's not an issue with webpack. It's a general issue of if you use a custom template then you are forced to load an extra default one which makes your output from any tool (or manual import) larger than it needs to be.

This could be fixed with updates to the directory paginate build process. If you give a js file with the default template and one without then we could pick which one to use. Plus it'd still be easy for new people to use the default with the template included.

**Comment by michaelbromley** [comment]
Okay. It's not a top priority right now since I have a backlog of actual bugs and other issues, but I'll leave this issue open for further feedback and I will consider having two versions.

**Comment by devourment77** [comment]
I am also using webpack, is it possible to use a template string instead of a URL for a custom template?

**Comment by michaelbromley** [comment]
@devourment77 Having just started using Webpack myself, I finally understand this issue :)

I agree that it would be useful to be able to pass a string for this case. I do not have time to work on it myself right now, but I welcome anyone who wants to put in a pull request.

**Comment by devourment77** [comment]
This is what I am doing currently in my config and it seems to be working when I use the directive.

```
/**
 * Setup the pagination template.  It doesn't have template string support yet so we have to to fake with
 * template cache
 * @see https://github.com/michaelbromley/angularUtils/issues/88
 */
let paginationTemplate = require('ngtemplate?module=core!../views/pagination.client.view');
angular.module(ApplicationConfiguration.applicationModuleName).config((paginationTemplateProvider) => {
    paginationTemplateProvider.setPath(paginationTemplate);
});

```

**Comment by simonbuehler** [comment]
@devourment77 where does that code go? i can run it via serverr but the build output doesn't pick up my custom template
